### ISSUE TITLE
faiss(python) can only run in faiss/python directory

### ISSUE THREAD

**Issue by wjtan99** [facebookresearch/faiss#1087]
I have exactly same problem as issue $522 but on version 1.6.1 

# Platform

OS: Ubuntu 16.04 

Faiss version: 1.6.1 

Faiss compilation options:  

Running on:
- [x ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
In python directory, everything is fine.  But in root faiss directory or any other directory,  

python -c "import faiss"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/faiss/__init__.py", line 49, in <module>
  File "build/bdist.linux-x86_64/egg/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: cannot import name _swigfaiss

In issue $522, it says 

The can be fixed with below environment addition. 
export PYTHONPATH=$PYTHONPATH:/opt/faiss/python 

But the faiss is not installed to /opt or other place in the system.   

Thanks a lot.

**Comment by mdouze** [comment]
No activity, closing.
