### ISSUE TITLE
Installation issue - KeyError 'flags' when import faiss

### ISSUE THREAD

**Issue by houssam7737** [facebookresearch/faiss#1098]
# Summary

After running all the installation steps, and I run `python -c "import faiss"` I get a `KeyError: 'flags'` error. I'm installing faiss in a conda environment. For some reason, running `make test_gpu` also fails with a `TestGpuIndexFlat.cpp:9:29: fatal error: faiss/IndexFlat.h: No such file or directory` error. Running `make test` also fails with 16 errors, all due to the `KeyError: 'flags'` error. 

I am aware of the error in #866 where the egg file does not get unzipped, but even after unzipping I still get the error. 

Any help would be much appreciated! I spent a lot of time trying to go through past issues and figure it out but I'm quite stuck.

# Platform

OS: Rhel 7.6 

Faiss version: faiss 1.6.1, commit e0849496ddeccda7a15fa4b2ddeb93639c33c239 

Faiss compilation options: 

`
./configure --with-cuda=/usr/local/cuda-10.1 --with-blas=/usr/lib64/libblas.so.3 --with-lapack=/usr/lib64/liblapack.so.3 --prefix=/nobackup/users/houssam/anaconda3/envs/NAME_OF_ENV

make 

make install 

make SWIG=/home/houssam/swig/bin/swig py

make -C python install`

After this step I proceeded to the `site-packages` folder and manually unzipped the egg file.  

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

`
python -c "import faiss"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nobackup/users/houssam/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/faiss/__init__.py", line 38, in <module>
    instr_set = instruction_set()
  File "/nobackup/users/houssam/anaconda3/envs/wmlce-1.6.2/lib/python3.6/site-packages/faiss/__init__.py", line 31, in instruction_set
    if "avx2" in numpy.distutils.cpuinfo.cpu.info[0]['flags']:
KeyError: 'flags'
`

**Comment by houssam7737** [comment]
Also, running in a python shell:

`
import numpy.distutils.cpuinfo
numpy.distutils.cpuinfo.cpu.info[0]
`
I get: `{'uname_m': 'ppc64le', 'processor': '0', 'cpu': 'POWER9, altivec supported', 'clock': '3616.000000MHz', 'revision': '2.1 (pvr 004e 1201)'}` so there is actually no 'flags' keyword ??

**Comment by mdouze** [comment]
You are running on an unusual architecture, so I can't really test this, but I am interested in any feedback on Faiss on PPC.  
avx2 is specific to intel architectures, so you could add a test case for platform.system() == what your system returns.

**Comment by mdouze** [comment]
No activity, closing.

**Comment by gilbertfrancois** [comment]
Hi, I have the same issue, when compiling on ARMv8 (Jetson Xavier)
```
$ uname -a
Linux 3b7650e1cdad 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:52:02 PST 2019 aarch64 aarch64 aarch64 GNU/Linux
```

After importing Faiss, I see the "KeyError: flags".

Running the following in a python interpreter, gives:

```
>>> import numpy.distutils.cpuinfo
>>> numpy.distutils.cpuinfo.cpu.info[0]
{'uname_m': 'aarch64', 'processor': '0', 'model name': 'ARMv8 Processor rev 0 (v8l)', 'BogoMIPS': '62.50', 'Features': 'fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp', 'CPU implementer': '0x4e', 'CPU architecture': '8', 'CPU variant': '0x0', 'CPU part': '0x004', 'CPU revision': '0', 'MTS version': '45309758'}

>>> import platform
>>> platform.system()
'Linux'
```
