### ISSUE TITLE
CUDA error 77 an illegal memory access was encountered

### ISSUE THREAD

**Issue by mrgransky** [facebookresearch/faiss#1194]
Given the following script:

```
import numpy as np
import faiss, time, os
d, nb, nq = 3211264, 3450, 3450

np.random.seed(1234)      # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

res = faiss.StandardGpuResources()
ivfflat_config = faiss.GpuIndexIVFFlatConfig()
nlists = 10
index = faiss.GpuIndexIVFFlat(res, d, nlists, faiss.METRIC_L2, ivfflat_config)
index.reset()
index.train(xb)
index.add(xb)
k = 10 # KNN
D, I = index.search(xq, k)
print(I[:5])
```
I encountered the following error:
```
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>::copyFrom(faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>&, cudaStream_t) [with T = float; int Dim = 2; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits; cudaStream_t = CUstream_st*] at ./faiss/gpu/utils/Tensor-inl.cuh:154; details: CUDA error 77 an illegal memory access was encountered
Aborted
```

OS: 
```
$ lsb_release -a

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
```
My GPU Platform:

```
$ nvidia-smi 
==============NVSMI LOG==============

Timestamp                           : Thu Apr 23 17:12:08 2020
Driver Version                      : 440.64.00
CUDA Version                        : 10.2

Attached GPUs                       : 2
GPU 00000000:18:00.0
    FB Memory Usage
        Total                       : 16160 MiB
        Used                        : 0 MiB
        Free                        : 16160 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB

GPU 00000000:3B:00.0
    FB Memory Usage
        Total                       : 16160 MiB
        Used                        : 0 MiB
        Free                        : 16160 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB


Thu Apr 23 17:12:08 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:18:00.0 Off |                    0 |
| N/A   34C    P0    25W / 250W |      0MiB / 16160MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    25W / 250W |      0MiB / 16160MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Faiss version: 
`1.6.3`
Faiss compilation options: 

Running on:
- [ ] GPU

Interface: 
- [ ] Python

How can I fix the problem?
Cheers,

**Comment by wickedfoo** [comment]
Looking into this.

**Comment by wickedfoo** [comment]
@mrgransky  I haven't tried running this, but looking at your code, your data won't fit into GPU memory anyways:

d, nb, nq = 3211264, 3450, 3450

nb x d is 44 GB in size (3211264 * 3450 * sizeof(float)).

**Comment by mrgransky** [comment]
Yes, u're right and if I alternatively use `faiss.index_cpu_to_all_gpus()` to run the following script:
```
import numpy as np
import faiss, time, os

d, nb, nq = 3211264, 3450, 3450 

##############################################
# 3211264 * 3450 * 4 * 1e-9 =  44.3154432 GB
##############################################

np.random.seed(1234)      # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

cpu_index = faiss.IndexFlatL2(d)
gpu_index = faiss.index_cpu_to_all_gpus(cpu_index)

gpu_index.add(xb)  
print(gpu_index.ntotal)
k = 10   
D, I = gpu_index.search(xq, k) # actual search
print(I[:5])  
```
I get the memory error:

```
Traceback (most recent call last):
  File "tutorial_faiss.py", line 26, in <module>
    gpu_index.add(xb)              # add vectors to the index
  File "/home/alijani/.conda/envs/py27_gpu/lib/python2.7/site-packages/faiss/__init__.py", line 138, in replacement_add
    self.add_c(n, swig_ptr(x))
  File "/home/alijani/.conda/envs/py27_gpu/lib/python2.7/site-packages/faiss/swigfaiss_avx2.py", line 6103, in add
    return _swigfaiss_avx2.IndexReplicas_add(self, n, x)
RuntimeError: Exception thrown from index 0: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 44315443200 bytes (error 2 out of memory)
Exception thrown from index 1: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 44315443200 bytes (error 2 out of memory
```
I am running these sample scripts using SLURM clusters with:

```
#!/bin/bash

#SBATCH -J faiss_tutorial
#SBATCH -o %x_%N_%j_LOG.txt
#SBATCH -e %x_%N_%j_LOG.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16       <<<<< --------------------------------
#SBATCH --mem-per-cpu=24000      <<<<< --------------------------------
#SBATCH --time=3-21:59:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:2

source activate py27_gpu
module loadCUDA/9.0

python tutorial_faiss.py
```
and I get the following log info:

```
Job ID: 9025913
Cluster: narvi
User/Group: alijani/alijani
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:06:25
CPU Efficiency: 6.22% of 01:43:12 core-walltime
Job Wall-clock time: 00:06:27
Memory Utilized: 158.32 GB
Memory Efficiency: 42.22% of 375.00 GB <<<<< -----------
```
I mean doesn't this mean I had `375.00 GB `of memory for my GPU ?  `16 * 24000 = 384 GB
`

**Comment by wickedfoo** [comment]
In your second example you have 32 GiB *per GPU*. It's the *per GPU* that matters. You are replicating the index to each GPU.

**Comment by mrgransky** [comment]
so is there efficient way to handle such huge calculation using faiss after all? cuz `32 GiB * 4GPUs` is all I have.

**Comment by mdouze** [comment]
No activity, closing.

**Comment by mhmd-mst** [comment]
Hello,
I am using Ubuntu 20.04.3 LTS
Language Python
faiss version : 1.7.2
I tried training IVFPQ index on GPU (RTX 2080Ti)
```python
code_sz = 64 # power of 2
n_centroids = 256#
nbits = 8  # nbits must be 8, 12 or 16, The dimension d should be a multiple of M.
index = faiss.IndexIVFPQ(index, d, n_centroids, code_sz, nbits)
```
when I did index.add(data) with dimension 66.4M x 128 and I am using Float 16, I got error:
```
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>::copyFrom(const faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>&, cudaStream_t) [with T = float; int Dim = 2; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits; cudaStream_t = CUstream_st*] at /project/faiss/faiss/gpu/utils/Tensor-inl.cuh:206; details: CUDA error 77 an illegal memory access was encountered
Aborted (core dumped)
```
Then I did it on cpu without FLOAT16 and write_index to save it, then i tried to read_index and move it to GPU with FLOAT16 i get error:
```
Faiss assertion 'gpuListSizeInBytes <= (size_t)std::numeric_limits<int>::max()' failed in void faiss::gpu::IVFBase::addEncodedVectorsToList_(int, const void*, const idx_t*, size_t) at /project/faiss/faiss/gpu/impl/IVFBase.cu:352
Aborted (core dumped)
```
what is the problem?
