### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by bikegirl** [facebookresearch/faiss#1246]
# Summary
 I am currently trying to add about 2.2M embeddings to a FAISS index object, serialize it (using your internal method), pickle dump it, and save it for later use.  It amounts to ~13Gs.  Maybe the problem is I don't have to pickle dump directly after serializing the index?  Is there another way to serialize the index to be able to save it at this size? (I only want to generate the Index one and save it, to be able to run different sim search later).

# Platform

OS: N/A, macOS Catalina 10.15.4

Faiss version: N/A

Faiss compilation options: N/A

Running on:
- [ CUDA 10.1] GPU

Interface: 
- [ ] Python

# Reproduction instructions (excerpt from my code)
`
    xb = np.vstack(xb).astype('float32')

    ## build word faiss index
    quantizer = faiss.IndexFlatIP(d) 
    index = faiss.IndexIVFFlat(quantizer, d, int(np.sqrt(len(xb))), faiss.METRIC_INNER_PRODUCT)
    faiss.normalize_L2(xb)
    index.train(xb)
    index.add(xb)

    # Dumps everything to an output-serialized pickle file
    serialized_index = util.serialize_index(index)
    util.pickle_dump(serialized_index, index_outfile)`

Traceback (most recent call last):
  File "code/word_sim_search.py", line 549, in <module>
    create_faiss_index(giga_dict_outfile, index_outfile, xb_outfile, xq_outfile, words_outfile, qwords_outfile, qsents_outfile, bert_tokenizer, bert_model, SBERT_flag)
  File "code/word_sim_search.py", line 276, in create_faiss_index
    util.pickle_dump(serialized_index, index_outfile)
  File "/mnt/nlpgridio3/data/irebecca/Event-Primitives/code/util.py", line 32, in pickle_dump
    pkl.dump(data, fout)
OverflowError: cannot serialize a bytes object larger than 4 GiB

**Comment by mdouze** [comment]
This is a limitation of the pickle module. 
Why do you want to embed it in a pickle file? You could also: 
- just store to a file with `write_index`
- write the bytes object directly without putting it in a pickle
- use the Python IO callback https://github.com/facebookresearch/faiss/blob/a17a631/tests/test_io.py#L188

**Comment by bikegirl** [comment]
Let me try this.  Pickle is all I know, and I guess up until now I haven't worked with files larger than 4 GiB.  So in my code I have:
`serialized_index = util.serialize_index(index)
util.pickle_dump(serialized_index, index_outfile)`
instead should this be:
`serialized_index = util.serialize_index(index)
faiss.write_index(index, fname)`
?
I ask b/c inside my util.py I copied the serialized method from the website... it looks like this:
`def serialize_index(index):
    """ convert an index to a numpy uint8 array  """
    writer = faiss.VectorIOWriter()
    faiss.write_index(index, writer)
    return faiss.vector_to_array(writer.data)

def deserialize_index(data):
    reader = faiss.VectorIOReader()
    faiss.copy_array_to_vector(data, reader.data)
    return faiss.read_index(reader)`

So it looks like if I use this method it's already writing to this faiss.VectorIOWriter()?  Should I just make this a filename then instead of use this IOWriter()?

**Comment by bikegirl** [comment]
Also, I see this on another GitHub issue to just use `faiss.write_index(index, fname)`:
https://github.com/facebookresearch/faiss/issues/421

But I also try to use faiss.read_index(fname) to be able to load it and run sim_search and this does not work.  Does this load the index?  I'm looking here: https://github.com/facebookresearch/faiss/blob/a17a631/tests/test_io.py#L188

**Comment by bikegirl** [comment]
Sorry, I think I was just psyching myself out b/c I was so hung up on using that prior code I saw from another github issue.  Just wanted to give you and update.  I stopped using that serialize() and deserialized() method above^^^.  I literally just used:
`faiss.write_index(index, index_outfile)`
`index = faiss.read_index(index_outfile)`
And this works now!  Thanks for the response! (-:

**Comment by xloem** [comment]
Note that with protocol version >= 4, pickle can handle bytelengths than 4GB https://peps.python.org/pep-3154/#summary-of-new-opcodes .
