### ISSUE TITLE
Error: 'err == cudaSuccess' failed: failed to cudaMalloc

### ISSUE THREAD

**Issue by ucasiggcas** [facebookresearch/faiss#1253]
Faiss version: 

Running on:
- [x] GPU

Interface: 
- [x] Python

# Reproduction instructions
at first, use the gpu for tensorflow training,
then use the faiss single GPU for search, refer the [script](https://github.com/facebookresearch/faiss/blob/master/tutorial/python/4-GPU.py)

the codes

```
import faiss
import numpy as np
import time
import os


#tf-keras training
import tensorflow as tf

model = tf.keras.Sequential() 
model.add(tf.keras.layers.Dense(512,activation='relu',input_shape=(784,)))
model.add(tf.keras.layers.Dense(256,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.summary()


X_train=np.random.randn(10000,784)
y_train=np.random.randint(0,10,size=10000)

y_train=tf.keras.utils.to_categorical(y_train,10)
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=64,epochs=5)

d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

res = faiss.StandardGpuResources()  # use a single GPU
nlist = 100
quantizer = faiss.IndexFlatL2(d)  # the other index
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
# here we specify METRIC_L2, by default it performs inner-product search

# make it an IVF GPU index
gpu_index_ivf = faiss.index_cpu_to_gpu(res, 0, index_ivf)

assert not gpu_index_ivf.is_trained
gpu_index_ivf.train(xb)        # add vectors to the index
assert gpu_index_ivf.is_trained

gpu_index_ivf.add(xb)          # add vectors to the index
print(gpu_index_ivf.ntotal)

k = 4                          # we want to see 4 nearest neighbors
D, I = gpu_index_ivf.search(xq, k)  # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries
```

the error
```
Traceback (most recent call last):
  File "faiss_org_2.py", line 41, in <module>
    gpu_index_ivf = faiss.index_cpu_to_gpu(res, 0, index_ivf)
  File "/data/logs/。/yes/lib/python3.7/site-packages/faiss/__init__.py", line 448, in replacement_function
    result = original_function(*args)
  File "/data/logs/。/yes/lib/python3.7/site-packages/faiss/swigfaiss.py", line 5053, in index_cpu_to_gpu
    return _swigfaiss.index_cpu_to_gpu(resources, device, index, options)
RuntimeError: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 1610612736 bytes (error 2 out of memory)
```

could you pls help me?
thx

**Comment by mdouze** [comment]
The program runs out of memory. See 
https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#the-gpuresources-object

**Comment by ucasiggcas** [comment]
No，not the question
you didn't see the codes

**Comment by wickedfoo** [comment]
@ucasiggcas no, your program is running out of memory, it can't allocate the 1.5 GB required up front.

**Comment by ucasiggcas** [comment]
now I found that the memory wasn't released after tensorflow-keras training, but I do not konw why
and then cause the problem
maybe its the problem of tensorflow,
so will close
