### ISSUE TITLE
 AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

### ISSUE THREAD

**Issue by cdhx** [facebookresearch/faiss#1285]
use ```pip install faiss-cpu```got error, here is the log
```
Building wheels for collected packages: faiss-cpu
  Building wheel for faiss-cpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\blink37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hx\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"'; __file__='"'"'C:\\Users\\hx\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\hx\AppData\Local\Temp\pip-wheel-3rrts8id'
       cwd: C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 107, in <module>
      ext_modules=[_swigfaiss]
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 45, in run
      build_ext.run(self)
    File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 50, in build_extensions
      self._remove_flag('-Wstrict-prototypes')
    File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 58, in _remove_flag
      compiler = self.compiler.compiler
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
  ----------------------------------------
  ERROR: Failed building wheel for faiss-cpu
  Running setup.py clean for faiss-cpu
Failed to build faiss-cpu
Installing collected packages: faiss-cpu
    Running setup.py install for faiss-cpu ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\blink37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hx\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"'; __file__='"'"'C:\\Users\\黄 祥\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hx\AppData\Local\Temp\pip-record-qsj3c0ie\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\blink37\Include\faiss-cpu'
         cwd: C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\
    Complete output (38 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 107, in <module>
        ext_modules=[_swigfaiss]
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 45, in run
        build_ext.run(self)
      File "C:\ProgramData\Anaconda3\envs\blink37\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 50, in build_extensions
        self._remove_flag('-Wstrict-prototypes')
      File "C:\Users\hx\AppData\Local\Temp\pip-install-drqmfmaj\faiss-cpu\setup.py", line 58, in _remove_flag
        compiler = self.compiler.compiler
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\blink37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hx\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"'; __file__='"'"'C:\\Users\\hx\\AppData\\Local\\Temp\\pip-install-drqmfmaj\\faiss-cpu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hx\AppData\Local\Temp\pip-record-qsj3c0ie\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\blink37\Include\faiss-cpu' Check the logs for full command output.
```

**Comment by cdhx** [comment]
waitting for your help !
thx !

**Comment by ashfaq92** [comment]
Hi, `@cdhx pip install faiss-cpu` is not the official channel. It may result in errors. The original `faiss` library comes with `conda` environment. You must have following configuration for official `faiss` to work:
1. Linux / MacOs operating system
2. conda environment installed [here](https://anaconda.org/anaconda/conda)
3. Python 3.7

Full installation instructions are [here](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md)

**Comment by cdhx** [comment]
@ashfaq92 
thanks for replay!
i will try on linux

**Comment by ashfaq92** [comment]
yes. I have faced same error. Then I tried on linux ubuntu and it is working now
