### ISSUE TITLE
Importing python interface fails with `Symbol not found: _omp_destroy_lock`

### ISSUE THREAD

**Issue by carlgieringer** [facebookresearch/faiss#1289]
# Summary

Importing python interface fails with `Symbol not found: _omp_destroy_lock`

# Platform

OS: macOS 10.15.5
Python: 3.8.3

```
brew info libomp
libomp: stable 10.0.0 (bottled)
```

```
brew info swig
swig: stable 4.0.2 (bottled), HEAD
```

Faiss version: git SHA: 9e5d5b722e1d1bc7ad4c76dd18d9634609ac5257
Faiss compilation options: ./compile --without-cuda

```
pip freeze
numpy==1.19.0
```

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

<details>
  <summary>`./configure --without-cuda`</summary>

```
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features with -std=c++11... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for python... python
checking for Python C flags... -I/Users/factor/.pyenv/versions/3.8.3/include/python3.8 -I/Users/factor/.pyenv/versions/3.8.3/include/python3.8
checking for numpy headers path... /Users/factor/.pyenv/versions/faiss/lib/python3.8/site-packages/numpy/core/include
checking for swig... swig
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for inline... inline
checking for int32_t... yes
checking for int64_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for clock_gettime... yes
checking for floor... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for munmap... yes
checking for pow... yes
checking for sqrt... yes
checking for strerror... yes
checking for strstr... yes
checking for g++ -std=c++11 option to support OpenMP... unsupported
checking build system type... x86_64-apple-darwin19.5.0
checking host system type... x86_64-apple-darwin19.5.0
checking if sgemm_ is being linked in already... no
checking for sgemm_ in -lmkl_intel_lp64... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -lopenblas... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... yes
checking for dgemm_ in -ldgemm... no
checking for sgemm_ in -framework vecLib... no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) yes
checking for sgemm_ in -lessl... no
checking for sgemm_ in -lblas... (cached) yes
checking for cheev_... no
checking for cheev_ in -llapack... yes
checking target system type... x86_64-apple-darwin19.5.0
checking for cpu arch... x86_64-apple-darwin19.5.0 CPUFLAGS+="-mpopcnt -msse4" CXXFLAGS+="-m64"
configure: creating ./config.status
config.status: creating makefile.inc
```
</details>

`make`: https://gist.github.com/carlgieringer/814b45b8525bf71529a26bf88cfc4f0a

<details>
  <summary>`make py`</summary>

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C python
swig -python -c++ -Doverride= -I../  -o swigfaiss.cpp swigfaiss.swig
g++ -std=c++11 -DFINTEGER=int    -fPIC -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -mpopcnt -msse4 -I/Users/factor/.pyenv/versions/3.8.3/include/python3.8 -I/Users/factor/.pyenv/versions/3.8.3/include/python3.8 -I/Users/factor/.pyenv/versions/faiss/lib/python3.8/site-packages/numpy/core/include \
               -I../ -c swigfaiss.cpp -o swigfaiss.o
swigfaiss.cpp:1780:7: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
      0,                                    /* tp_print */
      ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
In file included from swigfaiss.cpp:178:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/Python.h:85:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/pytime.h:6:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/object.h:746:
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:177:16: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
typedef struct _typeobject {
               ^
swigfaiss.cpp:1790:23: note: in implicit copy assignment operator for '_typeobject' first required here
    swigpyobject_type = tmp;
                      ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
In file included from swigfaiss.cpp:178:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/Python.h:85:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/pytime.h:6:
In file included from /Users/factor/.pyenv/versions/3.8.3/include/python3.8/object.h:746:
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:177:16: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
typedef struct _typeobject {
               ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
swigfaiss.cpp:1947:7: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
      0,                                    /* tp_print */
      ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
In file included from swigfaiss.cpp:3110:
In file included from ../faiss/impl/ThreadedIndex.h:80:
../faiss/impl/ThreadedIndex-inl.h:164:48: warning: unused parameter 'index' [-Wunused-parameter]
ThreadedIndex<IndexT>::onAfterAddIndex(IndexT* index) {
                                               ^
../faiss/impl/ThreadedIndex-inl.h:169:51: warning: unused parameter 'index' [-Wunused-parameter]
ThreadedIndex<IndexT>::onAfterRemoveIndex(IndexT* index) {
                                                  ^
swigfaiss.cpp:101639:120: warning: unused parameter 'varargs' [-Wunused-parameter]
SWIGINTERN PyObject *_wrap_MatrixStats_do_comment__varargs__(PyObject *SWIGUNUSEDPARM(self), PyObject *args, PyObject *varargs) {
                                                                                                                       ^
swigfaiss.cpp:114152:9: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0,                                  /* tp_print */
        ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/factor/.pyenv/versions/3.8.3/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
In file included from swigfaiss.cpp:3110:
In file included from ../faiss/impl/ThreadedIndex.h:80:
../faiss/impl/ThreadedIndex-inl.h:123:23: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::pair<faiss::Index *, std::__1::unique_ptr<faiss::WorkerThread,
      std::__1::default_delete<faiss::WorkerThread> > >, std::__1::allocator<std::__1::pair<faiss::Index *, std::__1::unique_ptr<faiss::WorkerThread, std::__1::default_delete<faiss::WorkerThread> > > > >::size_type' (aka 'unsigned long')
      [-Wsign-compare]
    for (int i = 0; i < this->indices_.size(); ++i) {
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~~
swigfaiss.cpp:82989:15: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::Index>::runOnIndex' requested here
      (arg1)->runOnIndex(arg2);
              ^
In file included from swigfaiss.cpp:3110:
In file included from ../faiss/impl/ThreadedIndex.h:80:
../faiss/impl/ThreadedIndex-inl.h:135:23: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::pair<faiss::Index *, std::__1::unique_ptr<faiss::WorkerThread,
      std::__1::default_delete<faiss::WorkerThread> > >, std::__1::allocator<std::__1::pair<faiss::Index *, std::__1::unique_ptr<faiss::WorkerThread, std::__1::default_delete<faiss::WorkerThread> > > > >::size_type' (aka 'unsigned long')
      [-Wsign-compare]
    for (int i = 0; i < this->indices_.size(); ++i) {
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~~
../faiss/impl/ThreadedIndex-inl.h:179:21: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::future<bool>, std::__1::allocator<std::__1::future<bool> > >::size_type' (aka 'unsigned long')
      [-Wsign-compare]
  for (int i = 0; i < v.size(); ++i) {
                  ~ ^ ~~~~~~~~
../faiss/impl/ThreadedIndex-inl.h:129:5: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::Index>::waitAndHandleFutures' requested here
    waitAndHandleFutures(v);
    ^
swigfaiss.cpp:82989:15: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::Index>::runOnIndex' requested here
      (arg1)->runOnIndex(arg2);
              ^
In file included from swigfaiss.cpp:3110:
In file included from ../faiss/impl/ThreadedIndex.h:80:
../faiss/impl/ThreadedIndex-inl.h:123:23: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::pair<faiss::IndexBinary *, std::__1::unique_ptr<faiss::WorkerThread,
      std::__1::default_delete<faiss::WorkerThread> > >, std::__1::allocator<std::__1::pair<faiss::IndexBinary *, std::__1::unique_ptr<faiss::WorkerThread, std::__1::default_delete<faiss::WorkerThread> > > > >::size_type'
      (aka 'unsigned long') [-Wsign-compare]
    for (int i = 0; i < this->indices_.size(); ++i) {
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~~
swigfaiss.cpp:83566:15: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::IndexBinary>::runOnIndex' requested here
      (arg1)->runOnIndex(arg2);
              ^
In file included from swigfaiss.cpp:3110:
In file included from ../faiss/impl/ThreadedIndex.h:80:
../faiss/impl/ThreadedIndex-inl.h:135:23: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::pair<faiss::IndexBinary *, std::__1::unique_ptr<faiss::WorkerThread,
      std::__1::default_delete<faiss::WorkerThread> > >, std::__1::allocator<std::__1::pair<faiss::IndexBinary *, std::__1::unique_ptr<faiss::WorkerThread, std::__1::default_delete<faiss::WorkerThread> > > > >::size_type'
      (aka 'unsigned long') [-Wsign-compare]
    for (int i = 0; i < this->indices_.size(); ++i) {
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~~
../faiss/impl/ThreadedIndex-inl.h:179:21: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::future<bool>, std::__1::allocator<std::__1::future<bool> > >::size_type' (aka 'unsigned long')
      [-Wsign-compare]
  for (int i = 0; i < v.size(); ++i) {
                  ~ ^ ~~~~~~~~
../faiss/impl/ThreadedIndex-inl.h:129:5: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::IndexBinary>::waitAndHandleFutures' requested here
    waitAndHandleFutures(v);
    ^
swigfaiss.cpp:83566:15: note: in instantiation of member function 'faiss::ThreadedIndex<faiss::IndexBinary>::runOnIndex' requested here
      (arg1)->runOnIndex(arg2);
              ^
14 warnings generated.
g++ -std=c++11 -dynamiclib -undefined dynamic_lookup  -o _swigfaiss.so swigfaiss.o ../libfaiss.a -lblas -llapack
python setup.py build
running build
running build_py
copying faiss/__init__.py -> build/lib/faiss
copying faiss/swigfaiss.py -> build/lib/faiss
copying faiss/_swigfaiss.so -> build/lib/faiss
rm swigfaiss.o
```
</details>

Try using `faiss` Python interface:

```
$ cd python
$ python
Python 3.8.3 (default, Jun 28 2020, 18:05:06)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "/Users/factor/code/github/facebookresearch/faiss/python/faiss/__init__.py", line 44, in <module>
    from .swigfaiss import *
  File "/Users/factor/code/github/facebookresearch/faiss/python/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: dlopen(/Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so, 2): Symbol not found: _omp_destroy_lock
  Referenced from: /Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so
  Expected in: flat namespace
 in /Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/factor/code/github/facebookresearch/faiss/python/faiss/__init__.py", line 49, in <module>
    from .swigfaiss import *
  File "/Users/factor/code/github/facebookresearch/faiss/python/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: dlopen(/Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so, 2): Symbol not found: _omp_destroy_lock
  Referenced from: /Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so
  Expected in: flat namespace
 in /Users/factor/code/github/facebookresearch/faiss/python/faiss/_swigfaiss.so
```

**Comment by mdouze** [comment]
no activity, closing.

**Comment by maoxiajun** [comment]
same problem occurred to me, is python 3.8+ supported by faiss python api ?
