### ISSUE TITLE
FAISS doesn't work with CUDA 10.1 

### ISSUE THREAD

**Issue by ofirpress** [facebookresearch/faiss#1295]
# Summary
I'm on Linux, I set up a fresh conda env and type:
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
conda install faiss-gpu cudatoolkit=10.1 -c pytorch 

When I do 'import faiss-gpu' I get:

```
Traceback (most recent call last):
  File "/private/home/ofirp/.conda/envs/test_faiss/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/private/home/ofirp/.conda/envs/test_faiss/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

```
Thanks!

# Platform

OS: Linux

Faiss version: faiss-gpu

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by kobiso** [comment]
Same error occurs with CUDA 10.2 as well.

**Comment by tw991** [comment]
Follow up on this. We are also hit by the same problem, especially pytorch starts with cuda 10.1 now.

**Comment by okhat** [comment]
+1 This would be really useful with pytorch 1.6.

**Comment by Crescentz** [comment]
watch

**Comment by mthielk** [comment]
Has anyone tried compiling for GPU?

**Comment by kobiso** [comment]
Instead of installing FAISS by conda, I solved this problem by [compile-from-source](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#compile-from-source).
It is a little hassle to install, but it works fine for both cuda 10.1 and 10.2.

**Comment by tangzhy** [comment]
mark

**Comment by hkunzhe** [comment]
There are some already [compiled builds](https://anaconda.org/conda-forge/faiss) for cuda 10.1, 10.2, and 11.0 in the conda-forge channel. To install a specific build, try `conda search faiss=<version> --info -c conda-forge` and find the no-conflict one with your environment. Then you can install by `conda install faiss=<version>=<build_string>`, e.g., `conda install faiss=1.6.3=py37hddabd6f_3_cuda -c conda-forge`.

**Comment by yushi-okunishi** [comment]
https://github.com/facebookresearch/faiss/issues/1606#issuecomment-757338945
I was able to import faiss in Docker container from `pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel` thanks to this comment.
