### ISSUE TITLE
in method 'IndexIVFPQ_encode', argument 3 of type 'float const *'

### ISSUE THREAD

**Issue by jngywang** [facebookresearch/faiss#1307]
# Summary

The source code shows it takes 3 parameters: "void encode (idx_t key, const float * x, uint8_t * code) const;". x in type "const float *" but a numpy 2d array in float32 doesn't work as below. Also, the example on wiki https://github.com/facebookresearch/faiss/wiki/Vector-codecs#example-usage doesn't work, it says index has no attribute of "encode".

# Platform

OS:  mac/Ubuntu

Faiss version:  1.6.3

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
>>> n = 10000
>>> x = np.random.rand(n, 20).astype('float32')
>>> codec = faiss.index_factory(20, "OPQ16_64,IVF256,PQ16")
>>> codec.train(x)
>>> codec_ivf = faiss.downcast_index(codec.index)
>>> output = np.zeros((n, 16)).astype(np.float32)
>>> code = codec_ivf.encode(0,x,output)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/faiss/swigfaiss.py", line 3219, in encode
    return _swigfaiss.IndexIVFPQ_encode(self, key, x, code)
TypeError: in method 'IndexIVFPQ_encode', argument 3 of type 'float const *'

**Comment by mdouze** [comment]
It's probably best to use the codec interface here, see

https://github.com/facebookresearch/faiss/wiki/Vector-codecs

Then you can just write

```
output = codec_ivf.sa_encode(x)
```

**Comment by jngywang** [comment]
Thanks Matthijs! `output = codec.sa_encode(x)` works

**Comment by jngywang** [comment]
>>> output = codec.sa_encode(x)
>>> output.shape
(10000, 17)

why the compressed size is 17 instead of 16?

**Comment by mdouze** [comment]
Because it includes the 1 byte for the coarse quantizer (IVF256). If you don't want that component use "OPQ16_64,PQ16".

**Comment by jngywang** [comment]
Super helpful! Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mdouze** [comment]
no activity, closing.
