### ISSUE TITLE
Huge dataset causes cuda OOM

### ISSUE THREAD

**Issue by seanchung2** [facebookresearch/faiss#1323]
# Summary

As my dataset is about 240GB, I implemented something similar to this [`demo_ondisk_ivf.py`](https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py).

When I load the `populated.index` and convert to gpu version by `index_cpu_to_all_gpus()`, a `RuntimeError` error occurs as it fails to allocate memory on GPU.

I'd wonder if there's any solution to this? Thank you

# Platform

Hardware: EC2 instance p2.16xlarge

Faiss version: 1.6.3

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

As mentioned in **_summary_**

 
```
Traceback (most recent call last):
  File "query_search.py", line 264, in <module>
    search(s3_client, "Q1")
  File "query_search.py", line 234, in search
    index = faiss.index_cpu_to_all_gpus(index)
  File "/home/ec2-user/anaconda3/envs/tf22_gpu/lib/python3.6/site-packages/faiss/__init__.py", line 518, in index_cpu_to_all_gpus
    index_gpu = index_cpu_to_gpus_list(index, co=co, gpus=None, ngpu=ngpu)
  File "/home/ec2-user/anaconda3/envs/tf22_gpu/lib/python3.6/site-packages/faiss/__init__.py", line 530, in index_cpu_to_gpus_list
    index_gpu = index_cpu_to_gpu_multiple_py(res, index, co, gpus)
  File "/home/ec2-user/anaconda3/envs/tf22_gpu/lib/python3.6/site-packages/faiss/__init__.py", line 512, in index_cpu_to_gpu_multiple_py
    index = index_cpu_to_gpu_multiple(vres, vdev, index, co)
  File "/home/ec2-user/anaconda3/envs/tf22_gpu/lib/python3.6/site-packages/faiss/swigfaiss.py", line 5056, in index_cpu_to_gpu_multiple
    return _swigfaiss.index_cpu_to_gpu_multiple(resources, devices, index, options)
RuntimeError: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 138700800 bytes (error 2 out of memory)
```

**Comment by mdouze** [comment]
240 GB most likely does not fit on the GPUs. Where do you want/expect the data to reside at search time?

**Comment by seanchung2** [comment]
Thank you for your reply.

Right now I could leave it in RAM, but when it comes to larger dataset, it could only resides in disk.

As process time is critical for me, I was wondering if you have any suggestion for current and future (larger dataset) situation respectively?

Thank you.

**Comment by mdouze** [comment]
See https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM

**Comment by seanchung2** [comment]
Thank you and I did use on disk strategy already.

One quick question: is it possible to feed in data chunk by chunk to `train()`. That is, when doing `index.train("data")`, could we first split up data to say 5 chunks and train the same index separately with these five chunks?

**Comment by mdouze** [comment]
I mean that using a distributed index is also an option if the dataset does not fit in RAM.

It is not possible to train with shards. It would not make much sense because at training time the data is not compressed so at some point it has to materialize as a full array in RAM anyways.

**Comment by mdouze** [comment]
No activity, closing.

**Comment by ZenBel** [comment]
I would like to re-open the discussion to clarify how to work with large datasets. My dataset `X` has 1.8TB of data (~450M 1024-vectors). There are 3 steps to the process (pseudo-code below):

1. Train the index (assuming access to a multi-gpu machine)
```python
d = X.shape[1]
index = faiss.index_factory(d, "OPQ64,IVF131072,PQ64")
co = faiss.GpuMultipleClonerOptions()
co.useFloat16 = True
index = faiss.index_cpu_to_all_gpus(index, co=co)
xb = subsample(X) # ~ 100 * num centroids index
index.train(xb)
```
2. Populate the index
```python
faiss.index_gpu_to_cpu(index) # moving to CPU because populatind index on GPU causes OOM
dl = build_dataloader(X, batch_size=2**14) # populate index in batches due to size of X
for batch in dl:
    index.add(batch)
```
Q1: is there a way to populate the index with so many vectors on the GPU without incurring in OOM?
Q2: If not, what is the best strategy to populate the index?

3. Search
```python
index.search(xq)
```
Q3: My understanding is that, if the index fits on GPU then search on GPU, otherwise load index in RAM and search with CPU. If index does not even fit on GPU, then save index on disk. Is this correct?
Q4: Are there any other strategies to optimize step 2 and 3 in terms of memory/speed?

Thank you in advance,

Z

**Comment by ucas010** [comment]
PQ only for 8bit if you do not have much RAM, give up 
and your data  should in cpu 
my dataset is largest 1 billion and dim=768, can't be run in 4*L20 GPU (46G per GPU )
