### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by MaheshChandrra** [facebookresearch/faiss#1389]
# Summary

Hi Team faiss

I'm using BERT in combination with faiss  for semantic similarity ,where the embedding dimension by BERT for a document is 768,like wise I was able to create indexes for 3.2 million but after that If I try to create indexes I'm getting the below memory error,I passed the embeddings of 100000 each time to the faiss for creating the indexes,after reading the  [bad alloc 20million](https://github.com/facebookresearch/faiss/issues/302) , I've changed the batch size to 1000,even still I'm getting the below error.The index file size for 3.2M is close to 10GB ,and there is space available in RAM,and I'm unable to add anymore indexes to the file. 
```
start_index=0
end_index=1000

from sentence_transformers import SentenceTransformer
embedder=SentenceTransformer('bert-base-nli-mean-tokens')

index = faiss.IndexIDMap(faiss.IndexFlatIP(768))

Traceback (most recent call last):
  File "create_indexes.py", line 42, in <module>
    generate_indexes(df_main,'Y','till_2019')
  File "create_indexes.py", line 30, in generate_indexes
    index.add_with_ids(np.array(embedder.encode(df_main['Text'][start_index:end_index].values,show_progress_bar=True),dtype='float32'),np.array(df_main['ID'][start_index:end_index].values))
  File "/home/mahesh/anaconda3/lib/python3.7/site-packages/faiss/__init__.py", line 144, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "/home/mahesh/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 3877, in add_with_ids
    return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
MemoryError: std::bad_alloc
```

Please let me know how to proceed further.
Thanks in advance.

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by QwertyJack** [comment]
I guess there is some memory bloat in your case. Try to write the intermediate results (i.e. vectors and ids generated by bert) onto the disk and then build the index.

**Comment by mdouze** [comment]
No activity, closing.

**Comment by Xnhyacinth** [comment]
> # Summary
> Hi Team faiss
> 
> I'm using BERT in combination with faiss for semantic similarity ,where the embedding dimension by BERT for a document is 768,like wise I was able to create indexes for 3.2 million but after that If I try to create indexes I'm getting the below memory error,I passed the embeddings of 100000 each time to the faiss for creating the indexes,after reading the [bad alloc 20million](https://github.com/facebookresearch/faiss/issues/302) , I've changed the batch size to 1000,even still I'm getting the below error.The index file size for 3.2M is close to 10GB ,and there is space available in RAM,and I'm unable to add anymore indexes to the file.
> 
> ```
> start_index=0
> end_index=1000
> 
> from sentence_transformers import SentenceTransformer
> embedder=SentenceTransformer('bert-base-nli-mean-tokens')
> 
> index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
> 
> Traceback (most recent call last):
>   File "create_indexes.py", line 42, in <module>
>     generate_indexes(df_main,'Y','till_2019')
>   File "create_indexes.py", line 30, in generate_indexes
>     index.add_with_ids(np.array(embedder.encode(df_main['Text'][start_index:end_index].values,show_progress_bar=True),dtype='float32'),np.array(df_main['ID'][start_index:end_index].values))
>   File "/home/mahesh/anaconda3/lib/python3.7/site-packages/faiss/__init__.py", line 144, in replacement_add_with_ids
>     self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
>   File "/home/mahesh/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 3877, in add_with_ids
>     return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
> MemoryError: std::bad_alloc
> ```
> 
> Please let me know how to proceed further. Thanks in advance.
> 
> # Platform
> OS:
> 
> Faiss version:
> 
> Faiss compilation options:
> 
> Running on:
> 
> * [x]  CPU
> * [ ]  GPU
> 
> Interface:
> 
> * [ ]  C++
> * [x]  Python
> 
> # Reproduction instructions

Hi, so how do you solve it? I met the same error.
