### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by anliyuan** [facebookresearch/faiss#1411]
Running on:
GPU

Interface: 
Python

When I import faiss in my project I got 'ImportError: dlopen: cannot load any more object with static TLS' 

heres logs:
Traceback (most recent call last):
  File "/home/shuipi/anaconda3/envs/cardTest4/lib/python3.8/site-packages/faiss/__init__.py", line 41, in <module>
    from .swigfaiss_avx2 import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "local_test/local_test1.py", line 15, in <module>
    from local_test.local_test_function.local_test_init import local_generate_feature, test_info_init, load_local_feature
  File "./local_test/local_test_function/local_test_init.py", line 9, in <module>
    from utils.tr_book.book_generate import book_generate_api
  File "./utils/tr_book/book_generate.py", line 10, in <module>
    from utils.model_init.word_model_init import g_wordsClassifier
  File "./utils/model_init/word_model_init.py", line 4, in <module>
    from utils.model.wordsFeaClassifier.wordClassifier import WordsClassifier
  File "./utils/model/wordsFeaClassifier/wordClassifier.py", line 2, in <module>
    import faiss
  File "/home/shuipi/anaconda3/envs/cardTest4/lib/python3.8/site-packages/faiss/__init__.py", line 49, in <module>
    from .swigfaiss import *
  File "/home/shuipi/anaconda3/envs/cardTest4/lib/python3.8/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: dlopen: cannot load any more object with static TLS

please help!!!!!

**Comment by anliyuan** [comment]
I upgraded pytorch to 1.6, everythings fine before that

**Comment by mdouze** [comment]
no activity, closing.

**Comment by Daya-Jin** [comment]
same problem

**Comment by zj19941113** [comment]
same problem
