### ISSUE TITLE
merge_ondisk func missing?

### ISSUE THREAD

**Issue by tangzhy** [facebookresearch/faiss#1472]
I've installed faiss-gpu following the intruction. When I try to use ondisk searching, I found errors as follows:

```
In [5]: from faiss_contrib.ondisk import merge_ondisk
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-04c005cb085f> in <module>
----> 1 from faiss_contrib.ondisk import merge_ondisk

ModuleNotFoundError: No module named 'faiss_contrib'
```

My conda env:
```
In [7]: conda list
# packages in environment at /root/Softwares/anaconda3/envs/faiss:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
backcall                  0.2.0                      py_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2020.10.14                    0    defaults
certifi                   2020.6.20                py37_0    defaults
cudatoolkit               10.0.130                      0    defaults
decorator                 4.4.2                      py_0    defaults
faiss-gpu                 1.6.3            py37h1a5d453_0    pytorch
intel-openmp              2020.2                      254    defaults
ipython                   7.18.1           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.17.2                   py37_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.2.0            py37h23d657b_0    defaults
mkl_random                1.1.1            py37h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.19.1           py37hbc911f0_0    defaults
numpy-base                1.19.1           py37hfa32c7d_0    defaults
openssl                   1.1.1h               h7b6447c_0    defaults
parso                     0.7.0                      py_0    defaults
pexpect                   4.8.0                    py37_1    defaults
pickleshare               0.7.5                 py37_1001    defaults
pip                       20.2.2                   py37_0    defaults
prompt-toolkit            3.0.8                      py_0    defaults
psutil                    5.7.2                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0    defaults
pygments                  2.7.1                      py_0    defaults
python                    3.7.9                h7579374_0    defaults
readline                  8.0                  h7b6447c_0    defaults
setuptools                49.6.0                   py37_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
traitlets                 5.0.4                      py_0    defaults
wcwidth                   0.2.5                      py_0    defaults
wheel                     0.35.1                     py_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

I cannot find merge_ondisk func, any advice?

**Comment by mdouze** [comment]
what about faiss.contrib?

**Comment by mdouze** [comment]
ah ok it's in the demos. Fixing in https://github.com/facebookresearch/faiss/pull/1478

**Comment by XiaogangYin** [comment]
$python demo_ondisk_ivf.py 0
Traceback (most recent call last):
  File "demo_ondisk_ivf.py", line 11, in <module>
    from faiss.contrib.ondisk import merge_ondisk
ModuleNotFoundError: No module named 'faiss.contrib'

My conda env is the same as tangzhy

**Comment by mdouze** [comment]
should be fixed.

**Comment by stoneyang** [comment]
`$python3.6
Python 3.6.6rc1 (default, Jul 30 2018, 15:26:44)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Loading faiss with AVX2 support.
Loading faiss.
>>> faiss.__version__
'1.6.0'
>>> from faiss.contrib import exhaustive_search
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faiss.contrib'
>>>`

**Comment by CarinaXZZ** [comment]
Hi, I have the same problem here. I reinstall the whole package through conda. But it still couldn’t manage to find the module. Can anyone help with this please? Thanks.
