### ISSUE TITLE
Question: test_gpu_index.py failing to run

### ISSUE THREAD

**Issue by igattm** [facebookresearch/faiss#1489]
# Summary

OS: Ubuntu 18.04.5 LTS

Faiss version: 1.6.3

Installed from: anaconda

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
After installing from anaconda with the use of
`conda install faiss-gpu cudatoolkit=10.0 -c pytorch
`
I simply copied test_gpu_index.py file contents to check FAISS installation.
It failes, although test_gpu_index_ivfsq.py seems to be passing.
Here is the error log:

```
user:~$ python3 test_gpu_index.py
EE....WARNING clustering 256 points to 128 centroids: please provide at least 4992 training points
.WARNING clustering 256 points to 128 centroids: please provide at least 4992 training points
WARNING clustering 256 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 256 points to 256 centroids: please provide at least 9984 training points
.......E2323.89013671875 2323.8896484375
.Training quantizer
Training quantizer on 10000 vectors in 256D
using clustering_index of dimension 256 to do the clustering
WARNING clustering 10000 points to 330 centroids: please provide at least 12870 training points
Clustering 10000 points in 256D to 330 clusters, redo 1 times, 10 iterations
Input data encoded in 32 bytes per vector
  Preprocessing in 0.00 s
  Iteration 9 (0.15 s, search 0.10 s): objective=2.35991e+06 imbalance=1.039 nsplit=0
....WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
.WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
.WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
WARNING clustering 5000 points to 256 centroids: please provide at least 9984 training points
..
======================================================================
ERROR: test_cpu_to_gpu_IVFFlat (__main__.EvalIVFPQAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gpu_index.py", line 118, in test_cpu_to_gpu_IVFFlat
    self.do_cpu_to_gpu('IVF128,Flat')
  File "test_gpu_index.py", line 77, in do_cpu_to_gpu
    mem_info = res.getMemoryInfo()
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 958, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, StandardGpuResources, name)
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'StandardGpuResources' object has no attribute 'getMemoryInfo'

======================================================================
ERROR: test_cpu_to_gpu_IVFPQ (__main__.EvalIVFPQAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gpu_index.py", line 115, in test_cpu_to_gpu_IVFPQ
    self.do_cpu_to_gpu('IVF128,PQ4')
  File "test_gpu_index.py", line 77, in do_cpu_to_gpu
    mem_info = res.getMemoryInfo()
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 958, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, StandardGpuResources, name)
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'StandardGpuResources' object has no attribute 'getMemoryInfo'

======================================================================
ERROR: test_bf_input_types (__main__.TestBruteForceDistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gpu_index.py", line 526, in test_bf_input_types
    params.outIndices = faiss.swig_ptr(out_i32)
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 7074, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, GpuDistanceParams, name, value)
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/user/.conda/envs/testEnv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 60, in _swig_setattr_nondynamic
    return method(self, value)
TypeError: in method 'GpuDistanceParams_outIndices_set', argument 2 of type 'faiss::Index::idx_t *'

----------------------------------------------------------------------
Ran 24 tests in 9.885s

FAILED (errors=3)


```

**Comment by mdouze** [comment]
Can't repro. Closing.
