### ISSUE TITLE
Error: 'device_ < getNumDevices()' failed: Invalid GPU device 1

### ISSUE THREAD

**Issue by ucasiggcas** [facebookresearch/faiss#1491]
hi,dear
I have tried the one GPU faiss
```
    res = faiss.StandardGpuResources()
    index_flat =faiss.IndexFlatIP(conf.embed_size)
    gpu_id=1
    print(gpu_id)
    GpuIndex = faiss.index_cpu_to_gpu(res,gpu_id, index_flat)
    GpuIndex.add(ItemEmb)
```
but tell me the error
```
Traceback (most recent call last):
  File "video_update_rec_items.py", line 150, in <module>
    GpuIndex = faiss.index_cpu_to_gpu(res,gpu_id, index_flat)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/faiss/__init__.py", line 448, in replacement_function
    result = original_function(*args)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/faiss/swigfaiss.py", line 5053, in index_cpu_to_gpu
    return _swigfaiss.index_cpu_to_gpu(resources, device, index, options)
RuntimeError: Error in faiss::gpu::GpuIndex::GpuIndex(faiss::gpu::GpuResources*, int, faiss::MetricType, float, faiss::gpu::GpuIndexConfig) at gpu/GpuIndex.cu:49: Error: 'device_ < getNumDevices()' failed: Invalid GPU device 1
```
so what's wrong ?
thx

**Comment by wickedfoo** [comment]
GPU 1 is the second GPU in the system. You probably want `gpu_id=0`.
