### ISSUE TITLE
install faiss==v1.4.0: No module named 'faiss.swigfaiss_gpu'

### ISSUE THREAD

**Issue by youngjt** [facebookresearch/faiss#1544]
======================================================================
ERROR: test_binary_factory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_binary_factory
Traceback (most recent call last):
  File "/dfs/1/xxxx/software/faiss-1.4.0/python/build/lib/faiss/__init__.py", line 21, in <module>
    from .swigfaiss_gpu import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dfs/1/xxxx/software/faiss-1.4.0/python/build/lib/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/python3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /dfs/1/xxxx/software/faiss-1.4.0/python/build/lib/faiss/_swigfaiss.so: undefined symbol: PyCObject_Type

**Comment by youngjt** [comment]
**when I try to install faiss==1.3.0，the same error occurs again！**

======================================================================
ERROR: test_binary_factory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_binary_factory
Traceback (most recent call last):
  File "/dfs/1/yangjiangtao/software/faiss-1.3.0/python/build/lib/faiss/__init__.py", line 21, in <module>
    from .swigfaiss_gpu import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dfs/1/yangjiangtao/software/faiss-1.3.0/python/build/lib/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/python3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /dfs/1/yangjiangtao/software/faiss-1.3.0/python/build/lib/faiss/_swigfaiss.so: undefined symbol: PyCObject_Type

**Comment by beauby** [comment]
Not enough information to repro. Please reopen once you have filled the issue template.
