### ISSUE TITLE
cannot import faiss v.1.6.3 as NameError: name 'range_search_with_parameters' is not defined

### ISSUE THREAD

**Issue by cmacdonald** [facebookresearch/faiss#1545]
# Summary

# Platform

OS: Linux, Centos 7

Faiss version: 

Installed from: `pip install faiss-cpu` TODAY 

Faiss compilation options: unknown

```
>>> faiss.__version__
'1.6.3'
```

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ X] Python

# Reproduction instructions

I cannot import faiss, due to range_search_with_parameters not being defined at that point.

```
python
>>> import faiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/tr.craigm/anaconda3/envs/pyterrier/lib/python3.6/site-packages/faiss/__init__.py", line 829, in <module>
    range_search_with_parameters_c = range_search_with_parameters
NameError: name 'range_search_with_parameters' is not defined
>>> 
```

Moving the definition of range_search_with_parameters_c after range_search_with_parameters fixes the issue.

**Comment by mdouze** [comment]
pip is not a supported way of installing Faiss
Are you sure this is not mixing up several Faiss installs?

**Comment by cmacdonald** [comment]
INSTALL.md says - "The easiest way to install FAISS is from Anaconda". Perhaps that could explicitly exclude pip then? Given that it does install, one might expect it to work.
