### ISSUE TITLE
How can I close the warnings about clustering points?

### ISSUE THREAD

**Issue by KaiChen1998** [facebookresearch/faiss#1637]
# Summary

# Platform

OS:  Linux

Faiss version: 

Installed from:  anaconda

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Hi! Can I shut down the warnings about data points during clustering, for example
```
WARNING clustering 49 points to 3 centroids: please provide at least 117 training points
```
Thank you!

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids

**Comment by Dr-Left** [comment]
My code is like:

```
>>>import faiss

>>>index = faiss.index_factory(128, "OPQ32,IVF16,PQ32x4")
>>> index.pq                                                                                                            
Traceback (most recent call last):                                                                                        
File "<stdin>", line 1, in <module>                                                                                   
AttributeError: 'IndexPreTransform' object has no attribute 'pq'                                                        
>>> index.cp                                                                                                            
Traceback (most recent call last):                                                                                       
File "<stdin>", line 1, in <module>                                                                                  
AttributeError: 'IndexPreTransform' object has no attribute 'cp'           
```

How can I adjust the `min_points_per_centroid` when using `index_factory`?
