### ISSUE TITLE
import _swigfaiss failed(can't find dll) using Ipython on Windows.

### ISSUE THREAD

**Issue by AlexWang1900** [facebookresearch/faiss#1701]
# Summary

# Platform

OS:  WINDOW 10

Faiss version: newest on conda pytorch channel

Installed from: conda install -c pytorch faiss-cpu

Running on:
- [ ] CPU

Interface: 

- [ ] Python

# Reproduction instructions
**1) faiss can run from python on conda terminal :**
```
(base) C:\Users\Alex>python
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
>>> faiss.get_num_gpus()
0
>>>
```
**2) failed on SPYDER 4.0.0 's  Ipython  interface** 

```
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.10.2 -- An enhanced Interactive Python.

import  os
print( os.getcwd())
C:\Users\Alex

import faiss
Traceback (most recent call last):

  File "<ipython-input-2-9e6a9f0b5bbf>", line 1, in <module>
    import faiss

  File "C:\Users\Alex\Anaconda3\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *

  File "C:\Users\Alex\Anaconda3\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *

  File "C:\Users\Alex\Anaconda3\lib\site-packages\faiss\swigfaiss.py", line 16, in <module>
    from . import _swigfaiss

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by AlexWang1900** [comment]
OK! I UPDATED spyder to 4.2.1 ,and anaconda to 1.10.0, the problem is gone now!
PLEASE Close this issue!

**Comment by AlexWang1900** [comment]
OK! I UPDATED spyder to 4.2.1 ,and anaconda to 1.10.0, the problem is gone now!
PLEASE Close this issue!

**Comment by JWenBin** [comment]
the same error with you(conda-4.9.2):
(TF2) C:\Users\lenovo>python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "D:\Anaconda3\envs\TF2\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "D:\Anaconda3\envs\TF2\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\TF2\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "D:\Anaconda3\envs\TF2\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "D:\Anaconda3\envs\TF2\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed: 找不到指定的模块。
>>>

**Comment by JWenBin** [comment]
pycharm also need to update from 2018.3 to 2020.3

**Comment by deepML2020** [comment]
Installing faiss with the following command solves the problem ' ImportError: DLL load failed while importing _swigfaiss: '(Remember to remove the installed faiss)：

# CPU-only version
$ conda install -c pytorch faiss-cpu=1.7.4 mkl=2021 blas=1.0=mkl

# GPU(+CPU) version
$ conda install -c pytorch -c nvidia faiss-gpu=1.7.4 mkl=2021 blas=1.0=mkl
