### ISSUE TITLE
Sometimes the value of index is Wrong.

### ISSUE THREAD

**Issue by yushi-okunishi** [facebookresearch/faiss#1731]
# Summary

Sometimes the searched values are wrong.
I encountered the following error.
`IndexError: index 4458766603700305201 is out of bounds for dimension 0 with size 264`
What's weird is that sometimes it works fine, and sometimes it doesn't.

# Platform

OS: Linux

Faiss version: f2f014de50b45847896d5e5fc377b269199bcad3

Installed from: conda-forge

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I'm using faiss along with pytorch.
I'm trying to reproduce [this paper](https://arxiv.org/abs/2005.02357).

I am searching for k neighbors in the training data during the test. 
like this
```
index.add(train_out)

for (x, y) in test_dataloader:
    with torch.no_grad():
        out = model(x)
    D, I = index.seach(out.reshape, k)

    # then I'm calculating the distance between test_out and k nearest train_out, using I.
```
All these series of calculations are done using the GPU.

And occasionally the contents of the index will look like the following, pointing to a non-existent index, resulting in an error.
```
tensor([[-4719509717503517538],
        [-4738497828050120303],
        [-4737060276727801277],
        [-4744230956554366742],
        [-4775401445494324176],
        [ 4433057829264909020],
        [-4738622334857089504],
        [-4750872702573880633], ... ], device='cuda:0')
```
However, D computed by `index.search()` seems normal.

Is it possible that torch is breaking the pointer of FAISS?

**Comment by wickedfoo** [comment]
Would be hard to investigate without seeing the rest of your script.

Are you using different CUDA streams or multiple devices somewhere? Is train_out, out, etc. on the CPU or GPU?

**Comment by wickedfoo** [comment]
and what kind of index are you using?

**Comment by yushi-okunishi** [comment]
@wickedfoo thank you for replying.

I could reproduce the error.
if run code below, Whenever you enter the second loop of (for class_name in mvtec.CLASS_NAMES), you will see the following error below the code. and `core` file will be created in the execution path.
I changed `mvtec.CLASS_NAMES` to `mvtec.CLASS_NAMES[1:]`, but I still always get an error on the second loop.

Do I need to free memory of any variables for the second Index of FAISS initialization?

```
import argparse
import numpy as np
import os
import pickle
from tqdm import tqdm

import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import timm
import faiss
import faiss.contrib.torch_utils

import datasets.mvtec as mvtec

def parse_args():
    parser = argparse.ArgumentParser('SPADE')
    parser.add_argument("--top_k", type=int, default=5)
    parser.add_argument("--save_path", type=str, default="./result")
    return parser.parse_args()


def main():
    k = 5 # kNN
    image_size = 224
    patch_size = 16
    nd = 768
    gpu_id = 1
    test_batch_size = 32

    args = parse_args()

    # device setup
    device = 'cuda:{}'.format(gpu_id) if torch.cuda.is_available() else 'cpu'

    # set model's intermediate outputs
    #outputs = []
    def hook(module, input, output):
        global descriptor
        descriptor = output[:, 1:]
        #outputs.append(output)

    # timm model
    model = timm.create_model("vit_base_patch16_224", pretrained=True)
    model.to(device)
    model.eval()
    model.blocks[6].register_forward_hook(hook)

    os.makedirs(os.path.join(args.save_path, 'temp'), exist_ok=True)

    for class_name in mvtec.CLASS_NAMES:

        train_dataset = mvtec.MVTecDataset(class_name=class_name, is_train=True)
        train_dataloader = DataLoader(train_dataset, batch_size=32, pin_memory=True)
        test_dataset = mvtec.MVTecDataset(class_name=class_name, is_train=False)
        test_dataloader = DataLoader(test_dataset, batch_size=test_batch_size, pin_memory=True)
        
        train_outputs = []

        # extract train set features
        train_feature_filepath = os.path.join(args.save_path, 'temp', 'train_%s.pkl' % class_name)
        if not os.path.exists(train_feature_filepath):
            for (x, y, mask) in tqdm(train_dataloader, '| feature extraction | train | %s |' % class_name):
                # model prediction
                with torch.no_grad():
                    _ = model(x.to(device))
                train_outputs.append(descriptor)
            train_outputs = torch.cat(train_outputs, 0)
            # save extracted feature
            with open(train_feature_filepath, 'wb') as f:
                pickle.dump(train_outputs, f)
        else:
            print('load train set feature from: %s' % train_feature_filepath)
            with open(train_feature_filepath, 'rb') as f:
                train_outputs = pickle.load(f)
        # train_outputs = N_train * 196 * 768

        ## make faiss index
        res = faiss.StandardGpuResources()
        flat_config = faiss.GpuIndexFlatConfig()
        flat_config.device = gpu_id
        flat_index = faiss.GpuIndexFlatL2(res, nd*14**2, flat_config)
        train_shape = train_outputs.shape
        print("train output shape {}".format(train_shape))
        flat_index.add(train_outputs.clone().reshape(train_shape[0], -1).contiguous())

        ## measuring time
        print("measuring localization time")
        pairwise_d = nn.PairwiseDistance(eps=0)

        for (x, y, mask) in tqdm(test_dataloader, '| anomaly detection | test | %s |' % class_name):
            score_maps = torch.zeros((test_batch_size, 14, 14))
            with torch.no_grad():
                _ = model(x.to(device))
            torch.cuda.synchronize()
            # search kNN , image wise
            desc_shape = descriptor.shape
            D, I = flat_index.search(descriptor.reshape(desc_shape[0], -1).contiguous(), k)
            torch.cuda.synchronize()

            for i in range(I.shape[0]):
                kn = train_outputs[[I[i]]]# k nearest tensor
                anom_maps = pairwise_d(descriptor[i:i+1].repeat(k, 1, 1).reshape(k*14**2, -1), kn.reshape(k*14**2, -1)).reshape(k, 14, 14)
                score_map = torch.min(anom_maps, dim=0)[0]
                score_maps[i] = score_map.detach().cpu()
            torch.cuda.synchronize()

        torch.cuda.synchronize()

if __name__ == '__main__':
    main()
```

```
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [37,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [38,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [40,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [41,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [42,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [45,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [46,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [48,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [49,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [50,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [56,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [16,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
| anomaly detection | test | cable |:   0%|                                                                                                                                                     | 0/5 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "for_issue.py", line 143, in <module>
    main()
  File "for_issue.py", line 126, in main
    score_maps[i] = score_map.detach().cpu()
RuntimeError: CUDA error: device-side assert triggered
Faiss assertion 'err == cudaSuccess' failed in virtual void faiss::gpu::StandardGpuResourcesImpl::deallocMemory(int, void*) at /home/conda/feedstock_root/build_artifacts/faiss-split_1612472396838/work/faiss/gpu/StandardGpuResources.cpp:494; details: Failed to cudaFree pointer 0x7f7f4964e400 (error 710 device-side assert triggered)
Aborted (core dumped)
```

**Comment by yushi-okunishi** [comment]
When I increased `k` from 5 to 50, I encountered the error in the first loop.
Is it something to do with how much I put on the GPU at once?

**Comment by yushi-okunishi** [comment]
It turns out that multiple initializations of index are not the problem.

**Comment by wickedfoo** [comment]
Is your `k` larger than the number of vectors in the index? All Faiss index classes report `-1` as the user index when there are no results to report, and could you be interpreting this `-1` as a valid index?

e.g., if you had an IndexFlat with 20 vectors and you asked for k=50, it would be expected that the first 20 indices reported are valid and the remainder 30 are -1.

**Comment by lindsey98** [comment]
Hi is there any solution for this issue, I encounter the same issue when running index.search() multiple times in a loop. And I can only resolve it by moving the index to CPU + deleting and rebuilding the index in every loop.
I don't think it is because "k larger than the number of vectors in the index" because we get a really large value like "4458766603700305201" instead of -1.

**Comment by mrFocusXin** [comment]
> Hi is there any solution for this issue, I encounter the same issue when running index.search() multiple times in a loop. And I can only resolve it by moving the index to CPU + deleting and rebuilding the index in every loop. I don't think it is because "k larger than the number of vectors in the index" because we get a really large value like "4458766603700305201" instead of -1.

Hi is there any solution for this issue? How do you resolve data by moving the index to CPU + deleting and rebuilding the index in every loop?
