### ISSUE TITLE
undefined reference to fvec_inner_products_ny() at runtime [Jetson]

### ISSUE THREAD

**Issue by fjodborg** [facebookresearch/faiss#1782]
# Summary
In short i tried to compile faiss on my Jetson xavier nx for speeding up correspondence matching. I run the setup that works on my desktop and i get no errors or warning, but when i try to run `python3.7 -c "import faiss"` from the `build/faiss/python` folder i get the following error on the jetson:
```
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/f/repos/faiss/build/faiss/libfaiss.so: undefined symbol: _ZN5faiss22fvec_inner_products_nyEPfPKfS2_mm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/f/repos/faiss/build/faiss/python/faiss/loader.py", line 34, in <module>
    from .swigfaiss import *
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/f/repos/faiss/build/faiss/libfaiss.so: undefined symbol: _ZN5faiss22fvec_inner_products_nyEPfPKfS2_mm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/f/repos/faiss/build/faiss/libfaiss.so: undefined symbol: _ZN5faiss22fvec_inner_products_nyEPfPKfS2_mm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/f/repos/faiss/build/faiss/python/faiss/__init__.py", line 17, in <module>
    from .loader import *
  File "/home/f/repos/faiss/build/faiss/python/faiss/loader.py", line 39, in <module>
    from .swigfaiss import *
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/f/repos/faiss/build/faiss/python/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/f/repos/faiss/build/faiss/libfaiss.so: undefined symbol: _ZN5faiss22fvec_inner_products_nyEPfPKfS2_mm
```
I've narrowed it down to `libfaiss.so` in `build/faiss` and if i run `ld libfaiss.so` i get:
```
ld: warning: cannot find entry symbol _start; not setting start address
libfaiss.so: undefined reference to `faiss::fvec_inner_products_ny(float*, float const*, float const*, unsigned long, unsigned long)'
```
When i run `ld libfaiss.so` on my desktop it doesn't have the undefined reference:
```
ld: warning: cannot find entry symbol _start; not setting start address
```

# Platform  Jetson xavier nx

## OS: 
18.04.1-Ubuntu (arm)

## Faiss version: 
 V.1.6.5 with commit 5efe1a97323a3e327b9058d57a54d4469ef6baad (v1.7.0 doesn't work on my desktop when compiling with gpu and on the jetson i still get the same error on newer branches/tags)

## Installed from: 
 compiled from source

## Faiss compilation options: 
flags:
```
cmake -B build . -DFAISS_ENABLE_GPU=OFF \
                -DFAISS_ENABLE_PYTHON=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DPython_EXECUTABLE=/usr/bin/python3.7 \
                -DFAISS_OPT_LEVEL=generic \
                -DBUILD_SHARED_LIBS=ON \
```
The follow versions were found by cmake:
```
-- The CXX compiler identification is GNU 7.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12") found components: python 
-- Found Python: /usr/include/python3.7m (found version "3.7.5") found components: Development NumPy Interpreter 
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
```

## Running on:
- [x] CPU
- [ ] GPU

## Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
These are the install steps i'm using
```
cd $HOME/repos
git clone https://github.com/facebookresearch/faiss
cd faiss/faiss
git checkout tags/v1.6.5 
wget https://github.com/facebookresearch/faiss/pull/1245/commits/5efe1a97323a3e327b9058d57a54d4469ef6baad.diff --output-document=gpu_fix.patch
patch -p1 < gpu_fix.patch --force
cd $HOME/repos/faiss
mkdir build

cmake -B build . -DFAISS_ENABLE_GPU=OFF \
                -DFAISS_ENABLE_PYTHON=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DPython_EXECUTABLE=/usr/bin/python3.7 \
                -DFAISS_OPT_LEVEL=generic \
                -DBUILD_SHARED_LIBS=ON \

make -C build -j6 swigfaiss
cd build/faiss/python
sudo python3.7 setup.py build
```

**Comment by wx257osn2** [comment]
@FjodBorg @hsz1273327 Would you try v1.7.1 or later? It seems that this problem had been fixed on #1655.
