### ISSUE TITLE
CPU: OpenMPI + Faiss + MKL work unproperly

### ISSUE THREAD

**Issue by ruanafan** [facebookresearch/faiss#1798]
# Summary

If I link faiss with openBLAS and LAPACK, it works as what I expected:
* each machine has 1 MPI process
* each process can automatically use all cores of that machine

But when I try to link faiss with MKL，threads of the MPI process are stuck, only one thread is doing the computation work. 

# Platform

OS: Ubuntu 18.04

Faiss version: faiss-1.7.0

Installed from: compiled by myseld

Faiss compilation options: cmake -B build . -DFAISS_ENABLE_GPU=OFF -DCMAKE_INSTALL_PREFIX=/home/disk/fassis -DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=/home/disk/intel_oneapi/mkl/2021.2.0/lib/intel64 -DFAISS_ENABLE_PYTHON=OFF -DBUILD_TESTING=OFF

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

libraries I link:
```
-lfaiss -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_gnu_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_blacs_openmpi_lp64.a -Wl,--end-group -lgomp -lpthread -lm -ldl
```

compile options:
```
-m64 -fopenmp
```

I get this configuration from https://software.intel.com/sites/products/mkl/mkl_link_line_advisor.htm

gdb stack of a process:
```
hread 18 (Thread 0x7f49a506d700 (LWP 13792)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a506d700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 17 (Thread 0x7f49a586e700 (LWP 13791)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a586e700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 16 (Thread 0x7f49a606f700 (LWP 13790)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a606f700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 15 (Thread 0x7f49a6870700 (LWP 13789)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a6870700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7f49a7071700 (LWP 13788)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a7071700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7f49a7872700 (LWP 13787)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a7872700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7f49a8073700 (LWP 13786)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
---Type <return> to continue, or q <return> to quit---
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a8073700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7f49a8874700 (LWP 13785)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a8874700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f49a9075700 (LWP 13784)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a9075700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7f49a9876700 (LWP 13783)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49a9876700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f49aa077700 (LWP 13782)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49aa077700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f49aa878700 (LWP 13781)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49aa878700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f49ab079700 (LWP 13780)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49ab079700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f49ab87a700 (LWP 13779)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f49ab87a700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f4aebbe5700 (LWP 13778)):
#0  0x00007f4afe24ef4e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f4afe24c948 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f4afe01e6db in start_thread (arg=0x7f4aebbe5700) at pthread_create.c:463
#3  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f4afaed2700 (LWP 13776)):
#0  0x00007f4afd1f7cb9 in __GI___poll (fds=0x7f4aec000b20, nfds=2, timeout=3599991) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4afcc17403 in ?? () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.20
#2  0x00007f4afcc0e60b in opal_libevent2022_event_base_loop () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.20
#3  0x00007f4afcbd417e in ?? () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.20
#4  0x00007f4afe01e6db in start_thread (arg=0x7f4afaed2700) at pthread_create.c:463
#5  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f4afb6d3700 (LWP 13775)):
#0  0x00007f4afd204a47 in epoll_wait (epfd=7, events=0x563f3b969770, maxevents=32, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007f4afcc0a56b in ?? () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.20
#2  0x00007f4afcc0e60b in opal_libevent2022_event_base_loop () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.20
#3  0x00007f4afb702fcd in ?? () from /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi/mca_pmix_pmix112.so
#4  0x00007f4afe01e6db in start_thread (arg=0x7f4afb6d3700) at pthread_create.c:463
#5  0x00007f4afd20471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f4afeb89040 (LWP 13774)):
#0  0x0000563f38a329ae in void faiss::(anonymous namespace)::exhaustive_L2sqr_blas<faiss::HeapResultHandler<faiss::CMax<float, long> > >(float const*, float const*, unsigned long, unsigned long, unsigned long, faiss::HeapResultHandler<faiss::CMax<float, long> >&, float const*) ()
#1  0x0000563f38a311f4 in faiss::knn_L2sqr(float const*, float const*, unsigned long, unsigned long, unsigned long, faiss::HeapArray<faiss::CMax<float, long> >*, float const*) ()
#2  0x0000563f38a2d59c in faiss::IndexFlat::search(long, float const*, long, float*, long*) const ()
```

If I switch to intel-thread + iomp5, the same result is received, and the stack shows the thread is stuck at pthread_cond_wait

**Comment by ruanafan** [comment]
MKL_NUM_THREADS has to be set in this case, otherwise it would not be dynamically parallel
