### ISSUE TITLE
Windows delete by IDs

### ISSUE THREAD

**Issue by hadhoryth** [facebookresearch/faiss#1853]
# Platform
OS:
- [x] Windows 10 (Error)
- [x] OSX 10.15.7 (Working)

Faiss version: 1.7.0

Installed from: Anaconda

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I have problems with `delete_ids` on Windows.
```python
xb = np.random.randn(10, 256)
xb = xb.astype(np.float32)
index = faiss.IndexFlatL2(xb.shape[1])
index.remove_ids(np.array([0]))
-------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\faiss\__init__.py", line 381, in replacement_remove_ids
    sel = IDSelectorBatch(x.size, swig_ptr(x))
  File "C:\ProgramData\Anaconda3\lib\site-packages\faiss\swigfaiss.py", line 4843, in __init__
    _swigfaiss.IDSelectorBatch_swiginit(self, _swigfaiss.new_IDSelectorBatch(n, indices))
TypeError: in method 'new_IDSelectorBatch', argument 2 of type 'faiss::IDSelector::idx_t const *'
```

Also, I've tried to use `IndexIDMap`
```python
index = faiss.IndexFlatL2(xb.shape[1])
index2 = faiss.IndexIDMap(index)
index2.add_with_ids(xb, ids)
--------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\faiss\__init__.py", line 212, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "C:\ProgramData\Anaconda3\lib\site-packages\faiss\swigfaiss.py", line 4661, in add_with_ids
    return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
TypeError: in method 'IndexIDMap_add_with_ids', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t const *'
```

But have the same code samples working on OSX. How can I properly delete items from `IndexFlatL2`?

**Comment by hadhoryth** [comment]
Yes, you are right. Everything working. Thank you.
