### ISSUE TITLE
AttributeError: module 'faiss' has no attribute 'OnDiskInvertedLists'

### ISSUE THREAD

**Issue by sinievanderben** [facebookresearch/faiss#1872]
# Summary

Hi there!

I tried to run the following demo: https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py
It works fine, except for merging the indices.

# Platform

Windows 10

Faiss version: cpu 1.7.0

Installed from: conda

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction 

I have 9 separate blocks of indices generated with the demo and a trained index. 

I changed one line of code in merge_ondisk.py, because I got an error previously with that. Might be due to Windows? (thought I read that in another issue). 
--> index = faiss.read_index(fname) #, faiss.IO_FLAG_MMAP)

However, when I try to merge the indices, I get the following error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\sinie\anaconda3\envs\provee2\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\sinie\anaconda3\envs\provee2\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "E:\PROVEE\provee-local-projector\LocalProjector\src\KNN\faissKNN.py", line 130, in trainKNN
    self.mergeIndices(indxdir, tmpdir)
  File "E:\PROVEE\provee-local-projector\LocalProjector\src\KNN\faissKNN.py", line 191, in mergeIndices
    merge_ondisk(index, block_fnames, tmpdir + "\\" +  "merged_index.ivfdata")
  File "E:\PROVEE\provee-local-projector\LocalProjector\src\KNN\merge_ondisk.py", line 35, in merge_ondisk
    invlists = faiss.OnDiskInvertedLists(
AttributeError: module 'faiss' has no attribute 'OnDiskInvertedLists'

**Comment by mdouze** [comment]
OnDiskInvertedList is not implemented for windows due to the lack of a proper memory map system call.

**Comment by sinievanderben** [comment]
Clear, thank you
