### ISSUE TITLE
_swigfaiss.so: undefined symbol: sorgqr_ when importing faiss

### ISSUE THREAD

**Issue by JeromeNi** [facebookresearch/faiss#1912]
# Summary

I tried to build faiss from source as the system architecture is ppc64le. I followed the instructions in INSTALL.md but upon importing faiss in Python I encountered the following issue:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/users/junruin2/faiss/build/faiss/python/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/nobackup/users/junruin2/faiss/build/faiss/python/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/nobackup/users/junruin2/faiss/build/faiss/python/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: /nobackup/users/junruin2/faiss/build/faiss/python/faiss/_swigfaiss.so: undefined symbol: sorgqr_`

Thanks for any help!

# Platform

Architecture: ppc64le

OS: Linux-4.14.0-115.10.1.el7a.ppc64le-ppc64le-with-redhat-7.6-Maipo

Faiss version: 1.7.0; commit 8eab15eca38201403ebd860cf9bd9849068494a1

Installed from: source

Faiss compilation options: `cmake -B build -DFAISS_OPT_LEVEL=generic .`

Python Version: 3.7.9
CUDA Version: 10.2
SWIG: 4.0.0

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
I first need to add `set (CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler -mno-float128")`
to CMakeLists.txt; otherwise, it will throw `error: identifier "__ieee128" is undefined`

I then followed the instructions in INSTALL.md as 

`cmake -B build -DFAISS_OPT_LEVEL=generic .`

`make -C build -j faiss`

`make -C build -j swigfaiss`

`(cd build/faiss/python && python setup.py install)`

I also added `faiss/build/faiss/python` to `PYTHONPATH` variable as it would otherwise throw
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/users/junruin2/anaconda3/envs/espnet-pt1.7.1/lib/python3.7/site-packages/faiss-1.7.0-py3.7.egg/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/nobackup/users/junruin2/anaconda3/envs/espnet-pt1.7.1/lib/python3.7/site-packages/faiss-1.7.0-py3.7.egg/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/nobackup/users/junruin2/anaconda3/envs/espnet-pt1.7.1/lib/python3.7/site-packages/faiss-1.7.0-py3.7.egg/faiss/swigfaiss.py", line 13, in <module>
ImportError: cannot import name '_swigfaiss' from 'faiss' (/nobackup/users/junruin2/anaconda3/envs/espnet-pt1.7.1/lib/python3.7/site-packages/faiss-1.7.0-py3.7.egg/faiss/__init__.py)`

# Additional Output
Output log from the terminal during installation:

https://gist.github.com/JeromeNi/0b46bf0723a5cabce3dc6a622dba657b

**Comment by JeromeNi** [comment]
Fixed this by adding -DCMAKE_CUDA_ARCHITECTURES="70" (the compute capability of the GPU on the server) for cmake. The package can now be imported without issues. Closing this for now.
