### ISSUE TITLE
run_index_server can't support gpu_index?

### ISSUE THREAD

**Issue by Crazycosin** [facebookresearch/faiss#1959]
# Summary

# Platform

OS: CentOS Linux release 7.4.1708 (Core) 

Faiss version: 1.7.1

Installed from: anaconda>

Faiss compilation options: MKL 

Running on:
- [ ] GPU

Interface: 
- [ ] Python

# Reproduction instructions

i wanna to use run_index_server create a remote server
## test_rpc.py, fllow:
```python
import numpy as np
from faiss.contrib.client_server import run_index_server

d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                     # make faiss available

res = faiss.StandardGpuResources() 
## Using an IVF index

nlist = 100
quantizer = faiss.IndexFlatL2(d)  # the other index
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
# here we specify METRIC_L2, by default it performs inner-product search

# make it an IVF GPU index
gpu_index_ivf = faiss.index_cpu_to_gpu(res, 0, index_ivf)

assert not gpu_index_ivf.is_trained
gpu_index_ivf.train(xb)        # add vectors to the index
assert gpu_index_ivf.is_trained

gpu_index_ivf.add(xb)

run_index_server(gpu_index_ivf, 12010, v6=False)
````
## test_client.py, fllow:
```python
from faiss.contrib.client_server import ClientIndex
client = ClientIndex([('localhost', 12010)])
```
first, start test_rpc.py, open other terminal, start  test_cilent.py, then error log show on the terminal, fllow:
```txt
Traceback (most recent call last):
  File "test_faiss.py", line 54, in <module>
    run_index_server(gpu_index_ivf, 12010, v6=False)
  File "/anaconda3/envs/flask_faiss/lib/python3.6/site-packages/faiss/contrib/client_server.py", line 41, in run_index_server
    port, v6=v6)
  File "/anaconda3/envs/flask_faiss/lib/python3.6/site-packages/faiss/contrib/rpc.py", line 247, in run_server
    ibs = new_handler(conn)
  File "/anaconda3/envs/flask_faiss/lib/python3.6/site-packages/faiss/contrib/client_server.py", line 40, in <lambda>
    lambda s: SearchServer(s, index),
  File "/anaconda3/envs/flask_faiss/lib/python3.6/site-packages/faiss/contrib/client_server.py", line 23, in __init__
    self.index_ivf = faiss.extract_index_ivf(index)
  File /anaconda3/envs/flask_faiss/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 3464, in extract_index_ivf
    return _swigfaiss_avx2.extract_index_ivf(*args)
RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at /root/miniconda3/conda-bld/faiss-pkg_1623024462375/work/faiss/IVFlib.cpp:79: Error: 'ivf' failed
```

i search this error  via google, but get nothing useful.

**Comment by mdouze** [comment]
Right, that is because the search_server expects an IndexIVF. you could just remove this line: https://github.com/facebookresearch/faiss/blob/master/contrib/client_server.py#L23

**Comment by Crazycosin** [comment]
> Right, that is because the search_server expects an IndexIVF. you could just remove this line: https://github.com/facebookresearch/faiss/blob/master/contrib/client_server.py#L23

Follow your suggestion, GPU_Index run_server run successfully! Thanks!
