### ISSUE TITLE
An error occurred while importing faiss

### ISSUE THREAD

**Issue by JQZhai** [facebookresearch/faiss#1979]
# Summary

I get an error when I try to import faiss in python3

# Platform

jetson xavier NX

OS: 

Faiss version: 1.7.1

Installed from:  compiled by myself 

Faiss compilation options: 

cmake -B build . -DFAISS_ENABLE_GPU=OFF
make -C build -j faiss
make -C build -j swigfaiss
(cd build/faiss/python && sudo python3 setup.py install)

Running on:
- [ ] CPU

Interface: 

- [ ] Python

# Reproduction instructions

Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "/home/mec/Downloads/faiss/build/faiss/python/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/mec/Downloads/faiss/build/faiss/python/faiss/_swigfaiss.so: undefined symbol: _Z9vsubq_u1612__Uint16x8_tS_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mec/Downloads/faiss/build/faiss/python/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/home/mec/Downloads/faiss/build/faiss/python/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/home/mec/Downloads/faiss/build/faiss/python/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/mec/Downloads/faiss/build/faiss/python/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mec/Downloads/faiss/build/faiss/python/_swigfaiss.so: undefined symbol: _Z9vsubq_u1612__Uint16x8_tS_
>>>

**Comment by derneuere** [comment]
@JQZhai I have the same error. Did you find a workaround, or do older versions work?

**Comment by vorj** [comment]
@JQZhai https://github.com/facebookresearch/faiss/issues/1916#issuecomment-850768877

**Comment by derneuere** [comment]
This argument did not solve my error. This was my dockerfile: https://github.com/LibrePhotos/librephotos-docker/blob/038972324dcd6f225adbfc4377aa4a6b85aecab5/backend/dependencies/Dockerfile

This is the job that failed: https://github.com/LibrePhotos/librephotos-docker/runs/3414502894?check_suite_focus=true

I don't even get an error, the job just stops.
