### ISSUE TITLE
"demo_ondisk_ivf" with index_factory "PCA64，IVF8192,SQ4", Error: 'ivf' failed"

### ISSUE THREAD

**Issue by jwpqjty** [facebookresearch/faiss#1994]
**Run “python demo_ondisk_ivf.py 5” ,get the error below:**

Traceback (most recent call last):
  File "/mnt/fpsl03/Downloads/pycharm-community-2020.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/mnt/fpsl03/Downloads/pycharm-community-2020.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fpsl03/CBIR/faiss-master/jwpModify/demo_ondisk_ivf_jwp.py", line 91, in <module>
    merge_ondisk(index, block_fnames, tmpdir +  SET_STRING+"merged_index.ivfdata")
  File "/home/fpsl03/anaconda3/lib/python3.7/site-packages/faiss-1.7.1-py3.7.egg/faiss/contrib/ondisk.py", line 26, in merge_ondisk
  File "/home/fpsl03/anaconda3/lib/python3.7/site-packages/faiss-1.7.1-py3.7.egg/faiss/swigfaiss.py", line 3465, in extract_index_ivf
RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at /mnt/fpsl03/CBIR/faiss-master/faiss/IVFlib.cpp:82: Error: 'ivf' failed"

**The code is bellow:**
tmpdir = './index_files/'
SIFT_PATH = "../../sift100M_com/"
SET_STRING = "PCA64，IVF8192,SQ4"
if stage == 0:
    # train the index
    xt = fvecs_read(SIFT_PATH+"bigann_learn_10M.bvecs")
    index = faiss.index_factory(xt.shape[1], SET_STRING)
    index = faiss.IndexIDMap(index)         ##################### enable add with idx
    print("training index")
    index.train(xt)
    print("write " + tmpdir + "trained.index")
    faiss.write_index(index, tmpdir + SET_STRING+"_trained.index")
if 1 <= stage <= 4:
    # add 1/4 of the database to 4 independent indexes
    bno = stage - 1
    xb = fvecs_read(SIFT_PATH+"bigann_base_100M.bvecs")
    i0, i1 = int(bno * xb.shape[0] / 4), int((bno + 1) * xb.shape[0] / 4)
    index = faiss.read_index(tmpdir +  SET_STRING+"_trained.index")
    print("adding vectors %d:%d" % (i0, i1))
    index.add_with_ids(xb[i0:i1], np.arange(i0, i1))
    print("write " + tmpdir +  SET_STRING+"block_%d.index" % bno)
    faiss.write_index(index, tmpdir +  SET_STRING+"block_%d.index" % bno)

if stage == 5:

    print('loading trained index')
    # construct the output index
    index = faiss.read_index(tmpdir + SET_STRING+"_trained.index")

    block_fnames = [
        tmpdir +  SET_STRING+"block_%d.index" % bno
        for bno in range(4)
    ]

    merge_ondisk(index, block_fnames, tmpdir +  SET_STRING+"merged_index.ivfdata")

    print("write " + tmpdir +  SET_STRING+"populated.index")
    faiss.write_index(index, tmpdir +  SET_STRING+"populated.index")

**I think the problem is :**
 I need to add data four times, so "add_with_ids" is needed. But when I use SET_STRING = "PCA64，IVF8192,SQ4", PCA is used,  no "add_with_ids" for  the IndexPreTransform type.  So  I add the code " index = faiss.IndexIDMap(index) "  for stage 0.
  Then  stage 5 for  merge_on_desk, which calls for the extract_index_ivf(const faiss::Index*) function, can not transform the IndexIDMap type to the IndexIVF type.

**Comment by mdouze** [comment]
IndexIDMap does not make sense for IVF indexes, see https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#ids-in-the-indexivf

**Comment by mdouze** [comment]
no activity, clsoing.
