### ISSUE TITLE
Using GpuIndexFlatIP does not work on Ubuntu 20.04 + Python 3.9

### ISSUE THREAD

**Issue by Filco306** [facebookresearch/faiss#2022]
# Summary

I am trying to use faiss for some kNN computations using GPUs, but it does not work (see below). Any ideas on what might be wrong? 

# Platform

OS:  Ubuntu 20.04

Faiss version: 

```python
>>> import faiss
>>> faiss.__version__
'1.7.0'
```
Installed from:  conda through `conda install -c conda-forge faiss-gpu`

Faiss compilation options: 

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```python
import numpy as np
import faiss
X = np.random.randn(2000, 20)
X = (X/np.linalg.norm(X,axis=1).reshape(-1,1)).astype(np.float32)
index = faiss.GpuIndexFlatIP(X.shape[1]) # changing this line to index = faiss.IndexFlatIP(X.shape[1]) makes it work
```
 

This gives me the error: 

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filco/.envs/env/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 5319, in __init__
    _swigfaiss_avx2.GpuIndexFlatIP_swiginit(self, _swigfaiss_avx2.new_GpuIndexFlatIP(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_GpuIndexFlatIP'.
  Possible C/C++ prototypes are:
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider *,faiss::IndexFlatIP *,faiss::gpu::GpuIndexFlatConfig)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider *,faiss::IndexFlatIP *)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(std::shared_ptr< faiss::gpu::GpuResources >,faiss::IndexFlatIP *,faiss::gpu::GpuIndexFlatConfig)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(std::shared_ptr< faiss::gpu::GpuResources >,faiss::IndexFlatIP *)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider *,int,faiss::gpu::GpuIndexFlatConfig)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider *,int)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(std::shared_ptr< faiss::gpu::GpuResources >,int,faiss::gpu::GpuIndexFlatConfig)
    faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(std::shared_ptr< faiss::gpu::GpuResources >,int)
```

**Comment by Filco306** [comment]
After looking at the documentation, I feel a bit stupid. Closing this issue now since the code from #505 works for me.
