### ISSUE TITLE
Doesn't FAISS support searching for torch tensors?

### ISSUE THREAD

**Issue by SirRob1997** [facebookresearch/faiss#2071]
# Summary

When searching for a torch tensor I get the following error message:

```
Traceback (most recent call last):
  File "test.py", line 91, in <module>
    dists, knns = index.search(search_this, 64)
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/faiss/__init__.py", line 144, in replacement_search
    self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I))
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/faiss/swigfaiss.py", line 6016, in swig_ptr
    return _swigfaiss.swig_ptr(a)
ValueError: input not a numpy array
```

I've also tried re-training or adding keys as torch tensors but that leads to the same error message at different steps.

# Platform

OS: Ubuntu 18.04.4 LTS

Faiss version: [1.7.0](https://pypi.org/project/faiss-gpu/1.7.0/) // 1.7.1 // 1.7.1.post2

Installed from: pip

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import faiss
import torch
import time
import os
import numpy as np

dstore_filename = 'datastore-0/'
#index_path = dstore_filename + 'faiss_index_de_DE-en_US_idx_0.trained'
index_path = 'test_index.trained'
keys_path = dstore_filename + f"/final_keys_de_DE-en_US_idx_0.npy"
vals_path = dstore_filename + f"/final_vals_de_DE-en_US_idx_0.npy"

dstore_type = np.float16
dstore_size = 25167201
dimension = 1024
keys = np.memmap(
        keys_path,
        dtype=dstore_type,
        mode="r",
        shape=(dstore_size, dimension),
)
vals = np.memmap(vals_path, dtype=int, mode="r", shape=(dstore_size, 1))

co = faiss.GpuMultipleClonerOptions()
co.shard = True
co.useFloat16 = True

#co = faiss.GpuClonerOptions()
#co.useFloat16 = True
#res = faiss.StandardGpuResources()

if not os.path.exists(index_path):
    quantizer = faiss.IndexFlatL2(dimension)
    index = faiss.IndexIVFPQ(quantizer, dimension, 4096, 64, 8)
    index.nprobe = 32

    gpu_index = faiss.index_cpu_to_all_gpus(index, co)
    print("Training Index")
    np.random.seed(42)
    random_sample = np.random.choice(
            np.arange(vals.shape[0]),
            size=[min(7000000, vals.shape[0])],
            replace=False,
            )
    start = time.time()
    gpu_index.train(keys[random_sample].astype(np.float32))
    print("Training took {} s".format(time.time() - start))
    faiss.write_index(faiss.index_gpu_to_cpu(gpu_index), index_path)

    print("Adding Keys")
    index = faiss.read_index(index_path)
    #gpu_index = faiss.index_cpu_to_gpu(res, 0, index, co)
    gpu_index = faiss.index_cpu_to_all_gpus(index, co)
    start = 0
    num_keys_to_add_at_a_time = 500000
    start_time = time.time()
    while start < dstore_size:
        end = min(dstore_size, start + num_keys_to_add_at_a_time)
        to_add = keys[start:end].copy()
        gpu_index.add_with_ids(to_add.astype(np.float32), np.arange(start, end))
        start += num_keys_to_add_at_a_time
        print("Added %d tokens so far" % start)

        if (start % 1000000) == 0:
            print(f"Writing Index {start}")
            faiss.write_index(faiss.index_gpu_to_cpu(gpu_index), index_path)

    print("Adding total %d keys" % end)
    print("Adding took {} s".format(time.time() - start_time))
    print("Writing Index")
    start = time.time()
    faiss.write_index(faiss.index_gpu_to_cpu(gpu_index), index_path)
    print("Writing index took {} s".format(time.time() - start))

index = faiss.read_index(index_path, faiss.IO_FLAG_ONDISK_SAME_DIR)
print(f'LOADED INDEX {type(index)}')
index = faiss.index_cpu_to_all_gpus(index, co)
#index = faiss.index_cpu_to_gpu(res, 0, index, co)

vals_from_memmap = np.memmap(vals_path, dtype=int, mode="r", shape=(dstore_size, 1), )
vals = np.zeros((dstore_size, 1), dtype=int)
vals = vals_from_memmap[:]
vals = vals.astype(int)
vals = torch.from_numpy(vals)
vals = vals.cuda()

print(f'VALS ARE OF TYPE {type(vals)}')

search_this = torch.rand(100, 1024)
dists, knns = index.search(search_this, 64)
print(dists, knns)
```

**Comment by SirRob1997** [comment]
Just set up a new node and ran this again, for some reason now it works fine! I guess there were some problems with other package versions...

**Comment by SirRob1997** [comment]
Importing `import faiss.contrib.torch_utils` fixed the issue
