### ISSUE TITLE
ImportError: undefined symbol: _Z9vaddq_u1612__Uint16x8_tS_

### ISSUE THREAD

**Issue by mjack3** [facebookresearch/faiss#2335]
# Summary

I can't to import FAISS in python3.6

# Platform

Jetson NX with JetPack 4.6

Faiss version: v1.7.2

Installed from: Source

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
I was installing the dependeces for use FAISS in Python3

1. Update CMAKE
2. Update SWIG 4.0
3. Install FAISS

UPDATE CMAKE
```
sudo apt remove cmake
sudo apt-get install gfortran
sudo apt-get install libssl-dev
apt install qt4-qmake
wget https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1.tar.gz
tar -xzvf cmake-*.tar.gz
cd cmake-3.23.1
sudo ./bootstrap
sudo make -j6
sudo make -j6 install
```

INSTALL SWIG 4.X
```
wget http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz
tar -xzvf swig-*tar.gz
cd swig-4.0.2/
./configure
sudo make -j6
sudo make -j6 install
```

INSTALL FAISS

```
sudo apt-get install python3-pip # or python3 won't be recognite - IDK
sudo apt-get install libblas-dev # blas
sudo apt-get install libatlas-base-dev libatlas3-base
sudo apt-get install clang-8
git clone -b v1.7.2 https://github.com/facebookresearch/faiss.git
cd faiss
cmake -B build . \ -DCUDAToolkit_ROOT=/usr/local/cuda-10.2 -DCMAKE_CUDA_ARCHITECTURES=72 -DPython_EXECUTABLE=/usr/bin/python3
make -C build -j6 faiss
make -C build -j6 swigfaiss
cd build/faiss/python
sudo python3 setup.py install
```
This is the output of latest command
```
Copying _swigfaiss.so
running install
running bdist_egg
running egg_info
writing faiss.egg-info/PKG-INFO
writing dependency_links to faiss.egg-info/dependency_links.txt
writing requirements to faiss.egg-info/requires.txt
writing top-level names to faiss.egg-info/top_level.txt
reading manifest file 'faiss.egg-info/SOURCES.txt'
writing manifest file 'faiss.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
copying faiss/swigfaiss.py -> build/lib/faiss
copying faiss/__init__.py -> build/lib/faiss
copying faiss/loader.py -> build/lib/faiss
copying faiss/_swigfaiss.so -> build/lib/faiss
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/faiss
creating build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/exhaustive_search.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/client_server.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/factory_tools.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/ivf_tools.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/__init__.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/torch_utils.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/inspect_tools.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/rpc.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/evaluation.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/ondisk.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/vecs_io.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/contrib/datasets.py -> build/bdist.linux-aarch64/egg/faiss/contrib
copying build/lib/faiss/swigfaiss.py -> build/bdist.linux-aarch64/egg/faiss
copying build/lib/faiss/_swigfaiss.so -> build/bdist.linux-aarch64/egg/faiss
copying build/lib/faiss/__init__.py -> build/bdist.linux-aarch64/egg/faiss
copying build/lib/faiss/loader.py -> build/bdist.linux-aarch64/egg/faiss
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/exhaustive_search.py to exhaustive_search.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/client_server.py to client_server.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/factory_tools.py to factory_tools.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/ivf_tools.py to ivf_tools.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/torch_utils.py to torch_utils.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/inspect_tools.py to inspect_tools.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/rpc.py to rpc.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/evaluation.py to evaluation.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/ondisk.py to ondisk.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/vecs_io.py to vecs_io.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/contrib/datasets.py to datasets.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/swigfaiss.py to swigfaiss.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/faiss/loader.py to loader.cpython-36.pyc
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/not-zip-safe -> build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying faiss.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
writing build/bdist.linux-aarch64/egg/EGG-INFO/native_libs.txt
creating 'dist/faiss-1.7.2-py3.6.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing faiss-1.7.2-py3.6.egg
removing '/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg
Extracting faiss-1.7.2-py3.6.egg to /usr/local/lib/python3.6/dist-packages
faiss 1.7.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg
Processing dependencies for faiss==1.7.2
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for faiss==1.7.2
```

Then, using python3 this is what I am getting
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: /usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/_swigfaiss.so: undefined symbol: _Z9vaddq_u1612__Uint16x8_tS_
```

 
PDT: if this work at the end, you can use it in INSATALL.md for jetson system

**Comment by mjack3** [comment]
I repeated the same process but with` sudo apt-get install swig `. In this case i need to delete the --oxygen flag and same, process finish correctly but, with this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/_swigfaiss.so: undefined symbol: _Z9vaddq_u1612__Uint16x8_tS_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.2-py3.6.egg/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_swigfaiss'
```

**Comment by mjack3** [comment]
Finally I get it

```
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
>>> faiss.__version__
'1.7.2'
>>> 
```

I'll check tomorrow and will update this with the steps.

**Comment by mjack3** [comment]
Solved. It seem that we need to use clang compile. I reproduced the installation twice in order to make sure it works.
This is a really complete guide for installing from source.

**Comment by mdouze** [comment]
This is related to the ARM SIMD instructions, which require specific flags.

**Comment by mjack3** [comment]
Hello @mdouze thanks.

Could you details the needed flags?
