### ISSUE TITLE
Clone not supported for this type of IndexIVF

### ISSUE THREAD

**Issue by mitchellgordon95** [facebookresearch/faiss#2361]
# Summary

I'm trying to move a trained composite index to a GPU, so that adding embeddings (~5.8B) to the index is faster. However, my IndexIVF cannot be cloned onto the GPU. Here's a minimal reproducing snippet:

```
import faiss

index = faiss.index_factory(128, "OPQ4_64,IVF16384_HNSW32,PQ16x4fs")
xt = faiss.rand((20000, 128))
index.train(xt)

faiss.index_cpu_to_all_gpus(index)
```

which yields:

```
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    faiss.index_cpu_to_all_gpus(index)
  File "/opt/conda/lib/python3.8/site-packages/faiss/__init__.py", line 887, in index_cpu_to_all_gpus
    index_gpu = index_cpu_to_gpus_list(index, co=co, gpus=None, ngpu=ngpu)
  File "/opt/conda/lib/python3.8/site-packages/faiss/__init__.py", line 899, in index_cpu_to_gpus_list
    index_gpu = index_cpu_to_gpu_multiple_py(res, index, co, gpus)
  File "/opt/conda/lib/python3.8/site-packages/faiss/__init__.py", line 882, in index_cpu_to_gpu_multiple_py
    index = index_cpu_to_gpu_multiple(vres, vdev, index, co)
  File "/opt/conda/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 10278, in index_cpu_to_gpu_multiple
    return _swigfaiss_avx2.index_cpu_to_gpu_multiple(provider, devices, index, options)
RuntimeError: Error in virtual faiss::IndexIVF* faiss::Cloner::clone_IndexIVF(const faiss::IndexIVF*) at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/clone_index.cpp:71: clone not supported for this type of IndexIVF
```

Is this expected behavior? The IndexIVF I'm using doesn't seem to be special. I've also tried:

```
index_ivf = faiss.extract_index_ivf(index)
index_ivf = faiss.index_cpu_to_all_gpus(index_ivf)
```

with similar results.

# Platform

OS: `Linux 53143a0863f8 5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
(Docker image `nvidia/cuda:11.3.0-devel-ubuntu20.04`)

Faiss version: 

```
root@fddb9798ebfc:/src# conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
attrs                     21.4.0                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py38h27cfd23_1003
ca-certificates           2022.4.26            h06a4308_0
certifi                   2022.5.18.1      py38h06a4308_0
cffi                      1.15.0           py38hd667e15_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.4              pyhd3eb1b0_0
conda                     4.13.0           py38h06a4308_0
conda-content-trust       0.1.1              pyhd3eb1b0_0
conda-package-handling    1.8.1            py38h7f8727e_0
cryptography              37.0.1           py38h9ce1e76_0
cudatoolkit               11.3.1               h2bc3f7f_2
einops                    0.4.1                    pypi_0    pypi
faiss-gpu                 1.7.2           py3.8_h28a55e0_0_cuda11.3    pytorch
filelock                  3.7.1                    pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
huggingface-hub           0.7.0                    pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.11.1                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
jsonlines                 3.0.0                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9
libfaiss                  1.7.2           hfc2d529_0_cuda11.3    pytorch
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-ng              9.3.0               hd4cf53a_17
libuv                     1.40.0               h7b6447c_0
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py38h7f8727e_0
mkl_fft                   1.3.1            py38hd3c417c_0
mkl_random                1.2.2            py38h51133e4_0
ncurses                   6.3                  h7f8727e_2
numpy                     1.22.3           py38he7a7128_0
numpy-base                1.22.3           py38hf524024_0
openssl                   1.1.1o               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pip                       21.2.4           py38h06a4308_0
pycosat                   0.6.3            py38h7b6447c_1
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0
python                    3.8.13               h12debd9_0
pytorch                   1.10.2          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1
regex                     2022.6.2                 pypi_0    pypi
requests                  2.27.1             pyhd3eb1b0_0
retro-pytorch             0.3.7                    pypi_0    pypi
ruamel_yaml               0.15.100         py38h27cfd23_0
sentencepiece             0.1.96                   pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.2               hc218d9a_0
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0
tokenizers                0.12.1                   pypi_0    pypi
tqdm                      4.63.0             pyhd3eb1b0_0
transformers              4.20.0                   pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022a                hda174b7_0
urllib3                   1.26.8             pyhd3eb1b0_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_1
```

Installed from: Anaconda

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

**Comment by mdouze** [comment]
The index type that you build here is tuned for CPU indexing. 

"OPQ4_64,IVF16384_HNSW32,PQ16x4fs"

- IVFx_HNSW is not supported (and not necessary) on GPU: use IVF16386

- the "fs" variant of PQ is not supported on GPU. Only 8-bit PQ is supported (and more accurate anyways). 

So this boils down to "OPQ8_64,IVF16386,PQ8"

**Comment by mitchellgordon95** [comment]
Ah, thank you for replying! This answers my question so I will close the issue. 

I am not sure I will be able to get away with "IVF16386,PQ8" since I have >5B vectors, but I will do some benchmarking to see what works for me.
