### ISSUE TITLE
demo_auto_tune.py TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by yja1** [facebookresearch/faiss#262]
faiss-master$ export PYTHONPATH=.
faiss-master$ python python/demo_auto_tune.py
load data
Traceback (most recent call last):
  File "python/demo_auto_tune.py", line 56, in <module>
    xt = fvecs_read("sift1M/sift_learn.fvecs")
  File "python/demo_auto_tune.py", line 35, in fvecs_read
    return ivecs_read(fname).view('float32')
  File "python/demo_auto_tune.py", line 31, in ivecs_read
    a = np.fromfile(f, count = n * (d +1), dtype = 'int32').reshape(n, d + 1)
TypeError: integer argument expected, got float

**Comment by mdouze** [comment]
Hi 
You are probably using python3. `demo_auto_tune.py` is a python2 script currently.
