### ISSUE TITLE
Stuck at swigfaiss_avx2.py

### ISSUE THREAD

**Issue by SingL3** [facebookresearch/faiss#2753]
# Summary

I am using [autofaiss](https://github.com/criteo/autofaiss) to build index for my embeddings.
I decrease on purpose to try to select a best max_index_memory_usage.
First I try 4G and it is quite enough for my data(50,000 x 512 embeddings), and it finished in less than 2 mins.
Because the whole index just use 100+M memory, I set max_index_memory_usage to 50M and the process just stuck.

# Platform

OS: ubuntu 18.04

Faiss version: faiss-cpu 1.7.3

Installed from: conda

Running on:
CPU

Interface: 
Python

# Reproduction instructions

            build_index(
                embeddings=emb_folder,
                index_path=index_folder + "/" + index_name + ".index",
                index_infos_path=index_folder + "/" + index_name + ".json",
                max_index_memory_usage=max_index_memory_usage, # "50M"
                current_memory_available=current_memory_available, "16G"
                nb_cores=nb_cores,
            )

log:
2023-03-09 18:06:44,156 [INFO]: Using 128 omp threads (processes), consider increasing --nb_cores if you have more
2023-03-09 18:06:44,157 [INFO]: Launching the whole pipeline 03/09/2023, 18:06:44
2023-03-09 18:06:44,157 [INFO]: Reading total number of vectors and dimension 03/09/2023, 18:06:44
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 335.44it/s]
2023-03-09 18:06:44,219 [INFO]: There are 50000 embeddings of dim 512
2023-03-09 18:06:44,220 [INFO]: >>> Finished "Reading total number of vectors and dimension" in 0.0624 secs
2023-03-09 18:06:44,220 [INFO]:         Compute estimated construction time of the index 03/09/2023, 18:06:44
2023-03-09 18:06:44,220 [INFO]:                 -> Train: 16.7 minutes
2023-03-09 18:06:44,220 [INFO]:                 -> Add: 0.3 seconds
2023-03-09 18:06:44,220 [INFO]:                 Total: 16.7 minutes
2023-03-09 18:06:44,220 [INFO]:         >>> Finished "Compute estimated construction time of the index" in 0.0002 secs
2023-03-09 18:06:44,220 [INFO]:         Checking that your have enough memory available to create the index 03/09/2023, 18:06:44
2023-03-09 18:06:44,221 [INFO]: 393.0MB of memory will be needed to build the index (more might be used if you have more)
2023-03-09 18:06:44,221 [INFO]:         >>> Finished "Checking that your have enough memory available to create the index" in 0.0010 secs
2023-03-09 18:06:44,221 [INFO]:         Selecting most promising index types given data characteristics 03/09/2023, 18:06:44
2023-03-09 18:06:44,221 [INFO]:         >>> Finished "Selecting most promising index types given data characteristics" in 0.0001 secs
2023-03-09 18:06:44,222 [INFO]:         Creating the index 03/09/2023, 18:06:44
2023-03-09 18:06:44,222 [INFO]:                 -> Instanciate the index OPQ256_768,IVF1024_HNSW32,PQ256x8 03/09/2023, 18:06:44
2023-03-09 18:06:44,229 [INFO]:                 >>> Finished "-> Instanciate the index OPQ256_768,IVF1024_HNSW32,PQ256x8" in 0.0069 secs
2023-03-09 18:06:44,229 [INFO]: The index size will be approximately 15.6MB
2023-03-09 18:06:44,229 [INFO]:                 -> Extract training vectors 03/09/2023, 18:06:44
2023-03-09 18:06:44,229 [INFO]: Will use 50000 vectors to train the index, that will use 611.4MB of memory
 50%|█████████████████████████████████████████████████████████████████████████████▌                                                                             | 1/2 [00:00<00:00,  4.45it/s]
2023-03-09 18:06:44,456 [INFO]:                 >>> Finished "-> Extract training vectors" in 0.2275 secs
2023-03-09 18:06:44,456 [INFO]:                 -> Training the index with 50000 vectors of dim 512 03/09/2023, 18:06:44
!!! I interrupt here because it takes too long.
^C2023-03-10 12:00:24,868 [INFO]:               >>> Finished "-> Training the index with 50000 vectors of dim 512" in 64420.4108 secs
2023-03-10 12:00:24,868 [INFO]:         >>> Finished "Creating the index" in 64420.6462 secs
2023-03-10 12:00:24,868 [INFO]: >>> Finished "Launching the whole pipeline" in 64420.7108 secs
Traceback (most recent call last):
  File "clip_index.py", line 70, in <module>
    fire.Fire(clip_index)
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "clip_index.py", line 49, in clip_index
    quantize(
  File "clip_index.py", line 24, in quantize
    build_index(
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 286, in build_index
    index, metric_infos = create_index(
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/autofaiss/external/build.py", line 157, in create_index
    trained_index = create_and_train_new_index(
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/autofaiss/indices/training.py", line 108, in create_and_train_new_index
    index = _train_index(embedding_reader, index_key, index, metadata, current_memory_available, use_gpu)
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/autofaiss/indices/training.py", line 86, in _train_index
    index.train(train_vectors)
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/faiss/class_wrappers.py", line 298, in replacement_train
    self.train_c(n, swig_ptr(x))
  File "/mnt/data/conda/envs/clip/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 3630, in train
    return _swigfaiss_avx2.IndexPreTransform_train(self, n, x)
KeyboardInterrupt

**Comment by mdouze** [comment]
This problem seems to be related to Autofaiss.
