### ISSUE TITLE
Clone not supported for this type of Index

### ISSUE THREAD

**Issue by iDarkSnow** [facebookresearch/faiss#2773]
# Summary
I'm trying to implement a KNearestNeighbor classifier.
I'm trying to move a IndexFlat which i've previously moved on the GPU to add the training data and perform the search on the test data. 
Then, I need to save the model so I need to move it back on the CPU, but i get a Runtime error. Here's a minimal reproducing snippet:

```
 import faiss
 import numpy as np
 index = faiss.IndexFlat(X.shape[1], faiss.METRIC_BrayCurtis)
 index = faiss.index_cpu_to_gpu(self.res, 0, self.index)
 index.add(np.ascontiguousarray(X.astype(np.float32)))
 index = faiss.index_gpu_to_cpu(index)
```

which yields:
```
Traceback (most recent call last):
  File "/home/alessiocitro/word_spotting/Codice/main.py", line 6, in <module>
  index = faiss.index_gpu_to_cpu(index)
  File "/home/alessiocitro/anaconda3/envs/word_spotting/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py", line 10271, in index_gpu_to_cpu
    return _swigfaiss_avx2.index_gpu_to_cpu(gpu_index)
RuntimeError: Error in virtual faiss::Index* faiss::Cloner::clone_Index(const faiss::Index*) at /home/conda/feedstock_root/build_artifacts/faiss-split_1644327811086/work/faiss/clone_index.cpp:147: clone not supported for this type of Index
```

# Platform

OS: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```
Faiss version: 
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
_tflow_select             2.3.0                       mkl  
abseil-cpp                20211102.0           hd4dd3e8_0  
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1           py310h5764c6d_1    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0  
arrow-cpp                 8.0.0           py310h3098874_1  
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
aws-c-common              0.4.57               he6710b0_1  
aws-c-event-stream        0.1.6                h2531618_5  
aws-checksums             0.1.9                he6710b0_0  
aws-sdk-cpp               1.8.185              hce553d0_0  
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
blas                      1.0                    openblas  
blinker                   1.5                pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               h6a678d5_0  
boost-cpp                 1.73.0              h7f8727e_12  
bottleneck                1.3.5           py310ha9d4c09_0  
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py310h7f8727e_1002  
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0               hb05425b_3  
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3  
cfitsio                   3.470                hb418390_7    conda-forge
charls                    2.2.0                h2531618_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              39.0.1          py310h9ce1e76_0  
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
cytoolz                   0.12.0          py310h5eee18b_0  
dask-core                 2023.3.1           pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0  
deap                      1.3.1           py310h769672d_5    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docutils                  0.19            py310hff52083_1    conda-forge
editdistance              0.6.1           py310h6a678d5_0  
eigen                     3.3.7                hd09550d_1  
expat                     2.4.9                h6a678d5_0  
faiss                     1.7.2           py310cuda112h76f6547_0_cuda    conda-forge
faiss-gpu                 1.7.2                h788eb59_3    conda-forge
ffmpeg                    4.2.2                h20bf706_0  
flatbuffers               2.0.0                h2531618_0  
fontconfig                2.14.1               h52c9d5c_1  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3           py310h5eee18b_0  
fsspec                    2023.3.0           pyhd8ed1ab_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gflags                    2.2.2                he6710b0_0  
giflib                    5.2.1                h5eee18b_3  
glib                      2.69.1               he621ea3_2  
glog                      0.5.0                h2531618_0  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.16.2             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.14               h295c915_1  
grpc-cpp                  1.46.1               h33aed49_1  
grpcio                    1.42.0          py310hce63b2e_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
h5py                      3.7.0           py310he06866b_0  
harfbuzz                  4.3.0                hd55b92a_0  
hdf5                      1.10.6               h3ffc7dd_1  
icu                       58.2                 he6710b0_3  
idna                      3.4             py310h06a4308_0  
imagecodecs               2021.8.26       py310h46e8fbd_2  
imageio                   2.26.0             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.1           py310h06a4308_0  
jpeg                      9e                   h5eee18b_1  
jxrlib                    1.1                  h7f98852_2    conda-forge
keras                     2.11.0             pyhd8ed1ab_0    conda-forge
krb5                      1.19.4               h568e23c_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libboost                  1.73.0              h28710b8_12  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  10.0.1          default_hb85057a_2  
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.0.25                      0    nvidia
libcurand                 10.3.2.56                     0    nvidia
libcurl                   7.87.0               h91b91d3_0  
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               h8f2d780_0  
libfaiss                  1.7.2           cuda112hc9ed507_0_cuda    conda-forge
libfaiss-avx2             1.7.2           cuda112h1234567_0_cuda    conda-forge
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libnghttp2                1.46.0               hce63b2e_0  
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libopenblas               0.3.21               h043d6bf_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.9                 h16c4e8d_3  
libprotobuf               3.20.3               he621ea3_0  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libthrift                 0.15.0               hcc01f38_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                hfa300c1_0  
libxml2                   2.9.14               h74e7548_0  
libxslt                   1.1.35               h4e12654_0  
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
lmdb                      0.9.29               h166bdaf_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h7f8727e_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310h7f8727e_0  
multidict                 6.0.2           py310h5eee18b_0  
multiprocess              0.70.12.2       py310h5764c6d_2    conda-forge
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.0                pyhd8ed1ab_0    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numexpr                   2.8.4           py310h757a811_0  
numpy                     1.23.5          py310hac523dd_0  
numpy-base                1.23.5          py310h375b286_0  
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
opencv                    4.6.0           py310h1128e8f_3  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1t               h7f8727e_0  
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
orc                       1.7.4                hb3bc3d3_1  
packaging                 22.0            py310h06a4308_0  
pandas                    1.5.3           py310h1128e8f_0  
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
path                      16.6.0          py310hff52083_0    conda-forge
pcre                      8.45                 h295c915_0  
pillow                    9.4.0           py310h6a678d5_0  
pip                       23.0.1          py310h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
pooch                     1.4.0              pyhd3eb1b0_0  
protobuf                  3.20.3          py310h6a678d5_0  
pyarrow                   8.0.0           py310h468efa6_0  
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.6.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0          py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.9               h7a1cb2a_2  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-flatbuffers        23.1.21            pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.12.1          cpu_py310h9dbd814_1  
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310h5eee18b_0  
pyyaml                    6.0             py310h5764c6d_4    conda-forge
qt-main                   5.15.2               h327a75a_7  
qt-webengine              5.15.9               hd2b0992_4  
qtwebkit                  5.212                h4eab89a_4  
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1          py310h06a4308_0  
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scikit-image              0.19.2          py310hb5077e9_0    conda-forge
scikit-learn              1.2.1           py310h6a678d5_0  
scipy                     1.10.0          py310heeff2f4_1  
setuptools                65.6.3          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sklearn-genetic           0.5.1              pyhd8ed1ab_0    conda-forge
snappy                    1.1.9                h295c915_0  
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    6.1.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.40.1               h5082296_0  
tensorboard               2.11.0          py310h06a4308_0  
tensorboard-data-server   0.6.1           py310h52d8a92_0  
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.11.0          mkl_py310hb40ee82_0  
tensorflow-base           2.11.0          mkl_py310he5f8e37_0  
tensorflow-estimator      2.11.0          py310h06a4308_0  
termcolor                 2.2.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh0d69192_0  
tifffile                  2021.4.8           pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torchaudio                0.12.1                py310_cpu    pytorch
torchvision               0.13.1                py310_cpu    pytorch
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.14         py310h06a4308_0  
utf8proc                  2.6.1                h27cfd23_0  
werkzeug                  2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4          py310h06a4308_0  
wrapt                     1.14.1          py310h5eee18b_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2           py310h5764c6d_2    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.2                ha4553b6_0  
```

Installed from: Anaconda

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
In which line does the code fail and what is the error message?

**Comment by iDarkSnow** [comment]
Sorry for the lack of clarity, the code is divided in different modules so I just showed the implementation I made for the KNN.
The error message is the following:
```
Traceback (most recent call last):
  File "/home/alessiocitro/word_spotting/Codice/main.py", line 10, in <module>
    sift_reports_washington_reduced, hog_reports_washington_reduced, lgh_reports_washington_reduced, gabor_reports_washington_reduced = feature_selection.run_feature_selection('features_washington.parquet')
  File "/home/alessiocitro/word_spotting/Codice/feature_selection.py", line 197, in run_feature_selection
    sift_report = sift_experiment(training_data.loc[:, ["Word", "SIFT_1", "SIFT_2", "SIFT_3", "SIFT_4", "SIFT_5", "SIFT_6", "SIFT_7", "SIFT_8", "SIFT_9", "SIFT_10"] + words], 
  File "/home/alessiocitro/word_spotting/Codice/feature_selection.py", line 55, in sift_experiment
    fitted_estimator.save(path)
  File "/home/alessiocitro/word_spotting/Codice/KNNClassifier.py", line 33, in save
    self.index = faiss.index_gpu_to_cpu(self.index)
  File "/home/alessiocitro/anaconda3/envs/word_spotting/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py", line 10271, in index_gpu_to_cpu
    return _swigfaiss_avx2.index_gpu_to_cpu(gpu_index)
RuntimeError: Error in virtual faiss::Index* faiss::Cloner::clone_Index(const faiss::Index*) at /home/conda/feedstock_root/build_artifacts/faiss-split_1644327811086/work/faiss/clone_index.cpp:147: clone not supported for this type of Index
```
The line that gives the error is in the save function of my KNNClassifier class, in particular:
`self.index = faiss.index_gpu_to_cpu(self.index)`

**Comment by iDarkSnow** [comment]
Sorry for the inconvenient, I was able to solve the problem. In one of the different modules I was returning clone(knnclassifier) instead of the knnclassifier itself. Returning the object itself seems to have solved the problem.

**Comment by iDarkSnow** [comment]
Sorry for the inconvenient, I was able to solve the problem. In one of the different modules I was returning clone(knnclassifier) instead of the knnclassifier itself. Returning the object itself seems to have solved the problem.
