### ISSUE TITLE
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by meghbhalerao** [facebookresearch/faiss#2883]
# Summary
I am facing the issue - `ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory` for python versions higher than 3.6 when I try to install faiss-cpu only by using the following command - `conda install faiss-cpu -c pytorch`

OS - 
```
   Static hostname: debian
Transient hostname: megh-176-vcpu-box
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 605f692aca9c243c905eb7f1c84e71c0
           Boot ID: c54aa861b5f74cd28034ce21e3aef473
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-23-cloud-amd64
      Architecture: x86-64
```

Faiss version: `faiss-cpu                 1.7.4           py3.9_h8c27c75_0_cpu    pytorch`

Installed from: conda install faiss-cpu -c pytorch 

Running on: CPU

Interface:  Python

# Reproduction instructions
1. Have conda installed 
2. Do conda create -n faiss python=3.9
3. conda activate faiss
4. conda install faiss-cpu -c pytorch
5. python -c "import faiss"
6. I get the following error - 
Traceback (most recent call last):
```
  File "<string>", line 1, in <module>
  File "/home/megh.bhalerao/pkgs/anaconda3/envs/py39/lib/python3.9/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/home/megh.bhalerao/pkgs/anaconda3/envs/py39/lib/python3.9/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/home/megh.bhalerao/pkgs/anaconda3/envs/py39/lib/python3.9/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

```

**Comment by mdouze** [comment]
right, we are aware of this problem. There seems to be a fix in  #2880

**Comment by mlomeli1** [comment]
As Matthijs mentions, you can use `conda install mkl==2021.4.0 faiss-gpu=1.7.4 -c pytorch -c nvidia` @meghbhalerao
