### ISSUE TITLE
TypeError: in method 'IndexFlat_range_search', argument 4 of type 'float'

### ISSUE THREAD

**Issue by svalkiers** [facebookresearch/faiss#2894]
# Summary

I have been using the `range_search` functionality with great success within the Python interpreter. However, when I attempt to call it through a bash interface, I get prompted the following error:

```
Traceback (most recent call last):
  File "/path_to_script/test_faiss_cmd.py", line 24, in <module>
    lim, D, I = idx.range_search(X, thresh=r)
  File "/home/sebastiaan/miniconda3/envs/knn_tcr/lib/python3.9/site-packages/faiss/__init__.py", line 492, in replacement_range_search
    self.range_search_c(n, swig_ptr(x), thresh, res)
  File "/home/sebastiaan/miniconda3/envs/knn_tcr/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 1631, in range_search
    return _swigfaiss_avx2.IndexFlat_range_search(self, n, x, radius, result)
TypeError: in method 'IndexFlat_range_search', argument 4 of type 'float'
```
Running the exact same code in a Python interpreter does not produce the error, it only occurs from a command line interface.

# Platform

OS: Ubuntu 20.04.5 LTS

Faiss version: faiss 1.7.2 py39h44b29b8_3_cpu conda-forge

Installed from: anaconda 

Faiss compilation options: /

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```python
import faiss

# Generate random input array of shape (n, d)
n = 500
d = 272python3 test_faiss_cmd.py --n_vecs 100 --n_dims 272 --radius 50
vecs = np.random.rand(n,d).astype("float32")

# Build Flat Index
idx = faiss.IndexFlatL2(272)
idx.train(vecs)
idx.add(vecs)

# Search Flat Index
r = 24
X = np.random.rand(1,d).astype("float32")
lim, D, I = idx.range_search(X, thresh=r)
```

This example runs perfectly in a Python interpreter. However, in the following situation, this script fails and prompts the error that was mentioned previously.

`argparse` script (test_faiss_cmd.py):

```python
import faiss
import numpy as np
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--n_vecs', type=int)
parser.add_argument('--n_dims', type=int)
parser.add_argument('--radius')
args = parser.parse_args()

# Generate random input array of shape (n, d)
n = args.n_vecs
d = args.n_dims
vecs = np.random.rand(n,d).astype("float32")

# Build Flat Index
idx = faiss.IndexFlatL2(args.n_dims)
idx.train(vecs)
idx.add(vecs)

# Search Flat Index
r = args.radius
X = np.random.rand(1,d).astype("float32")
lim, D, I = idx.range_search(X, thresh=r)
```
Command line:
`python3 test_faiss_cmd.py --n_vecs 100 --n_dims 272 --radius 50`

**Comment by mdouze** [comment]
radius is a string......

**Comment by svalkiers** [comment]
Wow, I can't believe I did not realize this. Issue solved.
