### ISSUE TITLE
I have some small problems on my code

### ISSUE THREAD

**Issue by hackermengzhi** [facebookresearch/faiss#2923]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [√ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [√ ] Python

# Reproduction instructions

My code here:
import argparse, torch, torchaudio, faiss, pickle, os
from torchaudio.sox_effects import apply_effects_tensor
from torchaudio.transforms import MelSpectrogram
import pickle
import numpy as np
# Load the model
wav2mel = torch.jit.load("wav2mel.pt")
dvector = torch.jit.load("dvector.pt").eval()

def audio_procession(file_path):
    # Load the waveform
    wav_tensor, sample_rate = torchaudio.load(file_path)
    mel_tensor = wav2mel(wav_tensor, sample_rate)  # shape: (frames, mel_dim)
    
    # Compute embedding
    emb_tensor = dvector.embed_utterance(mel_tensor)  # shape: (emb_dim)
    return emb_tensor

def registration(file_path):
    name = os.path.splitext(os.path.basename(file_path))[0]
    emb_tensor = audio_procession(file_path)
    emb_numpy = emb_tensor.detach().numpy().reshape(1, -1)
    # Convert the string ID to an integer
    id_int = int(hash(name[-4:]))  # This is a simple way to convert a string to an integer

    # Create a NumPy array with the integer ID
    ids = np.array([id_int], dtype=np.int64)
    .values.astype(np.int64)
    index_file = "emb_index.index"
    if os.path.exists(index_file):
        # Load the existing index
        index = faiss.read_index(index_file)
    else:
        # Create a new index
        index = faiss.IndexFlatL2(emb_tensor.shape[0])
  
    # Add the new vector to the index
    index.add_with_ids(emb_numpy,ids)

    # Write the index back to the file
    faiss.write_index(index, index_file)
    

def recognition(file_path):
    emb_tensor = audio_procession(file_path)
    emb_numpy = emb_tensor.detach().numpy().reshape(1, -1)
    index_file = "emb_index.index"
    index = faiss.read_index(index_file)
    k = 1
    D, I = index.search(emb_numpy, k)
    # Look up the names for the returned IDs
    returned_names = id_to_name[I]
      
    print(returned_names)
    # Load the name to index mapping
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Demo script")
    parser.add_argument("--file", type=str, help="Input file path")
    parser.add_argument("--mode", type=str, help="Mode: register or recognize")
    args = parser.parse_args()

    if args.mode == "register":
        registration(args.file)
    elif args.mode == "recognize":
        recognition(args.file)
and it was error:]Traceback (most recent call last):
  File "demo.py", line 67, in <module>
    registration(args.file)
  File "demo.py", line 38, in registration
    index.add_with_ids(emb_numpy,ids)
  File "/home/docker/.local/lib/python3.8/site-packages/faiss/__init__.py", line 235, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "/home/docker/.local/lib/python3.8/site-packages/faiss/swigfaiss.py", line 1921, in add_with_ids
    return _swigfaiss.Index_add_with_ids(self, n, x, xids)
RuntimeError: Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const idx_t*) at /project/faiss/faiss/Index.cpp:39: add_with_ids not implemented for this type of index
I wander some help on the use of add_with_ids,could anyone help me?

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#faiss-id-mapping

**Comment by mlomeli1** [comment]
hi @hackermengzhi  please see the link that Matthijs added above, it should sort out your issue.
