### ISSUE TITLE
Faiss 1.7.4 does not recognize library libstdcxx-ng-11.2.0

### ISSUE THREAD

**Issue by ahadda5** [facebookresearch/faiss#3219]
# Summary

faiss-gpu=1.7.4. is not playing well with libstdc++ version 11.0.2 . 

```
[2024-01-22 12:01:35,163][INFO][faiss.loader] Could not load library with AVX2 support due to:
**ImportError("/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /anaconda3/envs/test/lib/python3.10/site-packages/faiss/_swigfaiss_avx2.so)")**
[2024-01-22 12:01:35,163][INFO][faiss.loader] Loading faiss.
Traceback (most recent call last):
  File "/anaconda3/envs/test/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 55, in dependable_faiss_import
    import faiss
  File "/anaconda3/envs/test/lib/python3.10/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/anaconda3/envs/tes/lib/python3.10/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/anaconda3/envs/test/lib/python3.10/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
**ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /anaconda3/envs/test/lib/python3.10/site-packages/faiss/_swigfaiss.so)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/appadmin/lms-model/test/import_data.py", line 221, in <module>
    import_data(docs)
  File "/home/appadmin/lms-model/test/import_data.py", line 132, in import_data
    faiss_vectorstore = FAISS.from_documents(semantic_docs, embeddings,
  File "/anaconda3/envs/test/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/anaconda3/envs/test/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 914, in from_texts
    return cls.__from(
  File "/anaconda3/envs/test/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 868, in __from
    faiss = dependable_faiss_import()
  File "/anaconda3/envs/test/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 57, in dependable_faiss_import
    raise ImportError(
ImportError: Could not import faiss python package. Please install it with `pip install faiss-gpu` (for CUDA supported GPU) or `pip install faiss-cpu` (depending on Python version).
(test) appadmin@BRLLMAPP02:~/lms-model/test$ 
```

# Platform

OS: ubuntu 20.04.6

Faiss version: 1.7.4

Installed from: anaconda

Faiss compilation options: 
```
conda create --name test python=3.10
conda activate course_chat
conda install faiss-gpu=1.7.4 mkl=2021 pytorch pytorch-cuda numpy -c pytorch -c nvidia
```

Running on:
- [ ] CPU
- [ x] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

Invoking a simple call to faiss  produces the error above.

**Comment by ahadda5** [comment]
GNU libstdcxx version 11.2.0 comes from [here](https://docs.anaconda.com/free/anaconda/reference/packages/pkg-docs/)

**Comment by ahadda5** [comment]
[Solved ](https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29)

**Comment by ahadda5** [comment]
[ldd issue ](https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29),  This is a linkage issue and not an issue with Faiss. So I will close it.
