### ISSUE TITLE
Use MultiIndexQuantizer in IVFPQ index faild 

### ISSUE THREAD

**Issue by DoItWithMe** [facebookresearch/faiss#3229]
# Summary
Using MultiIndexQuantizer fails in IVFPQ.  

The example code I learn is: https://github.com/facebookresearch/faiss/blob/v1.7.4/tests/test_index.py#L171

# Platform

OS: 

Faiss version: faiss-cpu=1.7.4

Installed from:  anaconda, pytorch, 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
My code:
![image](https://github.com/facebookresearch/faiss/assets/35800879/ab830c80-7fd1-47fe-9a07-da2843e9d8d5)
  
My log:
Traceback (most recent call last):
  File "/data/fabiss/video-dna-faiss/src/./main.py", line 739, in <module>
    main()
  File "/data/fabiss/video-dna-faiss/src/./main.py", line 734, in main
    test_fabiss()
  File "/data/fabiss/video-dna-faiss/src/./main.py", line 459, in test_fabiss
    build_IndexIVFPQ_faiss_with_MultiIndexQuantizer(
  File "/data/fabiss/video-dna-faiss/src/./main.py", line 234, in build_IndexIVFPQ_faiss_with_MultiIndexQuantizer
    faiss_index = faiss.IndexIVFPQ(
  File "/root/miniconda3/envs/python310-faiss/lib/python3.10/site-packages/faiss/__init__.py", line 93, in replacement_init
    original_init(self, *args)
  File "/root/miniconda3/envs/python310-faiss/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py", line 7455, in __init__
    _swigfaiss_avx2.IndexIVFPQ_swiginit(self, _swigfaiss_avx2.new_IndexIVFPQ(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_IndexIVFPQ'.
  Possible C/C++ prototypes are:
    faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index *,size_t,size_t,size_t,size_t,faiss::MetricType)
    faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index *,size_t,size_t,size_t,size_t)
    faiss::IndexIVFPQ::IndexIVFPQ()

**Comment by mdouze** [comment]
could you double check that all 4 int arguments are indeed ints?

**Comment by DoItWithMe** [comment]
It's same error even I cast the 4 arguments to int.
![image](https://github.com/facebookresearch/faiss/assets/35800879/d6390c30-9471-49b2-94ad-f03a52ac2767)


> could you double check that all 4 int arguments are indeed ints?
