### ISSUE TITLE
GPU OOM on index.search() using IndexIVFPQ

### ISSUE THREAD

**Issue by wenting-zhao** [facebookresearch/faiss#3259]
# Summary

GPU OOM errors in index.search() for an index of size 609687689x4096 (~41GB), when I still have 40GB of unused GPU memory. I would like to run search on GPU (as the time of CPU search is too long > 1000 hours). Any advice on how to fit the search into GPU memory is greatly appreciated. Specifically, I wondered if it is possible to break the index into a few chunks. For example, I first search the first 10% entries, then next 10% etc.

Faiss version: v1.7.4

Installed from: conda

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```
import faiss
cpu_index = faiss.read_index("index_llama_609687689_4096.indexed", faiss.IO_FLAG_ONDISK_SAME_DIR) # this is 41GB
co = faiss.GpuClonerOptions()
co.useFloat16 = True
gpu_resource = faiss.StandardGpuResources()
gpu_index = faiss.index_cpu_to_gpu(gpu_resource, 0, cpu_index, co)
import torch; search_this = torch.rand(1, 4096)
dists, knns = gpu_index.search(search_this, 10)
```
leads to the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wz346/miniconda3/envs/faiss/lib/python3.9/site-packages/faiss/class_wrappers.py", line 343, in replacement_search
    self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I), params)
  File "/home/wz346/miniconda3/envs/faiss/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 10849, in search
    return _swigfaiss_avx2.GpuIndex_search(self, n, x, k, distances, labels, params)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /home/circleci/miniconda/conda-bld/faiss-pkg_1683504247947/work/faiss/gpu/StandardGpuResources.cpp:514: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryOverflow dev 0 space Device stream 0x6bd9ee0 size 624320193536 bytes (cudaMalloc error out of memory [2])
```
but I still have 40G unused memory.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off | 00000000:07:00.0 Off |                    0 |
| N/A   35C    P0              73W / 400W |  44323MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   3407756      C   python                                    44310MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by mdouze** [comment]
Could you try with the latest nightly build? There was an inefficiency in memory allocation that was addressed recently.
