### ISSUE TITLE
Error when deploying through StreamlitCloud but working fine locally

### ISSUE THREAD

**Issue by joelsiby02** [facebookresearch/faiss#3300]
When i run on localHost its working fine, The issue is when i deploy it on Streamlit Cloud
def get_vector_store(text_chunks):
    embeddings = GoogleGenerativeAIEmbeddings(model = 'models/embedding-001')
    vector_store= FAISS.from_texts(text_chunks, embedding= embeddings)
    vector_store.save_local("faiss_index")
    
    
    When i deploy and use this application it raises an error :-
    
    
    Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/askaway_pdf/app.py", line 126, in <module>

    main()

  File "/mount/src/askaway_pdf/app.py", line 117, in main

    get_vector_store(text_chunks)

  File "/mount/src/askaway_pdf/app.py", line 42, in get_vector_store

    embeddings = GoogleGenerativeAIEmbeddings(model = 'models/embedding-001')

  File "/home/adminuser/venv/lib/python3.9/site-packages/pydantic/v1/main.py", line 341, in __init__

    raise validation_error

**Comment by mlomeli1** [comment]
Hi @joelsiby02 , this issue is related to the faiss class in Langchain not to the faiss library, please submit the issue to the langchain repo.
