### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by rsuwaileh** [facebookresearch/faiss#3393]
# Summary

I'm trying to import `faiss` in my python script but I'm getting the following error:
```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /../.conda/envs/my_project/lib/python3.6/site-packages/faiss/_swigfaiss.so)
```

OS: Oracle Linux Server, version=7.6

Faiss version: 1.5.3

Installed using the following commands:
```
conda install -c pytorch faiss-cpu
conda install pytorch::faiss-cpu
conda install pytorch/label/nightly::faiss-cpu
```

Running on:  CPU

Interface: Python

# Reproduction instructions

When running the following code:
```
import faiss
```

I get the following error:

```
Traceback (most recent call last):
  File "create_index.py", line 2, in <module>
    import faiss
  File "/../.conda/envs/my_project/lib/python3.6/site-packages/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/../.conda/envs/my_project/lib/python3.6/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/../.conda/envs/my_project/lib/python3.6/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /../.conda/envs/my_project/lib/python3.6/site-packages/faiss/_swigfaiss.so)
```

Any idea how to fix this issue?

**Comment by mlomeli1** [comment]
please follow the exact conda  install command as per the [INSTALL.md](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md)
