### ISSUE TITLE
Creating an array of faiss.Kmeans objects that uses gpu

### ISSUE THREAD

**Issue by FalsoMoralista** [facebookresearch/faiss#3491]
Context: I have a dataset with say 1.000 classes and I want to perform K-means with gpu over each class.
E.g. (sketch):
``` Python

class KMeansModule:
    
    def __init__(self, nb_classes, dimensionality=256, n_iter=10, k=5, max_iter=300):

        self.k = k
        self.d = dimensionality
        self.n_iter = n_iter
        self.n_kmeans = [faiss.Kmeans(d=dimensionality, k=k, niter=1, gpu=True, verbose=True) for _ in nb_classes]         


    def assign(self, x_i, y_i):
        # Train K-means model for one iteration to initialize centroids
        self.n_kmeans[y_i].train(x_i)
        # Assign vectors to the nearest cluster centroid
        D, I = self.n_kmeans[y_i].index.search(x_i, 1)
        return D, I

```
But then I came across into [this](https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU?fbclid=IwZXh0bgNhZW0CMTAAAR3Sfc4jQp3RZEUKUdAOsXcfc0OlhlLlKl2kxPQJG-pc8B71FPL7YBHqQRg_aem_AYSDKlDdlVDpSNmVp-hKCajFVRnw_n2S-OiYzkGBvRxNHJJi-PsdO4CKw0EoF4ou5fmk1WzM1-AIbw9ZrOFSMT8V) which states: 
"All GPU indexes are built with a StandardGpuResources object (which is an implementation of the abstract class GpuResources). The resource object contains needed resources for each GPU in use, including an allocation of temporary scratch space (by default, about 2 GB on a 12 GB GPU), cuBLAS handles and CUDA streams."

Therefore I was worried about running into memory issues considering that I will have one kmeans object for each class. Is there anyway to modify those settings? Should I be worried at all?

Suggestions are appreciated. Thanks in advance.

**Comment by mdouze** [comment]
You can share the `StandardGpuResources` over different GPU indexes and share the same GPU index across Kmeans indexes, so as long as you are not running them separately, you should be fine.

**Comment by FalsoMoralista** [comment]
I will try that, thank you for the attention.

**Comment by FalsoMoralista** [comment]
I tried the following:

```Python
class KMeansModule:

    def __init__(self, nb_classes, dimensionality=256, n_iter=10, k_range=[2,3,4,5], resources=None, config=None, max_iter=300):

        self.resources = resources
        self.config = config        
        self.index = faiss.GpuIndexFlatL2(resources, dimensionality, config)

        # Create the K-means object
        self.k_range = k_range
        self.d = dimensionality
        self.n_iter = n_iter
        
        if len(k_range) == 1:
            self.n_kmeans = [faiss.Kmeans(d=dimensionality, k=k_range[0], niter=1, verbose=True, min_points_per_centroid = 1 ) for _ in range(nb_classes)]   
        else:
            self.n_kmeans = []   
            #  For each class create a set of K-means (e.g., with k=2,3,4,5) objects 
            for _ in range(nb_classes):
                self.n_kmeans.append([faiss.Kmeans(d=dimensionality, k=k, niter=1, verbose=True, min_points_per_centroid = 1) for k in k_range])
            
            for cls in range(nb_classes):
                for k in range(len(k_range)):
                    self.n_kmeans[cls][k].index = self.index
```

Then when i do:

```Python
# Train K-means model for one iteration to initialize centroids
for k in range(len(self.k_range)):
    self.n_kmeans[y[i]][k].train(batch_x)

```

Then it seems to be trying to copy the tensor into cpu when i call the train method.

>   File "/home/rtcalumby/adam/luciano/LifeCLEFPlant2022/DeepCluster/src/KMeans.py", line 130, in assign
    self.n_kmeans[y[i]][k].train(batch_x)
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/extra_wrappers.py", line 544, in train
    x = np.ascontiguousarray(x, dtype='float32')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/torch/_tensor.py", line 1089, in __array__
    return self.numpy().astype(dtype, copy=False)
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by wickedfoo** [comment]
You seem to be passing a pytorch GPU tensor as input? You need to import faiss.contrib.torch_utils in order to allow this.

**Comment by FalsoMoralista** [comment]
Hi, thanks for replying but i was already importing faiss.contrib.torch_utils in the code, sorry for not mentioning it before.

**Comment by FalsoMoralista** [comment]
Tried importing faiss.contrib.torch_utils into faiss/extra_wrappers.py which generates the following: 
```
Traceback (most recent call last):
  File "/home/rtcalumby/adam/luciano/LifeCLEFPlant2022/DeepCluster/main_deeper_cluster.py", line 16, in <module>
    from engine_deeper_cluster import main as app_main
  File "/home/rtcalumby/adam/luciano/LifeCLEFPlant2022/DeepCluster/engine_deeper_cluster.py", line 64, in <module>
    from src import KMeans
  File "/home/rtcalumby/adam/luciano/LifeCLEFPlant2022/DeepCluster/src/KMeans.py", line 3, in <module>
    import faiss
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/__init__.py", line 22, in <module>
    from faiss.extra_wrappers import kmin, kmax, pairwise_distances, rand, randint, \
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/extra_wrappers.py", line 19, in <module>
    import faiss.contrib.torch_utils
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/contrib/torch_utils.py", line 493, in <module>
    handle_torch_Index(the_class)
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/contrib/torch_utils.py", line 469, in handle_torch_Index
    torch_replace_method(the_class, 'add', torch_replacement_add)
  File "/home/rtcalumby/miniconda3/envs/py382/lib/python3.12/site-packages/faiss/contrib/torch_utils.py", line 106, in torch_replace_method
    assert ignore_no_base or (orig_method.__name__ == 'replacement_' + name)
AssertionError
```
