### ISSUE TITLE
Faiss compatibility with NumPy 2 (ImportError: numpy.core.multiarray failed to import)

### ISSUE THREAD

**Issue by pdarulewski** [facebookresearch/faiss#3526]
# Summary

I'm not really sure if this is something on my side or Faiss but from the logs it looks like Faiss needs to be recompiled with the newest NumPy release. AFAIK, there are a couple of C API changes: https://numpy.org/doc/stable/release/2.0.0-notes.html

# Platform

OS: macOS 14.4.1 23E224 arm64

Faiss version: faiss-cpu==1.8.0

Installed from: pypi through poetry and pip

Faiss compilation options: none

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

 

To reproduce:
1. install numpy, faiss-cpu, packaging (apparently is required by faiss but it's not automatically installed by pip 24.0)
2. open REPL and import faiss

```
∇ python3.11 -m venv .venv
∇ source .venv/bin/activate
∇ pip install numpy faiss-cpu packaging
Collecting numpy
  Using cached numpy-2.0.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting faiss-cpu
  Using cached faiss_cpu-1.8.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.6 kB)
Collecting packaging
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Using cached numpy-2.0.0-cp311-cp311-macosx_14_0_arm64.whl (5.2 MB)
Using cached faiss_cpu-1.8.0-cp311-cp311-macosx_11_0_arm64.whl (3.1 MB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Installing collected packages: packaging, numpy, faiss-cpu
Successfully installed faiss-cpu-1.8.0 numpy-2.0.0 packaging-24.1
∇ python
Python 3.11.8 (main, Jun  7 2024, 13:22:20) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/loader.py", line 98, in <module>
    from .swigfaiss import *
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/swigfaiss.py", line 10, in <module>
    from . import _swigfaiss
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/loader.py", line 98, in <module>
    from .swigfaiss import *
  File "/Users/pd/utils/scratch/.venv/lib/python3.11/site-packages/faiss/swigfaiss.py", line 10, in <module>
    from . import _swigfaiss
ImportError: numpy.core.multiarray failed to import
```

**Comment by ydshieh** [comment]
Also see this in `transformers` CI while checking if it works with numpy v2

**Comment by mlomeli1** [comment]
hi @ydshieh, thank you for flagging. Just checking, if you installed faiss with pip, we don't support installation with pip. Could you try installing faiss with conda as per [INSTALL.md](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md) and let us know if there are still issues?

**Comment by ydshieh** [comment]
Hi @mlomeli1 Our currently CI environment doesn't have `conda` in it, and so far we are able to install and use `faiss-cpu` along with numpy < 2.0, but not with numpy 2.0.0.

Is there a plan to support numpy 2.0.0 (and ideally with pip install)?

**Comment by pdarulewski** [comment]
@mlomeli1 thanks, I didn't know that, sorry about that. Unfortunately, if I use conda, it fetches numpy 1.26.4 and numpy-base 1.26.4:

```
∇ conda install -c pytorch faiss-cpu=1.8.0
[...]

  added / updated specs:
    - faiss-cpu=1.8.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    [...]
    numpy-1.26.4               |  py312h7f4fdc5_0          12 KB
    numpy-base-1.26.4          |  py312he047099_0         6.3 MB

```

Then I can't install numpy 2.0 because of version conflicts:

```
numpy [2.0.0rc1|2.0.0rc2] would require
            └─ _numpy_rc, which does not exist (perhaps a missing channel);
[...]
numpy 2.0.0 conflicts with any installable versions previously reported;
```

@ydshieh There's an open issue already in `faiss-wheels` where faiss is published to pip: https://github.com/kyamagu/faiss-wheels/issues/104

**Comment by wencan** [comment]
@mlomeli1 

I have always used pip + venv. This combination has always worked well.

**Comment by ydshieh** [comment]
@pdarulewski But #104 and #105  mean, as long as we need to use faiss, we can't use numpy v2. I don't feel strong, but maybe at some point it's nice to make them compatible.

**Comment by mengdilin** [comment]
Heads up, it looks like faiss + numpy2.0 using conda installation is also not behaving as expected from https://github.com/facebookresearch/faiss/actions/runs/10117066685/job/27981278918?pr=3696 I will take a look

**Comment by shizhediao** [comment]
Mark it.

**Comment by volkov-maxim** [comment]
`pip install numpy==1.26.4` helps me twice (just I had forgot about first one 🤭)

**Comment by rafalh** [comment]
According to [numpy docs](https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice) building with numpy 2+ should result in packages compatible with both numpy 1.x and 2.x:

> When you build wheels for your package using a NumPy 2.x version at build time, those will work with NumPy 1.xx.

So I wonder why numpy version is still pinned to `<1` one year after numpy 2 release.

**Comment by mnorris11** [comment]
> According to [numpy docs](https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice) building with numpy 2+ should result in packages compatible with both numpy 1.x and 2.x:
> 
> > When you build wheels for your package using a NumPy 2.x version at build time, those will work with NumPy 1.xx.
> 
> So I wonder why numpy version is still pinned to `<1` one year after numpy 2 release.

Numpy2 did not work OOTB when I briefly tried it. I thought some code had to be updated.

Edit: I tried to just change the version, and these were the test errors: https://github.com/facebookresearch/faiss/actions/runs/16836126841/job/47695952460?pr=4523. Unfortunately don't have time to dig into it atm.

We definitely welcome contributions in this area. If anyone wants to create a PR to do the upgrade that passes the CI, we are happy to merge it.

Otherwise we hope to prioritize in Q4.

**Comment by mnorris11** [comment]
Aiming to upgrade in https://github.com/facebookresearch/faiss/pull/4523

After that merges, we will close this issue.

Note: numpy2 is definitely not a drop in replacement for numpy1, in that a few tests had to be adjusted in hacky ways. You may see some accuracy changes on various SIMD optimization levels. Windows especially now fails for a few more tests.

**Comment by cmacdonald** [comment]
Any news on the FAISS 1.13.0 release? Its really tiresome dealing with Numpy 1 mismatches, because every other platform upgraded to numpy 2 (torch, pandas, colab).

**Comment by mnorris11** [comment]
> Any news on the FAISS 1.13.0 release? Its really tiresome dealing with Numpy 1 mismatches, because every other platform upgraded to numpy 2 (torch, pandas, colab).

@cmacdonald it looks like the nightly failed. After that is green, we can start the 1.13.0 release process. ETA next week.

**Comment by cmacdonald** [comment]
thanks you @mnorris11 for so politely handling my frustration, great to hear its soon.
