### ISSUE TITLE
ImportError: /data01/user/xxx/tools/faiss/_swigfaiss.so: undefined symbol: dsyev_

### ISSUE THREAD

**Issue by carlislelee** [facebookresearch/faiss#370]
# Summary

# Platform

OS: CentOS 7.2

Faiss version: 8428f915484eff3f1e7ff4788494c2fcf403f1b0 

Faiss compilation options: 

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

Below is my error message:

Traceback (most recent call last):
  File "test_build_blocks.py", line 11, in <module>
    import faiss
  File "/data01/user/lizhaoxi/tools/faiss/faiss.py", line 28, in <module>
    from swigfaiss import *
  File "/data01/user/lizhaoxi/tools/faiss/swigfaiss.py", line 26, in <module>
    _swigfaiss = swig_import_helper()
  File "/data01/user/lizhaoxi/tools/faiss/swigfaiss.py", line 22, in swig_import_helper
    _mod = imp.load_module('_swigfaiss', fp, pathname, description)
ImportError: /data01/user/xxx/tools/faiss/_swigfaiss.so: undefined symbol: dsyev_

I've read issue 256, but it doesn't work for me.

First, I compiled openblas from source and linked /usr/lib64/libopenblas.so to /opt/OpenBLAS/lib/libopenblas_haswellp-r0.3.0.dev.so

Then I ran 'make' without any options, and then ran 'make py', get no error msg during the process.

But when I ran tests or "python -c 'import faiss'", I got error above.

Please help me, thx

**Comment by carlislelee** [comment]
Just solved, the problem is I didn't export env:
export LD_LIBRARY_PATH={openblas lib dir}
export PYTHONPATH={faiss install dir}:$PYTHONPATH
