### ISSUE TITLE
ImportError: No module named faiss

### ISSUE THREAD

**Issue by BondJYC** [facebookresearch/faiss#41]
i have a problem when i follow the install steps of faiss in step 2

```
Real-life test
--------------

The following script extends the demo_sift1M test to several types of
indexes:

  python python/demo_auto_tune.py

It will cycle through a few types of indexes and find optimal
operating points. You can play around with the types of indexes.
```

i get the information about this.

```
python python/demo_auto_tune.py
Traceback (most recent call last):
  File "python/demo_auto_tune.py", line 19, in <module>
    import faiss
ImportError: No module named faiss
```

thank you for your help!

**Comment by mdouze** [comment]
Please do

export PYTHONPATH=.

because faiss.py is in the current directory.

**Comment by BondJYC** [comment]
thanks~

**Comment by BondJYC** [comment]
Dear contributor,i encountered another problem in step 2.
after using the command  `export PYTHONPATH=.`
this command `python python/demo_auto_tune.py` can be executed
however at the end of execution,it reports a error like below:
```
cno=12 key=nprobe=4096 perf=0.9870 t=11.214 
Traceback (most recent call last):
  File "python/demo_auto_tune.py", line 168, in <module>
    fig.savefig('tmp/demo_auto_tune.png')
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2220, in print_figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 510, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: 'tmp/demo_auto_tune.png'
```
i don't know whether this problem is due to the matplotlib module of python.
thank you for your patient reply!
