### ISSUE TITLE
demo_auto_tune.py Number of training points (100000) should be at least as large as number of clusters (1048576)

### ISSUE THREAD

**Issue by dracoshield** [facebookresearch/faiss#414]
Hi
I got errors while running demos/demo_auto_tune.py

`
Traceback (most recent call last):
File "demos/demo_auto_tune.py", line 142, in <module>
index.train(xt)
File "/faiss/faiss.py", line 112, in replacement_train
self.train_c(n, swig_ptr(x))
File "/faiss/swigfaiss_gpu.py", line 4695, in train
return _swigfaiss_gpu.GpuIndexIVFFlat_train(self, n, x)
RuntimeError: Error in virtual void faiss::Clustering::train(faiss::Clustering::idx_t, const float*, faiss::Index&) at Clustering.cpp:70: Error: 'nx >= k' failed: Number of training points (100000) should be at least as large as number of clusters (1048576)
`

Running on :
- [ ] CPU
- [x] GPU

**Comment by mdouze** [comment]
No activity, closing.

**Comment by wongdu** [comment]
i also got this error!when i running on cpu architecture:

RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at Clustering.cpp:273: Error: 'nx >= k' failed: Number of training points (796) should be at least as large as number of clusters (1024)

**Comment by wongdu** [comment]
after change another pic,the error message disappeared.

**Comment by sgavela** [comment]
I have exactly the same issue
