### ISSUE TITLE
Anaconda macOS CPU version requires libomp

### ISSUE THREAD

**Issue by fibigerg** [facebookresearch/faiss#433]
# Summary

# Platform

OS: macOS 10.13.4

Faiss version: faiss-cpu: 1.2.1-py36_cuda0.0_1 pytorch

Faiss compilation options: anaconda version

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

Just installed cpu variant via Anaconda, import fails.

```
conda install faiss-cpu -c pytorch
Solving environment: done

## Package Plan ##

  environment location: /usr/local/anaconda3

  added / updated specs:
    - faiss-cpu


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    faiss-cpu-1.2.1            |   py36_cuda0.0_1         703 KB  pytorch

The following NEW packages will be INSTALLED:

    faiss-cpu: 1.2.1-py36_cuda0.0_1 pytorch

Proceed ([y]/n)? y


Downloading and Extracting Packages
faiss-cpu 1.2.1################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
 ~  python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/faiss/__init__.py", line 21, in <module>
    from .swigfaiss_gpu import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/usr/local/anaconda3/lib/python3.6/site-packages/faiss/_swigfaiss.so, 2): Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /usr/local/anaconda3/lib/python3.6/site-packages/faiss/_swigfaiss.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/faiss/__init__.py", line 28, in <module>
    from .swigfaiss import *
  File "/usr/local/anaconda3/lib/python3.6/site-packages/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/local/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_swigfaiss'
>>>
```

I was able to fix this simple by running `brew install libomp`. You might want to add this to dependancies in INSTALL.md.

**Comment by chenxingqiang** [comment]
thanks，very on time!

**Comment by NLPpupil** [comment]
thank you very much, it works for me
