### ISSUE TITLE
[docker deploy] Dockerfile compiling problem

### ISSUE THREAD

**Issue by alues** [facebookresearch/faiss#491]
# Summary

# Platform

OS: *`docker`*-> `nvidia/cuda:8.0-devel-ubuntu16.04`

Faiss version: [faiss:master](https://github.com/facebookresearch/faiss/commit/dd6c9ebf2da3123e055ffdc99f9b597e8b97de04)

Faiss compilation options: 
```bash
./configure && \
    make -j $(nproc) && \
    make -j $(nproc) -C gpu && \
    make -j $(nproc) -C python gpu && \
    make -j $(nproc) -C python build && \
    make -j $(nproc) -C python install
```
Running on :
- [x] CPU
- [x] GPU

# Reproduction instructions
`python -c "import _swigfaiss_gpu"` in faiss's python folder
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./_swigfaiss_gpu.so: undefined symbol: omp_set_lock
```

how can i fix it?

**Comment by beauby** [comment]
Could you post the output of `./configure`?

**Comment by alues** [comment]
```bash
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features with -std=c++11... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for python... python
checking for python-config... python-config
checking for Python C flags... -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7
checking for Python ld flags... -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking for numpy headers path... /usr/lib/python2.7/dist-packages/numpy/core/include
checking for swig... swig
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for nvcc... /usr/local/cuda/bin/nvcc
checking cuda.h usability... yes
checking cuda.h presence... yes
checking for cuda.h... yes
checking for cuInit in -lcuda... yes
checking for cublasAlloc in -lcublas... yes
checking for cudaSetDevice in -lcudart... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for inline... inline
checking for int32_t... yes
checking for int64_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for clock_gettime... yes
checking for floor... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for munmap... yes
checking for pow... yes
checking for sqrt... yes
checking for strerror... yes
checking for strstr... yes
checking for g++ -std=c++11 option to support OpenMP... -fopenmp
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if sgemm_ is being linked in already... no
checking for sgemm_ in -lmkl_intel_lp64... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -lopenblas... yes
checking for cheev_... yes
configure: creating ./config.status
config.status: creating makefile.inc
```

**Comment by beauby** [comment]
Could you try doing `./configure LIBS=-lgomp` and then re-building and doing `python -c "import _swigfaiss_gpu"`?

**Comment by alues** [comment]
new err with `./configure   ##LIBS=-lgomp` @beauby 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./_swigfaiss_gpu.so: undefined symbol: ssyrk_
```

**Comment by alues** [comment]
any progress for this issues?

**Comment by alues** [comment]
[issues #500 ](https://github.com/facebookresearch/faiss/issues/500)
[issues #494 ](https://github.com/facebookresearch/faiss/issues/494)
@beauby will this problem be resolved?

**Comment by mdouze** [comment]
@pletessier, any comment?

**Comment by pletessier** [comment]
I will get on to this and see what I can do @mdouze, but I will probably not be available before a week.

**Comment by mdouze** [comment]
I assume it's fixed. Closing.
