### ISSUE TITLE
faiss(python) can only run in faiss/python directory

### ISSUE THREAD

**Issue by danny1984** [facebookresearch/faiss#522]
# Summary

I compile faiss sources. Now it can only run in XX/faiss/python/  directory. 
When I run other directories, it outputs as follow

------------------

python -c "import faiss"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/faiss/__init__.py", line 28, in <module>
    from .swigfaiss import *
  File "/root/anaconda2/lib/python2.7/site-packages/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/root/anaconda2/lib/python2.7/site-packages/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/root/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swigfais

------------------

In my install directory "faiss/python/", it has already outputed _swigfaiss.so. 

I think maybe in other directories, it cannot find _swigfaiss.so when importing. 
I am a python fresher, and do not know how to solve this problem.
I hope faiss can be imported in any directory.
 

# Platform
Ubuntu 16.0

Running on:
- [√ ] CPU

Interface: 
- [ √] Python

# Reproduction instructions
------------------------
I have tried following commands, "make py " in "faiss" directory, and "python setup.py install && make install " in "faiss/python" directory.  the output is 

python setup.py build
running build
running build_py
copying faiss/__init__.py -> build/lib/faiss
copying faiss/swigfaiss.py -> build/lib/faiss
copying faiss/_swigfaiss.so -> build/lib/faiss
python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to faiss.egg-info/requires.txt
writing faiss.egg-info/PKG-INFO
writing top-level names to faiss.egg-info/top_level.txt
writing dependency_links to faiss.egg-info/dependency_links.txt
reading manifest file 'faiss.egg-info/SOURCES.txt'
writing manifest file 'faiss.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/faiss
copying build/lib/faiss/__init__.py -> build/bdist.linux-x86_64/egg/faiss
copying build/lib/faiss/swigfaiss.py -> build/bdist.linux-x86_64/egg/faiss
copying build/lib/faiss/_swigfaiss.so -> build/bdist.linux-x86_64/egg/faiss
byte-compiling build/bdist.linux-x86_64/egg/faiss/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/faiss/swigfaiss.py to swigfaiss.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying faiss.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying faiss.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying faiss.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying faiss.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying faiss.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
faiss.swigfaiss: module references __file__
creating 'dist/faiss-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing faiss-0.1-py2.7.egg
removing '/root/anaconda2/lib/python2.7/site-packages/faiss-0.1-py2.7.egg' (and everything under it)
creating /root/anaconda2/lib/python2.7/site-packages/faiss-0.1-py2.7.egg
Extracting faiss-0.1-py2.7.egg to /root/anaconda2/lib/python2.7/site-packages
faiss 0.1 is already the active version in easy-install.pth

Installed /root/anaconda2/lib/python2.7/site-packages/faiss-0.1-py2.7.egg
Processing dependencies for faiss==0.1
Searching for numpy==1.11.3
Best match: numpy 1.11.3
Adding numpy 1.11.3 to easy-install.pth file

Using /root/anaconda2/lib/python2.7/site-packages
Finished processing dependencies for faiss==0.1

-------------------------

**Comment by beauby** [comment]
Unless you have specific needs, I would advise to install the binary version available on conda (`conda install faiss-cpu` / `conda install faiss-gpu`).

Also, could you provide the content of your `makefile.inc`?

**Comment by msharmavikram** [comment]
I see the same error. I believe python interface was working before. One of the latest commits has screwed it up. 


```
# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD+Patents license found in the
# LICENSE file in the root directory of this source tree.

CXX          = g++ -std=c++11
CXXCPP       = g++ -std=c++11 -E
# TODO: Investigate the LAPACKE wrapper for LAPACK, which defines the correct
#   type for FORTRAN integers.
CPPFLAGS     = -DFINTEGER=int
CXXFLAGS     = -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra
CPUFLAGS     = -msse4 -mpopcnt
LDFLAGS      = -fopenmp
LIBS         = -lopenblas
PYTHONCFLAGS = -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include

NVCC         = /usr/local/cuda/bin/nvcc
NVCCLDFLAGS  = -L/usr/local/cuda/lib64
NVCCLIBS     = -lcudart -lcublas -lcuda
CUDAROOT     = /usr/local/cuda
CUDACFLAGS   = -I/usr/local/cuda/include
NVCCFLAGS    = -I $(CUDAROOT)/targets/x86_64-linux/include/ \
-Xcompiler -fPIC \
-Xcudafe --diag_suppress=unrecognized_attribute \
-gencode arch=compute_35,code="compute_35" \
-gencode arch=compute_52,code="compute_52" \
-gencode arch=compute_60,code="compute_60" \
-gencode arch=compute_61,code="compute_61" \
-lineinfo \
-ccbin $(CXX) -DFAISS_USE_FLOAT16

OS = $(shell uname -s)

SHAREDEXT   = so
SHAREDFLAGS = -shared

ifeq ($(OS),Darwin)
        SHAREDEXT   = dylib
        SHAREDFLAGS = -dynamiclib -undefined dynamic_lookup
endif

MKDIR_P      = /bin/mkdir -p
PYTHON       = python
SWIG         = swig

prefix      ?= /usr/local
exec_prefix ?= ${prefix}
libdir       = ${exec_prefix}/lib
includedir   = ${prefix}/include

```

**Comment by msharmavikram** [comment]
The can be fixed with below environment addition.

`export PYTHONPATH=$PYTHONPATH:/opt/faiss/python`

**Comment by mdouze** [comment]
No activity, closing.
