### ISSUE TITLE
failed: read error

### ISSUE THREAD

**Issue by reshu-b7** [facebookresearch/faiss#555]
I am trying to run faiss search on a big data set having 79241051 vectors of 64 dimension using the [bench_gpu_1bn.py](https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_1bn.py) scrpit . I am running it on 4 P40 Tesla GPUs and have been receiving this error but couldn't understand what could have been causing this. I am able to run the same for IVF4096,Flat and combination of IVF,PQ

`python bench_gpu.py big_data IVF16384,Flat -nnn 100 -ngpu 4 -altadd -noptables -tempmem $[2*1024*1024*1024] `

```
$[4*1024*1024*1024] -qbs 100000 -float16
Preparing dataset big_data
preparing base and learning set
preparing query set
preparing ground truth
sizes: B (79241051, 64) Q (100000, 64) T (79241051, 64) gt (100000, 100)
cachefiles:
None
/data/index/new/cent_big_data_IVF16384.npy
/data/index/new/big_data_IVF16384,Flat.index
preparing resources for 4 GPUs
load /data/index/new/big_data_IVF16384,Flat.index
Traceback (most recent call last):
  File "bench_gpu.py", line 789, in <module>
    index = get_populated_index(preproc)
  File "bench_gpu.py", line 669, in get_populated_index
    indexall = faiss.read_index(index_cachefile)
RuntimeError: Error in faiss::InvertedLists* faiss::read_InvertedLists(faiss::IOReader*, int) at index_io.cpp:613: Error: 'ret == (n * ails->code_size)' failed: read error

```

**Comment by mdouze** [comment]
It seems that the file /data/index/new/big_data_IVF16384,Flat.index is corrupted. Please erase it and try again.

**Comment by reshu-b7** [comment]
I tried creating and saving the .index and cent.npy file in a new folder, for IVF16384,Flat for GPU experiments, and it seemed to work. But when I run IVF4096,PQ or IVF16384,PQ experiments with the same script with cache files saved afresh, I get the following results. **Note that this is only the case for GPU implementation (bench_gpu_1bn.py) and things work perfectly for the CPU.**   


```
0/100000 (0.012 s)      probe=1  : 0.011 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.009 s)      probe=2  : 0.009 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.027 s)      probe=4  : 0.010 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.024 s)      probe=8  : 0.013 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.041 s)      probe=16 : 0.016 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.007 s)      probe=32 : 0.021 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.016 s)      probe=64 : 0.033 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.027 s)      probe=128: 0.061 ms   1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
0/100000 (0.019 s)      probe=256: 0.111 ms    1-R@1: 0.0000 1-R@10: 0.0000 1-R@100: 0.0000
```

**Comment by mdouze** [comment]
What about erasing the ground-truth cache as well?

**Comment by mdouze** [comment]
no activity, closing.
