### ISSUE TITLE
Python module error: 'GpuResourcesVector' is not defined

### ISSUE THREAD

**Issue by sicksick** [facebookresearch/faiss#591]
# Summary

when trying to execute script
```python
import faiss                     

m = 32                             
d = 2048
nlist = 100
ngpus = faiss.get_num_gpus()
print("number of GPUs:", ngpus)

quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)

gpu_index = faiss.index_cpu_to_all_gpus(  
    index
)
```

getting next error
```
Traceback (most recent call last):
  File "faisser.py", line 43, in <module>
    index
  File "/opt/anaconda/lib/python3.6/site-packages/faiss/__init__.py", line 408, in index_cpu_to_all_gpus
    index2 = index_cpu_to_gpu_multiple_py(res, index, co)
  File "/opt/anaconda/lib/python3.6/site-packages/faiss/__init__.py", line 395, in index_cpu_to_gpu_multiple_py
    vres = GpuResourcesVector()
NameError: name 'GpuResourcesVector' is not defined
```

# Platform

OS: Arch Linux

Faiss version: e57270600a49fea2f7e86a7214755c4721be6602, `conda faiss-gpu`

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by beauby** [comment]
What does `faiss.get_num_gpus()` report?

**Comment by sicksick** [comment]
0

**Comment by beauby** [comment]
This looks like you have the CPU-only version installed (or maybe both the `faiss-cpu` and `faiss-gpu` packages, which might create a conflict).

**Comment by mdouze** [comment]
No activity. Closing.
