### ISSUE TITLE
ubuntu 16.04 No module named _swigfaiss

### ISSUE THREAD

**Issue by wangchengb** [facebookresearch/faiss#601]
# Summary

conda install faiss-cpu -c pytorch -n mxnet

(mxnet) wangc@wangc-vm:~/Video$ python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangc/.conda/envs/mxnet/lib/python2.7/site-packages/faiss/__init__.py", line 28, in <module>
    from .swigfaiss import *
  File "/home/wangc/.conda/envs/mxnet/lib/python2.7/site-packages/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/wangc/.conda/envs/mxnet/lib/python2.7/site-packages/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/home/wangc/.conda/envs/mxnet/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swigfaiss

# Platform

OS: ubuntu 16.04

Running on:
- [x] CPU

Interface: 
- [x] Python

**Comment by wangchengb** [comment]
my envs is not install "mkl", after "pip install mkl", faiss is successful.

**Comment by beauby** [comment]
Glad to hear. Anaconda should install mkl as a dependency though.

**Comment by mdouze** [comment]
No activity. Closing.
