### ISSUE TITLE
Related errors encountered in reproducing data from papers

### ISSUE THREAD

**Issue by ahappycutedog** [facebookresearch/faiss#613]
# Summary

1.  In the Experiments on 1B elements dataset,  run the script for bench_polysemous_1bn.py ( python bench_polysemous_1bn.py SIFT1000M IMI2x12,PQ16 nprobe=16,max_codes={10000,30000},ht={44..54}) 
the following error has occurred:

File "bench_polysemous_1bn.py", line 175
    lambda (i0,i1): x[i0:i1].astype('float32').copy(),
           ^
SyntaxError: invalid syntax
 
2. Then I modified 175 lines：
  lambda (i0,i1): x[i0:i1].astype('float32').copy(), >>>>>>>  lambda i0,i1: x[i0:i1].astype('float32').copy(),

This error is solved and the data training take 277 seconds, but there is another error:

Traceback (most recent call last):
  File "bench_polysemous_1bn.py", line 208, in <module>
    index = get_populated_index()
  File "bench_polysemous_1bn.py", line 188, in get_populated_index
    for xs in matrix_slice_iterator(xb, 100000):
  File "bench_polysemous_1bn.py", line 163, in rate_limited_imap
    yield res.get()
  File "/home/hj/anaconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/home/hj/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
TypeError: <lambda>() missing 1 required positional argument: 'i1'

I looked at the code and didn't find a solution.

# Platform

ubuntu 16.04
Faiss install:   conda

Running on:
CPU

Interface: 
 Python(3.5)

**Comment by mdouze** [comment]
The code is written for Python 2.

**Comment by ahappycutedog** [comment]
> The code is written for Python 2.

OK, I have rewritten it in Python 3. But I have been facing an issue while running the bench_gpu_1bn.py on SIFT1B dataset.  My script is running on GTX1080 Ti with 10GB memory .  

The details are as follows:
hj@yanfa:~/smbshare/wf/wang_test/faiss/faiss_test$ python bench_gpu_1bn.py SIFT1000M OPQ8_32,IVF262144,PQ8 -nnn 10 -ngpu 1 -tempmem $[2048*1024*1024]
Preparing dataset SIFT1000M
sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)
cachefiles:
/tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans
/tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy
/tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index
preparing resources for 1 GPUs
load /tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans
load centroids /tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy
making an IVFPQ index, m =  8
Training vector codes
  done 72.097 s
  IndexIVFPQ size 0 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=1 useFloat16=0 reserveVecs=1000000000
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:19; details: Failed to cudaMalloc 30512 bytes
Aborted (core dumped)

Is this reason for insufficient memory? Would appreciate your any suggestion.

**Comment by mdouze** [comment]
see: 
https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#limitations
for options to reduce GPU mem usage.

**Comment by mdouze** [comment]
no activity, closing.
