### ISSUE TITLE
'GpuIndexIVFPQ' object has no attribute 'at'

### ISSUE THREAD

**Issue by PsLink** [facebookresearch/faiss#623]
# Summary

When I try to run the bench_gpu_1bn.py for sift1000m, encounter this issue during add.. 

# Platform

OS: 

CentOS 7.4.1708

Faiss version: 

commit 87721af

Faiss compilation options: 

default

Running on:
- [v] CPU
- [v] GPU

Interface: 
- [ ] C++
- [v] Python

# Reproduction instructions

when I set the -max_add parameters, encouter the following problem.

Traceback (most recent call last):
  File "bench_gpu_1bn.py", line 750, in <module>
    index = get_populated_index(preproc)
  File "bench_gpu_1bn.py", line 622, in get_populated_index
    gpu_index, indexall = compute_populated_index(preproc)
  File "bench_gpu_1bn.py", line 538, in compute_populated_index
    index_src_gpu = faiss.downcast_index(gpu_index.at(i))
  File "/home/pingyi/exp/FAISS/faiss/python/faiss/swigfaiss_gpu.py", line 5134, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, GpuIndexIVFPQ, name)
  File "/home/pingyi/exp/FAISS/faiss/python/faiss/swigfaiss_gpu.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'GpuIndexIVFPQ' object has no attribute 'at'

**Comment by mdouze** [comment]
no activity, closing.
