### ISSUE TITLE
Error while setting nprobe with IndexShards->IndexIDMap2->IndexIVFFlat

### ISSUE THREAD

**Issue by bvarghese1** [facebookresearch/faiss#671]
# Summary
Unable to increase the nprobe during search time. I am using an IndexShards with IndexIDMap2. The IndexIDMap2 points to an IndexIVFFlat. I am using an IndexShards without successive ids and IndexIDMap2 because I want to have random access to non consecutive ids.

# Platform

OS: macOS 10.13.6

Faiss version: 

Faiss compilation options: 

Running on:
- [Y ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [Y] Python

# Reproduction instructions

```
INDEX_PATH = '/data/faiss'
meta_index = faiss.IndexShards(D, True, False)
trained_index = faiss.index_factory(D, "IVF10000,Flat")
trained_index.train(embeddings.astype('float32'))
faiss.write_index(trained_index, os.path.join(INDEX_PATH, 'train_ivf.index'))
sub_index = faiss.read_index(INDEX_PATH + '/train_ivf.index')
sub_index.make_direct_map(True)
index_map = faiss.IndexIDMap2(sub_index)
ids = np.arange(i, i + 1000000)
index_map.add_with_ids(embeddings.astype('float32'), ids)
meta_index.add_shard(index_map)

# **Search meta_index WORKS**
idx = 124
start = time.time()
response = meta_index.search(np.reshape(embeddings[idx], (1, 512)).astype('float32'), 5)
end = time.time()
print (response)
print ("Search for 1 query took {} milliseconds".format((end - start) * 1000))

# **Increasing n_probe on the IndexShards(meta_index) FAILS**
faiss.ParameterSpace().set_index_parameter(meta_index, "nprobe", 4) # sets the nprobe for each shard

# **Increasing n_probe on a particular shard also FAILS**
faiss.ParameterSpace().set_index_parameter(meta_index.at(0), "nprobe", 4) # sets the nprobe for each shard
```
**Error Observed**
```
Traceback (most recent call last):
  File "faiss_shard_reconstruct.py", line 38, in <module>
    faiss.ParameterSpace().set_index_parameter(meta_index.at(i), "nprobe", i) # sets the nprobe for each shard
  File "/home/bonnie/.conda/envs/py36/lib/python3.6/site-packages/faiss/swigfaiss.py", line 4922, in set_index_parameter
    return _swigfaiss.ParameterSpace_set_index_parameter(self, index, name, val)
RuntimeError: Error in virtual void faiss::ParameterSpace::set_index_parameter(faiss::Index*, const string&, double) const at AutoTune.cpp:538: ParameterSpace::set_index_parameter:could not set parameter nprobe
```

Looking through the FAISS code, I found this 
https://github.com/facebookresearch/faiss/blob/master/AutoTune.cpp#L468
and
https://github.com/facebookresearch/faiss/blob/master/AutoTune.cpp#L490
It loops through each shard and invokes its set_index_parameter. However, the type is not IndexIVF. Do you think adding the following will do the trick?
```
    if (name == "nprobe") {
        if (DC(IndexIDMap)) {
            set_index_parameter (ix->index, name, val);
        } else if (DC(IndexIVF)) {
            ix->nprobe = int(val);
            return;
        }
    }
```
Or is there some workaround for this?

**Comment by mdouze** [comment]
It is true that the ParameterSpace object does not support all types of indexes. 
Could you make a PR with this change?

**Comment by bvarghese1** [comment]
@mdouze Sure, I will.
