### ISSUE TITLE
make py  error

### ISSUE THREAD

**Issue by xxllp** [facebookresearch/faiss#674]
on   centos  + anconda 3.6

> make -C python build
make[1]: Entering directory `/home/mlp/faiss/python'
swig -python -c++ -Doverride= -I../ -o swigfaiss_wrap.cpp swigfaiss.swig
../IndexIVF.h:263: Error: Syntax error in input(3).
make[1]: *** [swigfaiss_wrap.cpp] Error 1
make[1]: Leaving directory `/home/mlp/faiss/python'
make: *** [py] Error 2

**Comment by xxllp** [comment]
after all 
import faiss   get error 
Traceback (most recent call last):
  File "/home/mlp/faiss/python/swigfaiss_gpu.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/mlp/python/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_swigfaiss_gpu'
