### ISSUE TITLE
Conda install causes ModuleNotFoundError: No module named '_swigfaiss'

### ISSUE THREAD

**Issue by alexwms** [facebookresearch/faiss#708]
# Summary
See below for reproduction instructions. This issue is similar to other tickets that have been closed. I followed the advice on those tickets, but was not able to make the error go away.

# Platform

OS: macOS 10.14.2 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU

Interface: 
- [ ] Python

# Reproduction instructions

I installed faiss using conda with the following command: `conda install faiss-cpu -c pytorch`
Previous to installing faiss I ran: 
`conda install mkl`
`brew install llvm`
`brew install libomp`
All of these were installed successfully

I get the following error:

Traceback (most recent call last):
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/__init__.py", line 21, in <module>
    from .swigfaiss_gpu import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: dlopen(/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/_swigfaiss.so, 2): Symbol not found: _mkl_blas_caxpy
  Referenced from: /Users/alex/anaconda/envs/snakes/lib/libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /Users/alex/anaconda/envs/snakes/lib/libmkl_intel_lp64.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/projectname/filename.py", line 4, in <module>
    import faiss
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/__init__.py", line 28, in <module>
    from .swigfaiss import *
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/site-packages/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/Users/alex/anaconda/envs/snakes/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_swigfaiss'

Process finished with exit code 1

**Comment by beauby** [comment]
Could you try it in a fresh conda env?

**Comment by mdouze** [comment]
no activity, closing.

**Comment by visionscaper** [comment]
@mdouze The problem is (for faiss) that @alexwms is using Python3.6. [python/faiss.py](https://github.com/facebookresearch/faiss/blob/master/python/faiss.py), checks for the `ImportError` exception, not the `ModuleNotFoundError` exception that is thrown in Python3.6. Because of this the CPU version is not imported.

I would suggest to update the code in `python/faiss.py` as follows:

```
try:
    from swigfaiss_gpu import *
except Exception as e:

    # To support both Python 2.x and Python 3.x
    error_description = str(e)
    if 'No module named' not in error_description:
        # swigfaiss_gpu is there but failed to load: Warn user about it.
        sys.stderr.write("Failed to load GPU Faiss: %s\n" % error_description)
        sys.stderr.write("Faiss falling back to CPU-only.\n")

        # only import in case of import failure
        from swigfaiss import *
```

Let me know what you think.

**Comment by mullerhai** [comment]
BEST PRACTICE

IF  you use conda  virtual env,meet this error ,maybe your env  has been  polluted,you need destory it  or  rename  clone it ,

conda create -n new_env--clone old_env
conda deactivate 
conda remove -n old_env --all

conda create  -n old_env python=3.6.8 pip
conda activate old_env 
if you use centos7 
yum install swig pcre g++
 if you has use conda install swig ,meet error ,maybe  yum install swig is  best 
conda install faiss-cpu -c pytorch
or 
 conda install faiss-cpu=1.4.0 -c pytorch
if  you  has meet 
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so
ImportError: libmkl_gnu_thread.so: cannot open shared object file: No such file or directory

maybe you need  add mkl to  system path
export PATH=$PATH:/root/anaconda/pkgs/

use  anaconda instead of miniconda is best ,miniconda  is thin  ,maybe not has some package

there also are some other   solution
yum install swig pcre g++
conda install openblas swig mkl

conda install faiss-cpu -c pytorch

 conda install faiss-cpu=1.4.0 -c pytorch

Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so

conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service

conda update numpy
