### ISSUE TITLE
How to use compute_distance_subset

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#721]
*Received by e-mail*

I'm working on a similarity search project, and I'm really excited about the faiss project, and noticed your contact info in the repo. I'm working with the python bindings, and I'm trying to figure out how to get my inputs into the right shapes for the `IndexFlatL2.compute_distance_subset` method, and make sure I'm using the right method.

My goal is to get the L2 distances from a single query vector to some specific indices in the `IndexFlatL2`. I thought that the `compute_distance_subset` might be the right function to do so, and it looks like the parameters are (n, x, k, distances, labels), and I thought that `n` was the number of query vectors, `x` was the (n, d) set of query vectors, `k` was the number of indices to query against, I don't know what distance is, and labels is a list of indices to calculate distance against. If I have a vector, `x = np.array([[1, 1, 1, 1]])`, and I want to calculate the distance against indices `labels = [4, 7, 11]`, I would call `index.compute_distance_subset(1, x, 3, ?, labels)`, because there is one query vector and three labels to query against. I've tried passing integers, floats, lists, numpy arrays of size 1 x 3 as distances, but I keep getting the following error:

```
Traceback (most recent call last):
  File "/home/theaustinator/miniconda/envs/insight_2/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ec01f26418c2>", line 1, in <module>
    index_dict[layer_name].compute_distance_subset(1, gram, 3, 0, [3, 5, 7])
  File "/home/theaustinator/miniconda/envs/insight_2/lib/python3.6/site-packages/faiss/swigfaiss.py", line 2001, in compute_distance_subset
    return _swigfaiss.IndexFlat_compute_distance_subset(self, n, x, k, distances, labels)
TypeError: in method 'IndexFlat_compute_distance_subset', argument 3 of type 'float const *'
```

I looked at the source code, which eventually led me to fvec_inner_products_by_idx , but I don't know C++ and had a hard time understanding it. I apologize for the probably trivial question, but If you could provide any help, that would be greatly appreciated. I appreciate all your hard work on the repo, and am excited to get this working!

**Comment by mdouze** [comment]
For all low-level accesses to C++ functions, the arrays must be converted with `faiss.swig_ptr`.

Here is an example that works: https://gist.github.com/mdouze/57e11ea0acbf576f173a46e3e408af90

**Comment by mdouze** [comment]
No activity, closing.

**Comment by pedrocolon93** [comment]
Dunno if this will help anyone but found this nice article on how to use it:
https://memotut.com/a-little-niche-feature-introduction-of-faiss-2367b/
