### ISSUE TITLE
Support for 2080ti

### ISSUE THREAD

**Issue by LinXiLuo** [facebookresearch/faiss#748]
# Summary
Does faiss support for 2080ti? 

# Platform

cluster with 8 2080ti

OS: Ubuntu 18.10

cuda:9.0

python:3.6/2.7

Faiss version: faiss-gpu 1.5.0

Faiss compilation options: conda

Running on:
- [x] GPU

Interface: 
- [x] Python

# Reproduction instructions
 conda install successfully
import faiss successfully
however
run: faiss.get_num_gpus()
got: 0
run: faiss.StandardGpuResources()
got: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'StandardGpuResources'

**Comment by beauby** [comment]
@LinXiLuo Would you mind posting the full stacktrace?

**Comment by LinXiLuo** [comment]
Only those Traceback as I post.

**Comment by mdouze** [comment]
No activity, closing.

**Comment by bharathichezhiyan** [comment]
I also have the same problem. @mdouze  why are you closing the issues without giving proper answer.
>>> import faiss
Loading faiss with AVX2 support.
>>> res = faiss.StandardGpuResources()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'faiss' has no attribute 'StandardGpuResources'
>>>
