### ISSUE TITLE
How to use the IndexLSH with python

### ISSUE THREAD

**Issue by UpCoder** [facebookresearch/faiss#856]
Hi, I want to use the LSH index. But, there is a very few information.
When I use the code to build the Index, 
```python
    import faiss
    lshIndex = faiss.IndexLSH(num_dimension, num_bits)
    print np.shape(features), len(features)
    lshIndex.add(len(features), features)
```
It alway occur a like this:
```python
Traceback (most recent call last):
  File "/mnt/cephfs_wj/vc/liangdong.tony/PycharmProjects/RetrievalCCWebVideo/LSH/main.py", line 53, in <module>
    lshIndex.train(len(features), features)
TypeError: replacement_train() takes exactly 2 arguments (3 given)
```
If I delete the first parameters, like this
```python
lshIndex.add(features)
```
it will occur this error:
```python
Traceback (most recent call last):
  File "/mnt/cephfs_wj/vc/liangdong.tony/PycharmProjects/RetrievalCCWebVideo/LSH/main.py", line 54, in <module>
    lshIndex.add(features)
  File "/data00/home/liangdong.tony/anaconda2/lib/python2.7/site-packages/faiss/__init__.py", line 94, in replacement_add
    self.add_c(n, swig_ptr(x))
  File "/data00/home/liangdong.tony/anaconda2/lib/python2.7/site-packages/faiss/swigfaiss.py", line 2284, in add
    return _swigfaiss.IndexLSH_add(self, n, x)
TypeError: in method 'IndexLSH_add', argument 3 of type 'float const *'
```
So, do you know how to fix it?
Thanks!

**Comment by UpCoder** [comment]
I fixed it by this code:
```python
     import faiss
    lshIndex = faiss.IndexLSH(num_dimension, num_bits)
    print np.shape(features), len(features)
    # lshIndex.add(len(features), features)
    # lshIndex.add(np.ascontiguousarray(features))
    input_features = np.ascontiguousarray(np.asarray(features, "float32"))
    lshIndex.add(input_features)
    print lshIndex.search(np.asarray([input_features[0]], "float32"), 10)
```
but how to point the distance function? such as hamming distance?

**Comment by beauby** [comment]
@UpCoder `IndexLSH` uses Hamming distance, there is nothing special to do.

**Comment by chikubee** [comment]
@beauby Is there a way to check how many elements have similar hashes. Just thinking of a condition if there are say 20 samples on "sofware" and 1 on "cat" and if the query is software relevant this will be a brute force match with 20 samples due to similar hash. Is there some way to configure nlist like in the others., for keeping consistent bucket size.
