### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by Zheweiqiu** [facebookresearch/faiss#864]
Hi, 
Is there any guideline for offline installation of the python version?
Thanks in advance!

**Comment by mdouze** [comment]
If you don't need to compile from source, it is sufficient to copy the following files: 
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#python

**Comment by Zheweiqiu** [comment]
> If you don't need to compile from source, it is sufficient to copy the following files:
> https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#python

I did what it said but got the error "ImportError: No module named _swigfaiss".

**Comment by mdouze** [comment]
Please make sure you compiled for the right version of Python.

**Comment by Zheweiqiu** [comment]
> Please make sure you compiled for the right version of Python.

Hi,
Stating the problem clearly: 
I install faiss by using 'conda install faiss-cpu -c pytorch'; then I copy the package (i.e. faiss and faiss-1.5.2-py3.7.egg-info) into other environment i.e., docker, that never installs faiss before. When I try to do 'import faiss', I always the following error:

Traceback (most recent call last):
  File "/home/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/faiss/__init__.py", line 18, in <module>
    from .swigfaiss import *
  File "/home/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_swigfaiss'

For both environment, I use python 3.7 so I don't think python version is the cause.

Thank for any help!

**Comment by beauby** [comment]
> then I copy the package (i.e. faiss and faiss-1.5.2-py3.7.egg-info) into other environment

You need to copy the dependencies as well. The error you're seeing is because MKL, one of faiss' dependencies is not found.
