### ISSUE TITLE
Kmeans error

### ISSUE THREAD

**Issue by francescoli** [facebookresearch/faiss#900]
# Summary
Two 2D tensors with the same shape lead to different kmean result. The one read from csv get an error, but the random generated one runs OK

# Platform

OS: Unbuntu 14.04

Faiss version: Faiss-cpu 1.5.3

Faiss compilation options: using conda

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

## Code
```
import numpy as np
import faiss as fs

A = np.loadtxt('sift_10k.csv', dtype=float, delimiter=',')

B = np.random.rand(10000, 128).astype('float32')

print A
print B

print A.shape
print B.shape

ncentroids = 100
niter = 20
verbose = True
d = A.shape[1]

kmeans = fs.Kmeans(d, ncentroids, niter=niter, verbose=verbose)
kmeans.train(A)

np.savetxt('vocab_1k.txt',kmeans.centroids)
```
## Error Info
```
[[ 23.  53.   4. ...  18.  66.  33.]
 [126.  38.   0. ...  34.  30.  21.]
 [  0.   0.   0. ...   0.   0.  13.]
 ...
 [  5.   1.   0. ...   7.  33.  27.]
 [  2.  38. 135. ...   0.   0.   0.]
 [ 23.  11.  35. ...   0.  18.   7.]]
[[0.89541894 0.00223683 0.6539429  ... 0.28040436 0.39110968 0.48791024]
 [0.57830787 0.5340468  0.08764375 ... 0.00290395 0.31930214 0.42608193]
 [0.6888714  0.49050105 0.767181   ... 0.942297   0.25581676 0.13671431]
 ...
 [0.582841   0.6721598  0.42406493 ... 0.07052245 0.55508786 0.9895143 ]
 [0.29442012 0.4657543  0.2024351  ... 0.4854239  0.7695257  0.37914008]
 [0.15035798 0.9554772  0.7352968  ... 0.37981966 0.7891361  0.15399767]]
(10000, 128)
(10000, 128)
Traceback (most recent call last):
  File "sift_10k.py", line 20, in <module>
    kmeans.train(A)
  File "/home/dennis/anaconda2/lib/python2.7/site-packages/faiss/__init__.py", line 626, in train
    clus.train(x, self.index)
  File "/home/dennis/anaconda2/lib/python2.7/site-packages/faiss/__init__.py", line 50, in replacement_train
    self.train_c(n, swig_ptr(x), index)
  File "/home/dennis/anaconda2/lib/python2.7/site-packages/faiss/swigfaiss.py", line 1504, in train
    return _swigfaiss.Clustering_train(self, n, x, index)
TypeError: in method 'Clustering_train', argument 3 of type 'float const *'
```

**Comment by beauby** [comment]
Does it work if you replace
```
A = np.loadtxt('sift_10k.csv', dtype=float, delimiter=',')
```
with
```
A = np.loadtxt('sift_10k.csv', dtype=np.float32, delimiter=',')
```

**Comment by francescoli** [comment]
Solved, Thank you!
