### ISSUE TITLE
python -c "import faiss" error:ImportError: /root/ttian_faiss/faiss-master/python/_swigfaiss.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i

### ISSUE THREAD

**Issue by tian103041** [facebookresearch/faiss#938]
# Summary
# Platform

OS: CentOS 7.2

Faiss version: 8428f91

Faiss compilation options:

Running on:
- [√ ] CPU
- [   ] GPU

Interface: 
- [   ] C++
- [ √] Python

# Reproduction instructions

I install faiss using source code installation.It is normal when I preform make && make install make -C python, make -C python install, and i can run make misc/test_blas,./misc/test_blas. But when i import -c "import faiss", error occur:

>>> import faiss
Traceback (most recent call last):
  File "/root/ttian_faiss/faiss-master/python/faiss/swigfaiss.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: /root/ttian_faiss/faiss-master/python/faiss/_swigfaiss.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/ttian_faiss/faiss-master/python/faiss/__init__.py", line 18, in <module>
    from .swigfaiss import *
  File "/root/ttian_faiss/faiss-master/python/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/root/ttian_faiss/faiss-master/python/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/ttian_faiss/faiss-master/python/_swigfaiss.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i 

 Then I do the following:
 ldd -r _swigfaiss.so 
	linux-vdso.so.1 =>  (0x00007ffcf29d4000)
	libopenblas.so.0 => /usr/lib64/libopenblas.so.0 (0x00007fc2f8686000)
	libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007fc2f8305000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007fc2f8002000)
	libgomp.so.1 => /usr/local/lib64/libgomp.so.1 (0x00007fc2f7dd6000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007fc2f7bbf000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fc2f79a2000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fc2f75d5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc2fa7b4000)
	libgfortran.so.4 => /usr/lib64/./libgfortran.so.4 (0x00007fc2f74a7000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fc2f72a2000)
	libquadmath.so.0 => /usr/lib64/./libquadmath.so.0 (0x00007fc2f7066000)
undefined symbol: PyExc_ValueError	(./_swigfaiss.so)
undefined symbol: PyBool_Type	(./_swigfaiss.so)
undefined symbol: PyExc_IndexError	(./_swigfaiss.so)
undefined symbol: PyExc_SyntaxError	(./_swigfaiss.so)
undefined symbol: PyCapsule_Type	(./_swigfaiss.so)
undefined symbol: _Py_NoneStruct	(./_swigfaiss.so)
undefined symbol: PyExc_AttributeError	(./_swigfaiss.so)
undefined symbol: PyExc_IOError	(./_swigfaiss.so)
undefined symbol: PyExc_MemoryError	(./_swigfaiss.so)
undefined symbol: PyType_Type	(./_swigfaiss.so)
undefined symbol: PyExc_OverflowError	(./_swigfaiss.so)
undefined symbol: PyExc_ZeroDivisionError	(./_swigfaiss.so)
undefined symbol: PyExc_NotImplementedError	(./_swigfaiss.so)
undefined symbol: PyExc_RuntimeError	(./_swigfaiss.so)
undefined symbol: _Py_NotImplementedStruct	(./_swigfaiss.so)
undefined symbol: PyExc_TypeError	(./_swigfaiss.so)
undefined symbol: PyObject_GenericGetAttr	(./_swigfaiss.so)
undefined symbol: PyFloat_Type	(./_swigfaiss.so)
undefined symbol: PyExc_SystemError	(./_swigfaiss.so)
undefined symbol: PyExc_ImportError	(./_swigfaiss.so)
undefined symbol: PyTuple_SetItem	(./_swigfaiss.so)
undefined symbol: PyLong_AsLong	(./_swigfaiss.so)
undefined symbol: PyTuple_GetSlice	(./_swigfaiss.so)
undefined symbol: PyObject_GetAttr	(./_swigfaiss.so)
undefined symbol: PyImport_AddModule	(./_swigfaiss.so)
undefined symbol: PyObject_Call	(./_swigfaiss.so)
undefined symbol: PyObject_Init	(./_swigfaiss.so)
undefined symbol: PyInstanceMethod_New	(./_swigfaiss.so)
undefined symbol: PyObject_GetAttrString	(./_swigfaiss.so)
undefined symbol: PyErr_Restore	(./_swigfaiss.so)
undefined symbol: PyType_IsSubtype	(./_swigfaiss.so)
undefined symbol: PyModule_GetDict	(./_swigfaiss.so)
undefined symbol: PyModule_AddObject	(./_swigfaiss.so)
undefined symbol: PyUnicode_InternFromString	(./_swigfaiss.so)
undefined symbol: PyTuple_New	(./_swigfaiss.so)
undefined symbol: PyObject_SetAttr	(./_swigfaiss.so)
undefined symbol: PyObject_IsInstance	(./_swigfaiss.so)
undefined symbol: PyEval_RestoreThread	(./_swigfaiss.so)
undefined symbol: PyDict_SetItemString	(./_swigfaiss.so)
undefined symbol: PyUnicode_FromFormat	(./_swigfaiss.so)
undefined symbol: PyLong_AsDouble	(./_swigfaiss.so)
undefined symbol: PyTuple_Size	(./_swigfaiss.so)
undefined symbol: _PyObject_New	(./_swigfaiss.so)
undefined symbol: PyErr_Format	(./_swigfaiss.so)
undefined symbol: PyFloat_FromDouble	(./_swigfaiss.so)
undefined symbol: PyFloat_AsDouble	(./_swigfaiss.so)
undefined symbol: PyUnicode_DecodeUTF8	(./_swigfaiss.so)
undefined symbol: PyImport_ImportModule	(./_swigfaiss.so)
undefined symbol: PyUnicode_FromString	(./_swigfaiss.so)
undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i	(./_swigfaiss.so)
undefined symbol: PyErr_Clear	(./_swigfaiss.so)
undefined symbol: Py_DecRef	(./_swigfaiss.so)
undefined symbol: PyCapsule_Import	(./_swigfaiss.so)
undefined symbol: PyLong_FromVoidPtr	(./_swigfaiss.so)
undefined symbol: PyErr_SetString	(./_swigfaiss.so)
undefined symbol: PyCapsule_New	(./_swigfaiss.so)
undefined symbol: PyArg_ParseTuple	(./_swigfaiss.so)
undefined symbol: PyGILState_Release	(./_swigfaiss.so)
undefined symbol: PyCapsule_GetPointer	(./_swigfaiss.so)
undefined symbol: PyObject_Free	(./_swigfaiss.so)
undefined symbol: _ZNK5faiss14ParameterSpace16combination_nameEm	(./_swigfaiss.so)
undefined symbol: PyType_Ready	(./_swigfaiss.so)
undefined symbol: PyObject_Size	(./_swigfaiss.so)
undefined symbol: PyEval_SaveThread	(./_swigfaiss.so)
undefined symbol: _ZN5faiss15OperatingPoints10merge_withERKS0_RKSs	(./_swigfaiss.so)
undefined symbol: PyLong_FromLong	(./_swigfaiss.so)
undefined symbol: PyErr_WriteUnraisable	(./_swigfaiss.so)
undefined symbol: PyObject_IsTrue	(./_swigfaiss.so)
undefined symbol: PyModule_Create2	(./_swigfaiss.so)
undefined symbol: PyLong_AsUnsignedLong	(./_swigfaiss.so)
undefined symbol: PyLong_FromSize_t	(./_swigfaiss.so)
undefined symbol: PyErr_Occurred	(./_swigfaiss.so)
undefined symbol: _ZN5faiss15OperatingPoints3addEddRKSsm	(./_swigfaiss.so)
undefined symbol: PyErr_Fetch	(./_swigfaiss.so)
undefined symbol: PyObject_CallFunctionObjArgs	(./_swigfaiss.so)
undefined symbol: PyLong_FromUnsignedLong	(./_swigfaiss.so)
undefined symbol: PyErr_CheckSignals	(./_swigfaiss.so)
undefined symbol: PyArg_UnpackTuple	(./_swigfaiss.so)
undefined symbol: PyGILState_Ensure	(./_swigfaiss.so)
undefined symbol: PyObject_Malloc	(./_swigfaiss.so)
undefined symbol: PyErr_Print	(./_swigfaiss.so)
undefined symbol: PyUnicode_Concat	(./_swigfaiss.so)
undefined symbol: PyUnicode_AsUTF8String	(./_swigfaiss.so)
undefined symbol: PyBytes_AsStringAndSize	(./_swigfaiss.so)
undefined symbol: PyBool_FromLong	(./_swigfaiss.so)

I don't know why it's appear _ZN5faiss15OperatingPoints10merge_withERKS0_RKSs,
_ZN5faiss14FaissExceptionC1ERKSsPKcS4_i.......  undefined

**Comment by mdouze** [comment]
no activity, closing.
