### ISSUE TITLE
Docker failed to build

### ISSUE THREAD

**Issue by ljstrnadiii** [facebookresearch/faiss#991]
# Summary
I am simply trying to build the docker file as stated in the intall.md file and tests are not passing... I am not using `nvidia-docker` and just want to use CPU operations for now. I do know that nvidia drivers do not support debian, which is my current os. 

# Platform

`4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

# Reproduction instructions

`docker build -t faiss github.com/facebookresearch/faiss`

and I get 

```
======================================================================
ERROR: test_extra_distances (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_extra_distances
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/opt/faiss/tests/test_extra_distances.py", line 16, in <module>
    import scipy.spatial.distance
ImportError: No module named scipy.spatial.distance


======================================================================
ERROR: test_OIVFPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 513, in test_OIVFPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_OPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 484, in test_OPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

----------------------------------------------------------------------
Ran 155 tests in 85.588s

FAILED (errors=3)
```

**Comment by ljstrnadiii** [comment]
Not sure if this is helpful for you, @mdouze and @beauby, but I ended up building an image by installing miniconda and using the conda gpu install.

```
FROM nvidia/cuda:9.0-devel-ubuntu16.04

# System packages
RUN apt-get update && apt-get install -y curl

# Install miniconda to /miniconda
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
RUN bash Miniconda-latest-Linux-x86_64.sh -p /miniconda -b
RUN rm Miniconda-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda

# faiss-gpu 
RUN conda install -y faiss-gpu cudatoolkit=9.0 -c pytorch
# extras
RUN conda install -y matplotlib jupyter pandas scikit-learn scipy

CMD ["jupyter-notebook",  "--no-browser", "--ip=0.0.0.0", "--notebook-dir=/", "--allow-root", "--port=8000"]
```

The image is about 6.64Gb (pretty big!) and contains cudatoolkit 9 and faiss-gpu-1.6

There is probably some redundancy during install, but this works for me for now.  Any concerns?

**Comment by Ai-is-light** [comment]
@ljstrnadiii would you mind sharing your docker image or upload it to dockerhub?
thx

**Comment by ljstrnadiii** [comment]
@Ai-is-light sorry no can do, but you can simply build the thing yourself pretty easily. Just make the file above and call it Dockerfile, then

`docker build Dockerfile .`

**Comment by jingyuanz** [comment]
met exactly the same issue on centos, neither gpu nor cpu version can build. Would the above solution end up using a gpu version?

**Comment by ljstrnadiii** [comment]
The Dockerfile I posted above? Yes, hence the faiss-gpu install

**Comment by jingyuanz** [comment]
> The Dockerfile I posted above? Yes, hence the faiss-gpu install

Thank you. I was wonderring if this dockerfile would fail on a GPUless server, but now it is solved.

**Comment by nan-wang** [comment]
@ljstrnadiii I ran into the same error.

```
======================================================================
ERROR: test_OIVFPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 513, in test_OIVFPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_OPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 484, in test_OPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'
```
These two errors are due to the out-dated `numpy` version in the image. The `numpy` in the image is `1.7.1`, however the `norm()` from the `numpy` below `1.8.0` does **NOT** take `axis` argument. 
### Reference:
[numpy1.7.1::numpy.linalg.norm()](https://docs.scipy.org/doc/numpy-1.7.0/reference/generated/numpy.linalg.norm.html#numpy.linalg.norm)
[numpy1.8.0::numpy.linalg.norm()](https://docs.scipy.org/doc/numpy-1.8.0/reference/generated/numpy.linalg.norm.html#numpy.linalg.norm)

**Comment by nan-wang** [comment]
```
======================================================================
ERROR: test_extra_distances (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_extra_distances
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/opt/faiss/tests/test_extra_distances.py", line 16, in <module>
    import scipy.spatial.distance
ImportError: No module named scipy.spatial.distance
```

It turns out that `scipy` is not installed in the image at all. 😜

**Comment by ndtreviv** [comment]
Also experiencing this on Ubuntu 16.04 on a g4dn.xlarge ec2 instance:
```
======================================================================
ERROR: test_OIVFPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 543, in test_OIVFPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_OPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 514, in test_OPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_extra_distances (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_extra_distances
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/opt/faiss/tests/test_extra_distances.py", line 16, in <module>
    import scipy.spatial.distance
ImportError: No module named scipy.spatial.distance


======================================================================
ERROR: test_shuffle (test_binary_hashindex.TestSmallFuncs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_binary_hashindex.py", line 41, in test_shuffle
    oinv[o] = np.arange(d)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

----------------------------------------------------------------------
Ran 181 tests in 45.943s

FAILED (errors=4)
 0 xnew 0
nbit 46 xref 1f5142cc8064 xnew 1f5142cc8064
nbit 1 xref 1 xnew 1
nbit 1 xref 0 xnew 0
nbit 62 xref 3f54519128e7da2a xnew 3f54519128e7da2a
nbit 15 xref 16f3 xnew 16f3
nbit 1 xref 1 xnew 1
nbit 46 xref 11a76c671602 xnew 11a76c671602
nbit 13 xref 874 xnew 874
nbit 37 xref 171c63a504 xnew 171c63a504
nbit 50 xref 375eee460bd6f xnew 375eee460bd6f
nbit 40 xref 8d4eb1e034 xnew 8d4eb1e034
nbit 34 xref 1a8c4bac0 xnew 1a8c4bac0
nbit 14 xref 36f1 xnew 36f1
nbit 59 xref 5996b95a1674ece xnew 5996b95a1674ece
nbit 1 xref 1 xnew 1
nbit 5 xref 10 xnew 10
nbit 1 xref 0 xnew 0
nbit 16 xref 5e4c xnew 5e4c
nbit 35 xref 1179f63e xnew 1179f63e
nbit 33 xref 19052bc95 xnew 19052bc95
nbit 1 xref 0 xnew 0
nbit 3 xref 7 xnew 7
nbit 36 xref 758dc440d xnew 758dc440d
nbit 2 xref 3 xnew 3
nbit 14 xref 2c0 xnew 2c0
nbit 9 xref 16c xnew 16c
nbit 1 xref 1 xnew 1
nbit 11 xref 80 xnew 80
nbit 8 xref 7e xnew 7e
nbit 30 xref 19385dbe xnew 19385dbe
nbit 1 xref 1 xnew 1
nbit 1 xref 1 xnew 1
nbit 2 xref 1 xnew 1
nbit 58 xref 12316dc4a8193a2 xnew 12316dc4a8193a2
nbit 26 xref 3bf61d5 xnew 3bf61d5
nbit 1 xref 0 xnew 0
nbit 52 xref 20f1a69e47aa3 xnew 20f1a69e47aa3
nbit 1 xref 0 xnew 0
nbit 48 xref 9dcd17a8fa97 xnew 9dcd17a8fa97
nbit 37 xref 1a67ca04a9 xnew 1a67ca04a9
nbit 16 xref 8cfa xnew 8cfa
nbit 1 xref 0 xnew 0
nbit 5 xref 8 xnew 8
nbit 1 xref 1 xnew 1
nbit 30 xref 5308776 xnew 5308776
nbit 1 xref 0 xnew 0
nbit 26 xref b0684a xnew b0684a
nbit 1 xref 1 xnew 1
nbit 1 xref 1 xnew 1
nbit 37 xref b1b47bf33 xnew b1b47bf33
nbit 2 xref 2 xnew 2
nbit 9 xref 49 xnew 49
nbit 2 xref 0 xnew 0
nbit 1 xref 1 xnew 1
nbit 2 xref 0 xnew 0
nbit 24 xref dadd70 xnew dadd70
nbit 12 xref 11d xnew 11d
nbit 11 xref 676 xnew 676
nbit 3 xref 1 xnew 1
nbit 1 xref 0 xnew 0
nbit 1 xref 0 xnew 0
nbit 4 xref b xnew b
nbit 18 xref 4511 xnew 4511
nbit 6 xref 30 xnew 30
nbit 22 xref 1e0362 xnew 1e0362
nbit 1 xref 1 xnew 1
nbit 8 xref ba xnew ba
nbit 19 xref 3aa33 xnew 3aa33
nbit 61 xref c3f2a8045e0907d xnew c3f2a8045e0907d
nbit 18 xref 1fa64 xnew 1fa64
nbit 1 xref 0 xnew 0
make: *** [test] Error 1
The command '/bin/sh -c make test' returned a non-zero code: 2
```
